import { LessonsData } from './types';

/** 20世紀（1900-1999）戦争の教訓データ */
export const LESSONS_20TH_CENTURY: Record<string, LessonsData> = {
  'world-war-1': {
    commonalities: '<strong>同盟連鎖による拡大</strong>パターンは<code>balkan-wars</code>・<code>franco-prussian-war</code>と直結。サラエボ事件→墺セ最後通牒→露総動員→独宣戦の連鎖は、<code>world-war-2-europe</code>の宥和政策失敗とも対をなす古典事例。',
    universality: '<strong>chain-ganging（同盟連鎖）</strong>と<strong>攻撃優位の幻想</strong>（Stephen Van Evera "Cult of the Offensive"）が典型的に作動。シュリーフェン計画は<strong>機会の窓</strong>論理（露の鉄道完成前に叩く）に依拠し、セキュリティ・ジレンマを暴走させた。',
    modernLessons: '<strong>ロシア・ウクライナ戦争(2022-)</strong>の起点である「NATO東方拡大の脅威認識」、また<strong>米中対立・台湾海峡</strong>での「習近平の機会の窓」論はWWI類似。地域紛争(<code>balkan-wars</code>型)が大国関与で世界戦争化するメカニズムは現存。',
    preventable: 'Christopher Clark <em>The Sleepwalkers</em>(2012)は「全員が夢遊病者のように戦争へ歩いた」と評し、誰も望まぬ戦争が起きうると示した。A.J.P. Taylorは鉄道時刻表動員論で「動員=開戦」の硬直性を指摘。Henry Kissingerは外交柔軟性喪失を防止失敗の核心と論じた。',
    reproducibility: '警戒先行指標：<strong>同盟構造硬直化</strong>、軍拡競争、ナショナリズム高揚、メディア戦争扇動、軍事計画の政治制御喪失、相互不信の螺旋。これらが揃えば「7月危機」型暴走は再発しうる。',
  },
  'world-war-2-europe': {
    commonalities: '<code>world-war-1</code>のヴェルサイユ体制の延長線上にある「20年休戦」(Foch元帥)。<code>spanish-civil-war</code>はリハーサル、<code>winter-war</code>・<code>second-italo-ethiopian-war</code>は集団安全保障崩壊の前段階。',
    universality: '<strong>バック・パッシング（責任転嫁）</strong>(John Mearsheimer)が決定的役割。英仏は対独抑止責任を相互に押し付け、宥和政策はヒトラーに<strong>機会の窓</strong>を与えた。修正主義国家×現状維持国家×不十分な抑止という古典構図。',
    modernLessons: '<strong>ロシア・ウクライナ戦争(2022-)</strong>でのクリミア併合(2014)放置は「ミュンヘン会談2.0」と批判される。<strong>米中対立・台湾海峡</strong>でも台湾への曖昧戦略がバック・パッシングを誘発するリスク。修正主義国家初動への抑止失敗は破滅を招く。',
    preventable: 'A.J.P. Taylor <em>The Origins of the Second World War</em>(1961)はヒトラー固有性より構造要因を強調、論争を呼んだ。Mearsheimerは「英仏のオフショア・バランシング不全」が原因と分析。Kissingerはヴェルサイユの「過酷すぎて緩く、緩すぎて過酷」の中途半端さを問題視。',
    reproducibility: '警戒指標：<strong>戦間期型</strong>経済危機×ナショナリズム×領土修正主義×大国の責任回避。民主主義疲労、強権指導者待望論、軍縮条約崩壊、武力使用閾値低下が同時進行すれば再発リスク。',
  },
  'pacific-war': {
    commonalities: '<code>second-sino-japanese-war</code>の延長で<code>world-war-2-europe</code>と接続。<code>russo-japanese-war</code>勝利体験が<strong>経路依存</strong>を生み、対米開戦への自縛を作った。',
    universality: '<strong>経路依存</strong>と<strong>グループシンク</strong>(Irving Janis)の典型。ハル・ノート受諾不可という閉塞下で「ジリ貧より一撃講和」論理が暴走。日本軍部は<strong>攻撃優位の幻想</strong>に陥り、米国の戦争遂行能力(GDP比10倍)を過小評価した。',
    modernLessons: '<strong>米中対立・台湾海峡</strong>で習近平政権が「資源・技術封じ込め」を「ABCD包囲網」類比で解釈する危険。経済制裁が当事国の被害者意識を強化し誤算を呼ぶメカニズムは<strong>ロシア・ウクライナ戦争(2022-)</strong>でも観察される。',
    preventable: 'Robert Butow <em>Tojo and the Coming of the War</em>は組織的意思決定の機能不全を分析。Scott Sagan "The Origins of the Pacific War"はリスク不可避論者と回避可能論者を整理。野村・来栖外交の機会喪失は防止可能性を示唆するが、軍部統制不能が決定的障害だった。',
    reproducibility: '警戒指標：<strong>資源依存×経済封鎖×軍部自律性</strong>、文民統制喪失、メディア戦争扇動、勝利幻想の再生産、相手国意思の構造的誤読。エネルギー安全保障論が暴発装置になる構図は再現性が高い。',
  },
  'korean-war': {
    commonalities: '<code>vietnam-war</code>と並ぶ冷戦代理戦争の典型。<code>chinese-civil-war</code>(1949中共勝利)と<code>russo-japanese-war</code>以来の朝鮮半島地政学が連結。<code>cuban-revolution</code>と並ぶ陣営化の起点。',
    universality: '<strong>誤算による戦争</strong>の代表例。Achesonの不後退線声明(1950.1)で韓国除外→金日成・スターリンが<strong>機会の窓</strong>と誤認。中国介入も米軍北上による<strong>セキュリティ・ジレンマ</strong>暴走。<strong>リムランド理論</strong>(Spykman)実証ケース。',
    modernLessons: '<strong>朝鮮半島</strong>は休戦状態のまま21世紀へ。北朝鮮核武装と<strong>米中対立</strong>下で再戦リスク継続。曖昧戦略が侵略誘発する教訓は<strong>台湾海峡</strong>に直接適用される。',
    preventable: 'Bruce Cumings <em>The Origins of the Korean War</em>は内戦的性格を強調、米ソ責任論を相対化。Allen Whiting <em>China Crosses the Yalu</em>は中国介入のシグナル誤読を分析。明確な抑止コミットメントがあれば防止可能だったとの議論が主流。',
    reproducibility: '警戒指標：<strong>分断国家×大国コミットメント曖昧化×指導者の機会窓認識</strong>。経済格差拡大、体制崩壊不安、核開発進展が組み合わさる現朝鮮半島はまさに該当条件下。',
  },
  'vietnam-war': {
    commonalities: '<code>first-indochina-war</code>の直接継承、<code>korean-war</code>型代理戦争パターン、<code>soviet-afghan-war</code>と並ぶ大国介入失敗例。<code>cambodian-genocide</code>を波及的に誘発。',
    universality: '<strong>沈没費用効果</strong>と<strong>ドミノ理論</strong>(信念体系)の暴走。Robert Jervis <em>Perception and Misperception</em>が示す認知バイアス（共産主義一枚岩誤認）が顕著。<strong>非対称戦争</strong>で物量優位が無効化された古典例。',
    modernLessons: '<strong>米中対立</strong>下で南シナ海・台湾介入時の「ベトナム化」リスク。<strong>ロシア・ウクライナ戦争(2022-)</strong>でロシアが直面する泥沼化はベトナム類似。対反乱戦の限界は<code>afghanistan-war</code>でも再証明された。',
    preventable: 'Daniel Ellsberg <em>Pentagon Papers</em>は政府内部で勝算なしと認識されつつ撤退できなかった構造を暴露。H.R. McMaster <em>Dereliction of Duty</em>は軍政関係不全を分析。Kissingerは「名誉ある撤退」交渉の遅延を批判。',
    reproducibility: '警戒指標：<strong>イデオロギー反共/反テロのドミノ論</strong>、軍事的解決可能信念、現地政権腐敗放置、撤退コスト過大評価、メディア戦況乖離。介入泥沼化条件は再現性高い。',
  },
  'gulf-war': {
    commonalities: '<code>iran-iraq-war</code>後のイラク疲弊→誤算による侵攻という連鎖。<code>falklands-war</code>と並ぶ「明確な侵略への国際的反応」事例。<code>iraq-war</code>の前段階。',
    universality: '<strong>誤算</strong>の古典例。サダムはApril Glaspie発言を米国不介入シグナルと誤読。<strong>機会の窓</strong>論理（冷戦終結直後の混乱期）も作動。一方、米国は<strong>新世界秩序</strong>論で多国籍軍を正当化、集団安全保障を機能させた稀少例。',
    modernLessons: '<strong>ロシア・ウクライナ戦争(2022-)</strong>での国際法違反侵略への対応モデルとして参照される。一方、過剰な勝利幻想が<code>iraq-war</code>誤算を生んだ点は<strong>米中対立</strong>での教訓。',
    preventable: 'Lawrence Freedman <em>The Gulf Conflict</em>は外交シグナルの曖昧さを批判。Kissingerは「明確な抑止」の重要性を強調。Glaspie電報問題は防止可能性論争の核心で、明示的レッドラインがあれば抑止できた可能性が高い。',
    reproducibility: '警戒指標：<strong>独裁者の財政危機×領土主張×大国シグナル誤読</strong>。資源紛争、国境画定の曖昧さ、債権国-債務国対立は再現条件として現存。',
  },
  'russian-civil-war': {
    commonalities: '<code>russian-revolution</code>の延長、<code>spanish-civil-war</code>と並ぶ20世紀イデオロギー内戦の原型。<code>chinese-civil-war</code>の手本となった。<code>world-war-1</code>敗戦の余波。',
    universality: '<strong>権力真空</strong>と<strong>イデオロギー動員</strong>の組み合わせ。Theda Skocpol <em>States and Social Revolutions</em>は国家崩壊と社会革命の連動を理論化。外国干渉(連合国14カ国)は<strong>セキュリティ・ジレンマ</strong>を悪化させた。',
    modernLessons: '<strong>シリア内戦</strong>・<strong>リビア内戦</strong>で見られる多勢力混戦+外国介入パターンの原型。体制崩壊後の権力真空管理失敗は現代中東で繰り返される。',
    preventable: 'Richard Pipes <em>The Russian Revolution</em>はボリシェヴィキの専制不可避論。Sheila Fitzpatrickは社会的支持基盤を強調。臨時政府の戦争継続選択が致命的だったとの見方が広く、ケレンスキーの判断ミスが防止失敗の核心。',
    reproducibility: '警戒指標：<strong>戦時下体制崩壊×イデオロギー武装勢力×外国介入</strong>。経済崩壊、軍隊崩壊、複数権力中心並存の現象は脆弱国家で常時観察される。',
  },
  'spanish-civil-war': {
    commonalities: '<code>russian-civil-war</code>のイデオロギー内戦パターン、<code>world-war-2-europe</code>のリハーサル。<code>greek-civil-war</code>と並ぶ冷戦前哨戦。',
    universality: '<strong>イデオロギー国際化</strong>と<strong>代理戦争化</strong>の典型。独伊が反共実験場として、ソ連が国際旅団を通じて介入。集団安全保障(国際連盟・不干渉委員会)の機能不全を露呈し、<strong>バック・パッシング</strong>(英仏の責任回避)が枢軸を勢いづけた。',
    modernLessons: '<strong>シリア内戦</strong>での露・イラン×米・トルコ・湾岸の代理介入構造は酷似。<strong>イエメン内戦</strong>もサウジ-イラン代理戦争。内戦が地域大国対立の実験場となる構図は現存。',
    preventable: 'Hugh Thomas <em>The Spanish Civil War</em>は不干渉政策の偽善性を分析。Paul Prestonは英仏のフランコ事実上容認が共和派敗北を決定づけたと論じる。早期国際介入か厳格不干渉のどちらかであれば異なる結果となった可能性。',
    reproducibility: '警戒指標：<strong>社会的分極化×軍部クーデタ×外国イデオロギー介入</strong>。民主主義後退、極右極左台頭、SNS分断扇動が組み合わされば内戦化リスク。',
  },
  'six-day-war': {
    commonalities: '<code>first-arab-israeli-war</code>・<code>suez-crisis</code>の継承、<code>yom-kippur-war</code>を誘発。中東紛争の構造的反復。',
    universality: '<strong>予防戦争</strong>と<strong>攻撃優位</strong>の教科書事例。Michael Oren <em>Six Days of War</em>は誤算螺旋を詳述。ナセルのチラン海峡封鎖はイスラエル先制を招き、<strong>セキュリティ・ジレンマ</strong>と<strong>機会の窓</strong>論理が同時作動。',
    modernLessons: '<strong>イラン核問題</strong>でイスラエルの先制攻撃論は六日戦争モデルを参照。<strong>台湾海峡</strong>や<strong>朝鮮半島</strong>での先制攻撃誘惑は同論理。占領地問題が長期紛争を生む教訓は<strong>ガザ戦争</strong>に直結。',
    preventable: 'Avi Shlaim <em>The Iron Wall</em>はナセルの瀬戸際外交の意図せざる結果論を提示。Tom Segevは情報誤認を強調。エジプトの示威行動エスカレーション抑制があれば回避可能だったとの議論が主流。',
    reproducibility: '警戒指標：<strong>瀬戸際外交×先制攻撃ドクトリン×シーレーン封鎖</strong>。海峡封鎖、軍事威嚇、第三国介入示唆という組合せは現代中東・東アジアで継続。',
  },
  'yom-kippur-war': {
    commonalities: '<code>six-day-war</code>の屈辱への報復、<code>first-arab-israeli-war</code>以来の構造的紛争の継続。石油危機と連動。',
    universality: '<strong>勝利症候群</strong>(victory disease)と<strong>情報判断バイアス</strong>(コンセプション)の典型。Uri Bar-Joseph <em>The Watchman Fell Asleep</em>はイスラエル情報部の構造的盲点を分析。<strong>限定戦争</strong>(Sadat)が政治目的達成手段となった事例。',
    modernLessons: '<strong>ロシア・ウクライナ戦争(2022-)</strong>緒戦の露軍誤算、<strong>ガザ戦争</strong>(2023.10.7)の情報失敗は同型。優越者の慢心が奇襲を許す構図は<strong>米中対立</strong>でも警戒対象。',
    preventable: 'Henry Kissingerは「外交が戦争に追い越された」と評価。Janice Stein <em>Threat Perception in International Relations</em>は認知パラダイムを分析。サダトの和平意図シグナルをイスラエル・米国が読めなかったことが核心的失敗。',
    reproducibility: '警戒指標：<strong>勝利後の慢心×限定戦争による政治目的×情報部のコンセプション固着</strong>。サイバー時代の警告無視、確証バイアスは制度設計で再発しうる。',
  },
  'first-indo-pakistani-war': {
    commonalities: '<code>second-indo-pakistani-war</code>・<code>kargil-war</code>・<code>bangladesh-liberation-war</code>と続く印パ反復紛争の起点。<code>first-arab-israeli-war</code>と並ぶ脱植民地化×宗教分割パターン。',
    universality: '<strong>分割の遺産</strong>(partition legacy)と<strong>地位曖昧領土</strong>論。カシミール藩王国の決定遅延が<strong>権力真空</strong>を生んだ。Stanley Wolpert <em>Jinnah of Pakistan</em>は分割の人為性を強調。',
    modernLessons: '<strong>カシミール</strong>は核保有国間紛争として最大級リスク。中印係争(<code>sino-indian-war</code>継承)、<strong>米中対立</strong>下のインド太平洋戦略にも直結。',
    preventable: 'Mountbatten分割線の拙速さが学界では広く批判される。Ayesha Jalal <em>The Sole Spokesman</em>は分割不可避論を相対化。藩王国地位の事前明確化があれば回避可能だった可能性。',
    reproducibility: '警戒指標：<strong>宗教民族分断×領土未画定×核武装</strong>。脱植民地化遺産は南アジア・中東で継続的に再発火源として機能。',
  },
  'sino-indian-war': {
    commonalities: '<code>first-indo-pakistani-war</code>と並ぶアジア独立後紛争。<code>kargil-war</code>と類似の山岳国境紛争。<code>russo-japanese-war</code>以来の東アジア大国対決系譜。',
    universality: '<strong>マクマホンライン</strong>等植民地遺産国境の曖昧性。<strong>機会の窓</strong>(キューバ危機で米注意分散)を毛沢東が活用。Neville Maxwell <em>India\'s China War</em>は印側挑発論、論争的だが影響大。',
    modernLessons: '<strong>米中対立</strong>下のインド太平洋戦略でインドの位置づけ、ガルワン渓谷衝突(2020)等継続的緊張。<strong>QUAD</strong>形成の歴史的背景。',
    preventable: 'Mearsheimerは中国の修正主義行動原型と分析。インドのフォワード・ポリシーが挑発的だったとの自省も学界に存在。境界画定交渉の優先があれば防止可能だった。',
    reproducibility: '警戒指標：<strong>未画定国境×大国機会窓×ナショナリズム</strong>。ヒマラヤ・南シナ海等での反復リスク。',
  },
  'second-indo-pakistani-war': {
    commonalities: '<code>first-indo-pakistani-war</code>の継続、<code>kargil-war</code>の前史。<code>six-day-war</code>と同年(1965)で大国冷戦下の地域戦争パターン。',
    universality: '<strong>抜き打ち戦略</strong>(Operation Gibraltar)の典型的失敗。<strong>攻撃優位の幻想</strong>に基づくパキスタンの誤算。米ソ共同調停(タシケント)は冷戦下の<strong>大国協調</strong>稀少例。',
    modernLessons: '<strong>カシミール紛争</strong>継続、印パ核保有後の限定戦争リスク管理問題。',
    preventable: 'Sumit Ganguly <em>Conflict Unending</em>はパキスタン側の戦略的誤算を中心要因と分析。インドの自制と国際調停があれば早期収束可能だった。',
    reproducibility: '警戒指標：<strong>非正規工作員浸透×通常戦争エスカレーション</strong>。ハイブリッド戦争の原型として現代に通用。',
  },
  'bangladesh-liberation-war': {
    commonalities: '<code>first-indo-pakistani-war</code>系譜、<code>biafra-war</code>と並ぶ脱植民地化国家の分離独立紛争。<code>cambodian-genocide</code>と並ぶ大規模虐殺事例。',
    universality: '<strong>多民族国家の構造的矛盾</strong>と<strong>人道的介入</strong>論の先駆。Gary Bass <em>The Blood Telegram</em>はニクソン-キッシンジャーの傍観を批判。<strong>セキュリティ・ジレンマ</strong>でインドの介入が決定的。',
    modernLessons: '<strong>R2P(保護する責任)</strong>原則の起源的事例。<strong>ミャンマー内戦</strong>・<strong>シリア内戦</strong>での虐殺対応問題に直結。',
    preventable: 'パキスタン軍政の選挙結果無視(アワミ連盟勝利の否定)が直接原因。早期権力移譲があれば防止可能だったとの見方が学界主流。',
    reproducibility: '警戒指標：<strong>民主選挙結果の軍部否定×民族抑圧×大国傍観</strong>。多民族国家の分離独立リスクは現代も継続。',
  },
  'kargil-war': {
    commonalities: '<code>first-indo-pakistani-war</code>・<code>second-indo-pakistani-war</code>系譜の継続。核保有後初の印パ戦争として<code>iran-iraq-war</code>後の紛争パターンと類似。',
    universality: '<strong>核保有下の限定戦争</strong>論(stability-instability paradox)の実証。Glenn Snyder理論通り、核抑止が通常戦争を抑制せず却って下位レベル冒険主義を促進。',
    modernLessons: '<strong>米中対立・台湾海峡</strong>での核下限定戦争リスク、<strong>ロシア・ウクライナ戦争(2022-)</strong>の核脅迫下通常戦争に直結する重要事例。',
    preventable: 'Ashley Tellis <em>Limited Conflicts Under the Nuclear Umbrella</em>はムシャラフの軍事的冒険主義を批判。文民統制があれば防止可能だった。',
    reproducibility: '警戒指標：<strong>核保有下のサラミ戦術×軍部自律×文民統制弱体化</strong>。核拡散時代の典型リスクとして高再現性。',
  },
  'russo-japanese-war': {
    commonalities: '<code>first-sino-japanese-war</code>勝利体験の延長、<code>pacific-war</code>に至る経路依存の起点。<code>world-war-1</code>と並ぶ近代総力戦の先駆。',
    universality: '<strong>新興国×衰退帝国</strong>のツキディデスの罠型対立。Graham Allison枠組みの古典適用例。<strong>攻撃優位</strong>(旅順奇襲)と<strong>機会の窓</strong>(露シベリア鉄道未完)論理が決定。',
    modernLessons: '<strong>米中対立</strong>でのパワートランジション論、<strong>台湾海峡</strong>での先制攻撃誘惑分析の歴史的参照点。',
    preventable: 'J.N. Westwood <em>Russia Against Japan</em>は露の極東過剰拡張を主因と分析。日露交渉の妥協余地はあったとの見解が学界に存在し、満韓交換論受諾なら回避可能性あり。',
    reproducibility: '警戒指標：<strong>台頭国の名誉欲求×衰退国の威信防衛×第三勢力の煽動</strong>。東アジア海洋覇権争いに直接適用される。',
  },
  'boxer-rebellion': {
    commonalities: '<code>second-opium-war</code>系譜の反植民地反乱、<code>chinese-civil-war</code>の遠因となる清朝弱体化加速。<code>indian-rebellion</code>と並ぶ反西洋反乱パターン。',
    universality: '<strong>反グローバリゼーション暴動</strong>の原型。8カ国共同出兵は<strong>大国協調</strong>稀少事例だが帝国主義分割を加速。義和団は外圧×経済破綻×千年王国思想の合流。',
    modernLessons: '反西洋ナショナリズム噴出パターンは現代中東・中国民族主義に通底。<strong>米中対立</strong>での「百年屈辱」記憶政治化の起点。',
    preventable: 'Joseph Esherick <em>The Origins of the Boxer Uprising</em>は社会経済的要因を強調。清朝の早期改革と列強自制があれば緩和可能だった。',
    reproducibility: '警戒指標：<strong>外資圧迫×伝統社会動揺×千年王国思想</strong>。グローバル化反動として現代でも観察可能。',
  },
  'second-sino-japanese-war': {
    commonalities: '<code>first-sino-japanese-war</code>・<code>russo-japanese-war</code>勝利体験の延長、<code>pacific-war</code>と一体化。<code>chinese-civil-war</code>の構図を決定。',
    universality: '<strong>泥沼化</strong>と<strong>下剋上</strong>(出先軍部の独走)。盧溝橋事件は現地衝突が拡大した<strong>火事場ジレンマ</strong>。<strong>サンクコスト効果</strong>で和平機会(トラウトマン工作)を逃した。',
    modernLessons: '<strong>米中対立</strong>での偶発衝突エスカレーションリスク、<strong>南シナ海</strong>での現場部隊自律行動リスクに直結。',
    preventable: 'Rana Mitter <em>Forgotten Ally</em>は日本軍部統制不全を主因と分析。文民統制機能と早期和平交渉受諾があれば限定可能だった。',
    reproducibility: '警戒指標：<strong>現地軍独走×文民統制喪失×和平機会逸失</strong>。シビリアン・コントロール劣化は普遍的リスク。',
  },
  'first-indochina-war': {
    commonalities: '<code>vietnam-war</code>の前史、<code>algerian-war</code>と並ぶ仏植民地戦争。<code>malayan-emergency</code>・<code>kenyan-independence-war</code>と同時代脱植民地化戦争。',
    universality: '<strong>植民地復帰の経済不可能性</strong>と<strong>反乱戦の非対称性</strong>。Mao三段階論実証。仏のディエンビエンフー敗北は<strong>過拡張</strong>と<strong>地形軽視</strong>の典型。',
    modernLessons: '対反乱戦の限界として<code>afghanistan-war</code>・<code>iraq-war</code>と直結。「現地化」幻想の失敗教訓。',
    preventable: 'Bernard Fall <em>Street Without Joy</em>は仏の戦略的誤りを詳述。早期独立承認(ホー・チ・ミン交渉)があれば回避可能だった。ドゴール後継政権の硬直性が決定的。',
    reproducibility: '警戒指標：<strong>植民地経済利害×ナショナリズム×大国代理化</strong>。覇権衰退期の撤退失敗パターンは現代に通用。',
  },
  'greek-civil-war': {
    commonalities: '<code>spanish-civil-war</code>と並ぶイデオロギー内戦、<code>russian-civil-war</code>のパターン継承。冷戦の最初期熱戦として<code>korean-war</code>に先行。',
    universality: '<strong>トルーマン・ドクトリン</strong>の発動契機。<strong>封じ込め政策</strong>(George Kennan)の現実適用第一号。チトーのソ連離脱が共産派敗北を決定づけた。',
    modernLessons: '<strong>シリア内戦</strong>等での代理戦争パターン分析の参照点。冷戦的封じ込め論理が<strong>米中対立</strong>で再活性化。',
    preventable: 'C.M. Woodhouseは英国撤退と米国引継ぎの過渡期混乱を分析。早期妥協政府形成があれば内戦化回避可能だった。',
    reproducibility: '警戒指標：<strong>戦後権力真空×大国陣営化×ティトー型独立変数</strong>。覇権交代期の代理戦争として再現可能。',
  },
  'chinese-civil-war': {
    commonalities: '<code>russian-civil-war</code>パターンのアジア版、<code>second-sino-japanese-war</code>の延長。<code>korean-war</code>・<code>vietnam-war</code>の地政学的前提を形成。',
    universality: '<strong>農民革命</strong>と<strong>包囲戦略</strong>(農村が都市を包囲)。<strong>外国援助逆効果</strong>(米の対国民党援助が腐敗強化)。Barbara Tuchman <em>Stilwell and the American Experience in China</em>は米国の認識誤りを批判。',
    modernLessons: '<strong>米中対立・台湾海峡</strong>の歴史的根源。共産党正統性の核心であり、台湾統一論の感情的駆動力。',
    preventable: 'マーシャル調停(1946)失敗が分岐点。Odd Arne Westadは双方の和解意思欠如を強調。蔣介石の早期改革と国共連立があれば回避可能性あり。',
    reproducibility: '警戒指標：<strong>戦後復興格差×腐敗×イデオロギー動員</strong>。脆弱国家での共産主義以外のイデオロギー版は再発しうる。',
  },
  'malayan-emergency': {
    commonalities: '<code>first-indochina-war</code>と並ぶ脱植民地反共戦争、<code>kenyan-independence-war</code>と類似のCOIN(対反乱)作戦。<code>vietnam-war</code>の対照的成功例。',
    universality: '<strong>対反乱戦の成功条件</strong>(Templer戦略)：民心獲得×情報×政治的解決の組合せ。Robert Thompson <em>Defeating Communist Insurgency</em>はベトナムへの教訓抽出を試みた古典。',
    modernLessons: '対反乱戦理論の参照点として<code>iraq-war</code>のサージ戦略にも影響。<strong>ミャンマー内戦</strong>分析にも応用。',
    preventable: '本ケースは「成功した対反乱戦」として、独立約束の早期提示×民族構成の有利さが鍵だったとされる。',
    reproducibility: '警戒指標：<strong>民族的孤立化×政治解決遅延</strong>。条件次第で抑制可能なモデルケース。',
  },
  'first-arab-israeli-war': {
    commonalities: '<code>six-day-war</code>・<code>yom-kippur-war</code>と続く中東紛争の起点。<code>first-indo-pakistani-war</code>と同年で脱植民地化×宗教分割パターン。',
    universality: '<strong>分割案拒否</strong>と<strong>権力真空</strong>。Benny Morris <em>1948</em>はパレスチナ難民問題形成を詳述。<strong>セキュリティ・ジレンマ</strong>の宗教・民族版。',
    modernLessons: '<strong>ガザ戦争(2023-)</strong>の根本構造形成。「ナクバ」記憶政治化は現代パレスチナ問題の核心。',
    preventable: 'Avi Shlaim <em>Collusion Across the Jordan</em>はヨルダンとイスラエルの暗黙協調を分析。アラブ連盟の戦略的不統一とパレスチナ自決機会逸失が学界での主要論点。',
    reproducibility: '警戒指標：<strong>領土分割案拒否×武装化×大国撤退</strong>。脱植民地化時の領土紛争として高再現性。',
  },
  'suez-crisis': {
    commonalities: '<code>first-arab-israeli-war</code>系譜、<code>six-day-war</code>の前史。<code>algerian-war</code>と並ぶ仏帝国斜陽期紛争。',
    universality: '<strong>覇権交代</strong>の象徴的事件(米国が英仏を抑制)。<strong>共謀</strong>(セーヴル協定)の露見と<strong>大国制約</strong>論の典型。Keith Kyle <em>Suez</em>は詳細に分析。',
    modernLessons: '<strong>米中対立</strong>下での同盟管理問題、ミドルパワーの単独行動限界の教訓。<strong>ロシア・ウクライナ戦争(2022-)</strong>での米欧連携問題に通底。',
    preventable: 'アイゼンハワーの強硬対応で短期収束。事前協議があれば英仏の冒険主義は抑制可能だった。',
    reproducibility: '警戒指標：<strong>衰退覇権の最後の冒険×新興覇権の制約</strong>。ロシアのウクライナ侵攻も類似構図。',
  },
  'cuban-revolution': {
    commonalities: '<code>nicaraguan-revolution</code>・<code>guatemalan-civil-war</code>と並ぶラ米左翼革命パターン。<code>chinese-civil-war</code>のラ米版。',
    universality: '<strong>foco理論</strong>(ゲバラ)実証。<strong>米国裏庭</strong>戦略との衝突。Jorge Domínguez <em>Cuba: Order and Revolution</em>は革命の社会的根拠を分析。',
    modernLessons: '<strong>米中対立</strong>でのラ米影響力争い、ベネズエラ・ニカラグア反米枢軸の歴史的根源。',
    preventable: 'バティスタ独裁の支援継続が米国の戦略的誤りとされる。Hugh Thomasは早期民主化支援があれば穏健化可能だったと示唆。',
    reproducibility: '警戒指標：<strong>独裁腐敗×米国支援固執×ナショナリズム</strong>。ラ米・中東で反復観察可能。',
  },
  'hungarian-uprising': {
    commonalities: '<code>greek-civil-war</code>・<code>cuban-revolution</code>と同時代の冷戦下民衆蜂起。後の「プラハの春」「連帯」運動の先駆。',
    universality: '<strong>制限主権論</strong>(後のブレジネフ・ドクトリン)の先取り。米国の<strong>ロールバック</strong>限界を露呈。<strong>大国勢力圏</strong>論の冷酷な実証。',
    modernLessons: '<strong>ロシア・ウクライナ戦争(2022-)</strong>でのロシアの「勢力圏」主張、<strong>NATO拡大</strong>論争の根本に直結。',
    preventable: 'Charles Gati <em>Failed Illusions</em>は米国のラジオ自由欧州が過剰期待を煽った責任を分析。ナジ政権の中立宣言が決定的引き金。',
    reproducibility: '警戒指標：<strong>権威主義圏内自由化×大国勢力圏論理×第三国煽動</strong>。ロシア周辺で継続的リスク。',
  },
  'algerian-war': {
    commonalities: '<code>first-indochina-war</code>と並ぶ仏脱植民地戦争、<code>kenyan-independence-war</code>と類似の入植者植民地紛争。<code>vietnam-war</code>と類似のCOIN失敗。',
    universality: '<strong>入植者植民地</strong>の構造的矛盾。Alistair Horne <em>A Savage War of Peace</em>は古典。テロと拷問の悪循環、<strong>勝てる戦争を政治的に失う</strong>典型。',
    modernLessons: '<strong>シリア・イラク</strong>でのISIS対応、<strong>イスラエル-パレスチナ</strong>紛争分析の参照点。対反乱戦と政治解決の関係。',
    preventable: 'ドゴール最終的決断は遅きに失した。Raymond Aronは早期独立論者で、1954年初期での独立承認なら流血最小化可能だったと論じた。',
    reproducibility: '警戒指標：<strong>入植者×先住民×宗主国財政負担</strong>。占領長期化のコストは現代でも普遍。',
  },
  'guatemalan-civil-war': {
    commonalities: '<code>cuban-revolution</code>・<code>nicaraguan-revolution</code>・<code>salvadoran-civil-war</code>と並ぶ中米冷戦内戦。<code>colombian-conflict</code>と類似。',
    universality: '<strong>米国介入</strong>(1954アルベンス政権転覆)が長期内戦の起点。<strong>マヤ先住民虐殺</strong>はジェノサイド条約適用ケース。',
    modernLessons: 'ラ米左傾化(ピンクタイド)の歴史的記憶、<strong>米中対立</strong>下のラ米外交の制約要因。',
    preventable: 'Stephen Schlesinger <em>Bitter Fruit</em>はCIA関与を実証。アルベンス改革容認があれば民主的発展可能だった。',
    reproducibility: '警戒指標：<strong>土地改革反対×多国籍企業利害×反共冷戦論理</strong>。資源国家の構造的反復リスク。',
  },
  'salvadoran-civil-war': {
    commonalities: '<code>guatemalan-civil-war</code>・<code>nicaraguan-revolution</code>系譜の中米冷戦内戦、<code>colombian-conflict</code>と類似。',
    universality: '<strong>レーガン・ドクトリン</strong>(反共反乱支援)の典型適用。<strong>低強度紛争</strong>概念の実験場。Tommie Sue Montgomeryは経済格差を主因と分析。',
    modernLessons: '中米難民流出(現在の対米移民問題の根)、<strong>米中対立</strong>下の中米影響力争いの歴史的根源。',
    preventable: 'チャプルテペック和平(1992)成功は冷戦終結効果。早期土地改革があれば内戦化回避可能だった。',
    reproducibility: '警戒指標：<strong>寡頭支配×軍部死の部隊×外国イデオロギー対立</strong>。中米構造問題は現存。',
  },
  'sino-vietnamese-war': {
    commonalities: '<code>vietnam-war</code>後遺症、<code>cambodian-genocide</code>波及。中ソ対立構造下の<code>korean-war</code>逆パターン。',
    universality: '<strong>共産主義一枚岩神話の崩壊</strong>。Mearsheimer的攻撃的リアリズムの実証(イデオロギーより国家利益)。<strong>懲罰的戦争</strong>の失敗例。',
    modernLessons: '<strong>米中対立</strong>下のベトナムの戦略的位置、<strong>南シナ海</strong>紛争の歴史的背景。同盟は固定的でないという教訓。',
    preventable: 'King Chen <em>China\'s War with Vietnam</em>は中国の戦略的誤算を分析。ベトナムのカンボジア侵攻と中越国境問題が連鎖したが、外交解決の余地はあった。',
    reproducibility: '警戒指標：<strong>同盟関係転換×懲罰戦争論理</strong>。アジアでのパワーバランス変動下で反復リスク。',
  },
  'namibian-independence-war': {
    commonalities: '<code>angolan-civil-war</code>と連動、<code>algerian-war</code>系譜の脱植民地戦争。<code>kenyan-independence-war</code>と類似。',
    universality: '<strong>南ア・アパルトヘイト</strong>体制との連動。冷戦終結が解決を加速した代表例。<strong>国連介入</strong>の成功事例(UNTAG)。',
    modernLessons: '<strong>南スーダン</strong>等での国連平和維持の参照点。冷戦後紛争解決モデル。',
    preventable: '冷戦終結による外部支援喪失が決定的。1978年安保理決議435の早期実施があれば短縮可能だった。',
    reproducibility: '警戒指標：<strong>植民地遺産×アパルトヘイト型支配×大国代理</strong>。アフリカで反復可能性。',
  },
  'first-nagorno-karabakh-war': {
    commonalities: '<code>chechen-wars</code>・<code>bosnian-war</code>と並ぶソ連崩壊後民族紛争。<code>nagorno-karabakh-2020</code>に直結。',
    universality: '<strong>ソ連民族政策</strong>の遺産(人為的境界画定)。<strong>権力真空</strong>と民族動員の組合せ。Thomas de Waal <em>Black Garden</em>は古典分析。',
    modernLessons: '<strong>ロシア・ウクライナ戦争(2022-)</strong>のドンバス問題と構造類似。凍結紛争の再燃リスク(2020,2023)実証。',
    preventable: 'ソ連末期の民族政策再考があれば回避可能だったとの見方。アゼルバイジャンの改革遅延も主因。',
    reproducibility: '警戒指標：<strong>多民族帝国崩壊×飛地×大国保証なし</strong>。ポストソビエト空間で継続的リスク。',
  },
  'lebanese-civil-war': {
    commonalities: '<code>syrian-civil-war</code>・<code>iraq-war</code>と並ぶ中東宗派紛争の原型。<code>angolan-civil-war</code>と類似の長期多勢力混戦。',
    universality: '<strong>コンソシエーショナリズム</strong>(宗派配分制)の機能不全。<strong>外国介入飽和</strong>(イスラエル・シリア・PLO・米仏)。Robert Fisk <em>Pity the Nation</em>は現場記録の古典。',
    modernLessons: '<strong>シリア・イラク・イエメン</strong>の宗派紛争分析の原型。ヒズボラ台頭の歴史的背景は現代<strong>イラン-イスラエル</strong>対立の核心。',
    preventable: 'Kamal Salibiは1943国民協約の硬直性を批判。人口動態変化への適応失敗が決定的。',
    reproducibility: '警戒指標：<strong>宗派配分硬直×人口動態変化×外国介入</strong>。中東で反復リスク高。',
  },
  'angolan-civil-war': {
    commonalities: '<code>namibian-independence-war</code>と連動、<code>second-congo-war</code>の前段階。<code>spanish-civil-war</code>型代理戦争。',
    universality: '<strong>キューバ・南ア介入</strong>のアフリカ最大代理戦争。<strong>資源呪い</strong>(石油・ダイヤ)が和平阻害。Patrick Chabal <em>A History of Postcolonial Lusophone Africa</em>分析。',
    modernLessons: '<strong>シリア内戦</strong>等の長期多勢力紛争分析の参照点。<strong>中露アフリカ進出</strong>の歴史的背景。',
    preventable: 'アルヴォル協定(1975)の即時崩壊が原点。三勢力包摂的暫定政府機能化があれば回避可能だった。',
    reproducibility: '警戒指標：<strong>植民地撤退時三つ巴×資源利権×冷戦代理</strong>。アフリカで反復リスク。',
  },
  'peruvian-internal-conflict': {
    commonalities: '<code>colombian-conflict</code>・<code>guatemalan-civil-war</code>と並ぶラ米農民反乱。毛沢東主義系譜は<code>chinese-civil-war</code>の理論輸出。',
    universality: '<strong>千年王国主義革命</strong>(センデロ・ルミノソ)。Steve Stern <em>Shining and Other Paths</em>は社会的根拠分析。アンデス先住民疎外が動員基盤。',
    modernLessons: 'ラ米の構造的不平等問題、極端思想の動員力に関する教訓。<strong>コロンビア</strong>FARCとの比較分析。',
    preventable: 'Cynthia McClintock <em>Revolutionary Movements in Latin America</em>はベラスコ改革挫折を起点と分析。土地改革持続があれば動員基盤縮小可能だった。',
    reproducibility: '警戒指標：<strong>先住民疎外×イデオロギー輸入×国家不在地域</strong>。ラ米構造問題は継続。',
  },
  'iran-iraq-war': {
    commonalities: '<code>gulf-war</code>の前史、<code>russo-japanese-war</code>と類似の地域大国対決。<code>world-war-1</code>型塹壕戦再現。',
    universality: '<strong>革命の輸出</strong>(イラン)への<strong>予防戦争</strong>(イラク)。Efraim Karsh分析。<strong>機会の窓</strong>(イラン革命直後の混乱)誤算。<strong>大国両天秤</strong>(米ソ双方支援)。',
    modernLessons: '<strong>米中対立</strong>下の中東代理戦争パターン、<strong>サウジ-イラン</strong>対立の歴史的根源。',
    preventable: 'Pierre Razouxはサダムの戦略的誤算を中心要因と分析。米国の対イラン中立維持があれば抑止可能だった可能性。',
    reproducibility: '警戒指標：<strong>革命輸出×予防戦争論×大国両建</strong>。中東で構造的リスク継続。',
  },
  'chechen-wars': {
    commonalities: '<code>first-nagorno-karabakh-war</code>系譜のソ連崩壊後紛争、<code>bosnian-war</code>と類似。<code>russian-civil-war</code>と類似の中央集権問題。',
    universality: '<strong>帝国崩壊と分離独立</strong>の典型。<strong>都市戦の蹂躙</strong>(グロズヌイ)。Anatol Lieven <em>Chechnya: Tombstone of Russian Power</em>は第一次戦争の象徴性を分析。',
    modernLessons: '<strong>ロシア・ウクライナ戦争(2022-)</strong>のロシア軍ドクトリンの直接的源流。プーチン政権の権力基盤形成過程。',
    preventable: 'エリツィン政権の初期軍事介入決定が分岐点。連邦制度内自治拡大があれば独立要求緩和可能だった。',
    reproducibility: '警戒指標：<strong>帝国崩壊×中央集権再強化×武力解決優先</strong>。多民族大国で反復リスク。',
  },
  'rwandan-genocide': {
    commonalities: '<code>cambodian-genocide</code>・<code>bosnian-war</code>と並ぶ20世紀末ジェノサイド。<code>biafra-war</code>と類似の植民地民族分断遺産。',
    universality: '<strong>ジェノサイドの先行指標</strong>(Gregory Stanton 8段階モデル実証)。<strong>傍観者問題</strong>(国連・米国の不作為)。Philip Gourevitch古典ルポ。',
    modernLessons: '<strong>R2P原則</strong>の起源、<strong>ミャンマー・スーダン</strong>での国際社会対応の参照点。SNS扇動と虐殺の関係。',
    preventable: 'Romeo Dallaire将軍の警告無視が国際社会の最大失敗。Samantha Powerは政治的意思欠如を主因と分析。早期介入で防止可能だった代表例。',
    reproducibility: '警戒指標：<strong>民族二項対立扇動×ヘイトメディア×武器配布×国際社会傍観</strong>。SNS時代に再発リスクむしろ増大。',
  },
  'kosovo-war': {
    commonalities: '<code>bosnian-war</code>系譜のユーゴ崩壊紛争、<code>rwandan-genocide</code>後の人道介入論。',
    universality: '<strong>人道的介入</strong>の典型。安保理決議なしのNATO空爆は<strong>合法性vs正統性</strong>論争を引き起こした。Tim Judah分析。',
    modernLessons: '<strong>ロシア・ウクライナ戦争(2022-)</strong>でロシアが「コソボ先例」を独立承認の正当化に援用。R2Pの両刃性。',
    preventable: 'ランブイエ会議でのセルビア拒否が直接引き金。Milošević政権への早期外交圧力強化があれば防止可能性。',
    reproducibility: '警戒指標：<strong>多民族国家解体×大国対立×先例の戦略利用</strong>。継続的リスク。',
  },
  'sri-lankan-civil-war': {
    commonalities: '<code>bangladesh-liberation-war</code>と類似の民族独立運動、<code>colombian-conflict</code>と類似のテロ含む長期内戦。',
    universality: '<strong>多数派暴政</strong>(シンハラ仏教ナショナリズム)による少数派疎外。LTTE自爆テロは現代テロリズムの原型。',
    modernLessons: '<strong>ミャンマー・カシミール</strong>での民族紛争分析の参照点。<strong>中印対立</strong>下のスリランカの戦略的位置。',
    preventable: 'バンダラナイケ"Sinhala Only"政策(1956)が起点。連邦制度提案受諾(1957)があれば民族統合可能だった。',
    reproducibility: '警戒指標：<strong>言語・宗教ナショナリズム×憲法的少数派保護欠如</strong>。多民族国家で構造的リスク。',
  },
  'second-congo-war': {
    commonalities: '<code>angolan-civil-war</code>系譜のアフリカ大戦、<code>rwandan-genocide</code>波及。<code>somali-civil-war</code>と類似の国家崩壊。',
    universality: '<strong>アフリカ世界大戦</strong>(9カ国関与)。<strong>資源呪い</strong>(コルタン等)が長期化要因。Jason Stearns <em>Dancing in the Glory of Monsters</em>分析。',
    modernLessons: '<strong>サヘル諸国紛争</strong>分析の参照点、<strong>中露アフリカ進出</strong>の前史。',
    preventable: 'モブツ末期の国家崩壊管理失敗が起点。冷戦後アフリカへの国際関心低下も主因。',
    reproducibility: '警戒指標：<strong>国家崩壊×資源収奪×近隣国介入</strong>。脆弱国家で反復可能。',
  },
  'somali-civil-war': {
    commonalities: '<code>second-congo-war</code>と類似の国家崩壊、<code>lebanese-civil-war</code>と類似の長期混戦。',
    universality: '<strong>失敗国家</strong>概念の原型(Robert Rotberg)。<strong>氏族主義</strong>動員。米軍の介入失敗(モガディシュ)は対反乱戦の限界事例。',
    modernLessons: '<strong>アフリカの角海賊問題</strong>、<strong>アル・シャバブ</strong>テロの根源。<strong>イエメン内戦</strong>と類似の地域不安定化。',
    preventable: 'バーレ政権崩壊管理失敗が起点。冷戦終結後のソマリア戦略的価値低下も主因。',
    reproducibility: '警戒指標：<strong>冷戦後支援打切×氏族動員×武器流入</strong>。失敗国家化リスクは現存。',
  },
  'algerian-civil-war': {
    commonalities: '<code>algerian-war</code>独立後の内戦、<code>iranian-revolution</code>と並ぶイスラム主義台頭。<code>syrian-civil-war</code>の前史。',
    universality: '<strong>選挙の罠</strong>(1991FIS勝利→軍部停止)。<strong>民主主義パラドックス</strong>(反民主勢力の選挙勝利問題)実証。',
    modernLessons: '<strong>アラブの春</strong>後の<strong>エジプト・シリア</strong>展開分析の参照点。民主化と安定の緊張関係。',
    preventable: 'Hugh Robertsは軍部選挙無効化が長期内戦化の決定的要因と分析。漸進的民主化選択肢があった。',
    reproducibility: '警戒指標：<strong>急進イスラム主義選挙勝利×軍部介入</strong>。中東で反復リスク。',
  },
  'bosnian-war': {
    commonalities: '<code>kosovo-war</code>と並ぶユーゴ崩壊紛争、<code>rwandan-genocide</code>と並ぶ民族浄化。<code>balkan-wars</code>系譜のバルカン民族紛争。',
    universality: '<strong>民族浄化</strong>概念の確立。<strong>セキュリティ・ジレンマ</strong>(Barry Posen "The Security Dilemma and Ethnic Conflict")の典型適用。スレブレニツァは国連保護地域での虐殺。',
    modernLessons: '<strong>ウクライナ・シリア</strong>紛争での民族浄化分析の参照点。NATO役割転換の起点。',
    preventable: 'David Owenらの分割案早期受諾があれば限定可能だった。Richard Holbrooke <em>To End a War</em>はデイトン合意までの遅延を批判。',
    reproducibility: '警戒指標：<strong>多民族連邦解体×民族別領土主張×外部承認競争</strong>。継続的リスク。',
  },
  'balkan-wars': {
    commonalities: '<code>world-war-1</code>の直接的前段階、<code>bosnian-war</code>と地理的・民族的に連続。<code>russo-turkish-war-1877</code>系譜のオスマン解体。',
    universality: '<strong>東方問題</strong>の最終局面、<strong>同盟連鎖</strong>のリハーサル。バルカン同盟の対オスマン勝利→分配紛争(第二次)は連合分裂典型。',
    modernLessons: 'バルカンは現在も<strong>EU拡大</strong>の課題地域。<strong>ロシア・ウクライナ戦争(2022-)</strong>でセルビア・スレタなど東方影響力。',
    preventable: '大国協調(列強会議)の機能不全が拡大の主因。早期国境画定があれば二次戦争回避可能だった。',
    reproducibility: '警戒指標：<strong>衰退帝国×民族解放×戦勝国分配争い</strong>。帝国解体時に反復リスク。',
  },
  'irish-independence-war': {
    commonalities: '<code>indian-rebellion</code>系譜の英帝国分離運動、<code>algerian-war</code>と類似の入植者植民地問題。',
    universality: '<strong>非対称ゲリラ戦</strong>(IRAコリンズ式)の原型。<strong>分割の遺産</strong>(北アイルランド問題)は<code>first-indo-pakistani-war</code>と類似。',
    modernLessons: '<strong>テロ対反乱戦</strong>研究の古典、<strong>カシミール・パレスチナ</strong>分析の参照点。Brexit後の北アイルランド問題は継続。',
    preventable: '1914自治法施行があれば分離独立回避可能だった。WWIによる延期と1916イースター蜂起への対応硬直化が決定的。',
    reproducibility: '警戒指標：<strong>植民地宗教民族分断×自治約束反故×武装化</strong>。脱植民地化遺産として現存。',
  },
  'mexican-revolution': {
    commonalities: '<code>cuban-revolution</code>に先行するラ米農民革命、<code>russian-revolution</code>と同時代の体制変革。',
    universality: '<strong>長期独裁の崩壊</strong>(Díaz体制34年)後の権力闘争。Alan Knight <em>The Mexican Revolution</em>は社会革命としての性格を分析。米国介入(ヴェラクルス)も含む。',
    modernLessons: 'ラ米ポピュリズム(AMLOら)の歴史的根拠、<strong>米国-ラ米関係</strong>の構造的緊張根源。',
    preventable: 'Díaz末期の漸進改革(マデロ受入)があれば回避可能だった。長期独裁の出口戦略欠如が主因。',
    reproducibility: '警戒指標：<strong>長期独裁×経済発展×権力継承不在</strong>。権威主義体制の終焉リスクとして普遍。',
  },
  'russian-revolution': {
    commonalities: '<code>russian-civil-war</code>の起点、<code>chinese-civil-war</code>のモデル、<code>mexican-revolution</code>と同時代。<code>world-war-1</code>敗戦の直接的帰結。',
    universality: '<strong>戦争による革命</strong>(Skocpol)。Lenin型前衛党理論実証。<strong>権力真空</strong>を組織化された少数派が掌握する古典例。',
    modernLessons: '<strong>ロシア・ウクライナ戦争(2022-)</strong>での体制動揺リスク分析の歴史的参照点。',
    preventable: 'ケレンスキーの戦争継続選択が決定的。早期講和(独墺と)があれば臨時政府維持可能だった。Pipes vs Fitzpatrick論争。',
    reproducibility: '警戒指標：<strong>戦争疲弊×食糧危機×軍隊崩壊×組織化前衛</strong>。条件次第で再現可能。',
  },
  'second-italo-ethiopian-war': {
    commonalities: '<code>spanish-civil-war</code>と並ぶ国際連盟機能不全事例、<code>world-war-2-europe</code>の前奏曲。',
    universality: '<strong>集団安全保障の失敗</strong>典型。経済制裁の不徹底が修正主義国家を勢いづけた。<strong>バック・パッシング</strong>の前駆形態。',
    modernLessons: '<strong>ロシア・ウクライナ戦争(2022-)</strong>での制裁実効性問題、<strong>国連安保理</strong>機能不全分析の根源。',
    preventable: 'スエズ運河閉鎖と石油禁輸の徹底があればイタリア経済を屈服させられたが、英仏の宥和姿勢で失敗。',
    reproducibility: '警戒指標：<strong>制裁の抜け穴×大国宥和×修正主義国家</strong>。現代制裁政治で継続。',
  },
  'winter-war': {
    commonalities: '<code>world-war-2-europe</code>の一部、<code>russo-japanese-war</code>と類似の小国対大国善戦例。',
    universality: '<strong>士気と地形</strong>が量的優位を相殺する事例。スターリンの<strong>機会の窓</strong>誤算(独ソ不可侵条約期)。Trotter <em>A Frozen Hell</em>分析。',
    modernLessons: '<strong>ロシア・ウクライナ戦争(2022-)</strong>緒戦の露軍苦戦と直接類比される。小国の防衛意志過小評価パターン。',
    preventable: 'ソ連の領土要求が過大でなければスウェーデン的中立保持可能だった。',
    reproducibility: '警戒指標：<strong>大国の小国国境要求×独裁者の過信×情報軽視</strong>。継続的リスク。',
  },
  'falklands-war': {
    commonalities: '<code>gulf-war</code>と並ぶ「明確な侵略」事例、<code>russo-japanese-war</code>と類似の遠征戦争。',
    universality: '<strong>転換戦争</strong>(diversionary war)理論の典型。アルゼンチン軍政の国内危機転嫁誤算。Lawrence Freedman <em>Signals of War</em>はシグナル誤読を分析。',
    modernLessons: '<strong>ロシア・ウクライナ戦争(2022-)</strong>でプーチン政権の国内危機転嫁要素分析の参照点。',
    preventable: '英国の防衛コミットメント明示(Endurance号撤退見直し等)があれば抑止可能だった。シグナル管理失敗の典型。',
    reproducibility: '警戒指標：<strong>独裁国内危機×領土回復主義×大国コミットメント曖昧</strong>。継続的リスク。',
  },
  'cambodian-genocide': {
    commonalities: '<code>vietnam-war</code>波及、<code>rwandan-genocide</code>と並ぶ20世紀ジェノサイド。<code>russian-revolution</code>の極端化型。',
    universality: '<strong>イデオロギー的純化</strong>の極限。Ben Kiernan <em>The Pol Pot Regime</em>古典分析。<strong>都市追放</strong>と農村ユートピア論の破滅的実装。',
    modernLessons: '<strong>R2P原則</strong>の起源的事例、<strong>ミャンマー</strong>等の現代ジェノサイド分析の参照点。',
    preventable: '米国のカンボジア秘密爆撃が極端化を加速したとSidney Schanbergら指摘。米中ベトナム介入の連鎖破断あれば防止可能性。',
    reproducibility: '警戒指標：<strong>戦争での社会破壊×純化イデオロギー×知識人粛清</strong>。極端思想政権で再発リスク。',
  },
  'biafra-war': {
    commonalities: '<code>bangladesh-liberation-war</code>と類似の分離独立、<code>rwandan-genocide</code>と類似の民族紛争。',
    universality: '<strong>植民地境界線の人為性</strong>(ベルリン会議遺産)。<strong>飢餓兵器化</strong>と人道的介入論の起源。',
    modernLessons: '<strong>南スーダン</strong>分離独立、<strong>カタルーニャ</strong>等分離主義分析の参照点。アフリカ国境問題は現存。',
    preventable: 'ナイジェリア連邦制度の早期再編があれば回避可能だったとの議論。',
    reproducibility: '警戒指標：<strong>植民地境界×多民族×資源偏在</strong>。アフリカで反復リスク。',
  },
  'iranian-revolution': {
    commonalities: '<code>cuban-revolution</code>と類似の親米独裁転覆、<code>algerian-civil-war</code>と並ぶイスラム主義台頭の起点。',
    universality: '<strong>近代化の逆説</strong>(Theda Skocpol "Rentier State and Shi\'a Islam")。石油収入×伝統社会動揺×宗教動員の合流。',
    modernLessons: '<strong>米イラン対立</strong>の起源、<strong>サウジ-イラン</strong>対立、<strong>ヒズボラ・ハマス</strong>支援の歴史的根源。',
    preventable: 'シャー体制末期の改革遅延が主因。米国のシャー支援硬直化も寄与。Gary Sickは政策ジレンマを分析。',
    reproducibility: '警戒指標：<strong>近代化×宗教反動×外国支援独裁者</strong>。中東で構造的リスク。',
  },
  'east-timor-occupation': {
    commonalities: '<code>algerian-war</code>と類似の脱植民地占領、<code>bangladesh-liberation-war</code>と類似の独立運動。',
    universality: '<strong>冷戦下の人権無視</strong>(米豪のスハルト容認)。<strong>R2P</strong>原則確立の重要事例。',
    modernLessons: '<strong>パプア</strong>問題、<strong>ミャンマー</strong>少数民族問題の参照点。',
    preventable: '1975ポルトガル撤退時の国連管理移行があれば占領回避可能だった。',
    reproducibility: '警戒指標：<strong>脱植民地化空白×近隣大国併合×冷戦論理</strong>。継続的リスク。',
  },
  'nicaraguan-revolution': {
    commonalities: '<code>cuban-revolution</code>系譜のラ米左翼革命、<code>guatemalan-civil-war</code>・<code>salvadoran-civil-war</code>と同時代中米紛争。',
    universality: '<strong>長期独裁(ソモサ家43年)崩壊</strong>後の冷戦化。コントラ戦争は<strong>レーガン・ドクトリン</strong>典型適用。',
    modernLessons: '<strong>米中ラ米影響力争い</strong>の歴史的根源、現代オルテガ政権の権威主義化分析。',
    preventable: '米国の早期サンディニスタ受容があれば穏健化可能だった。カーター政権末期判断が分岐点。',
    reproducibility: '警戒指標：<strong>米国支援独裁崩壊×左翼受皿×冷戦再陣営化</strong>。ラ米で反復リスク。',
  },
  'colombian-conflict': {
    commonalities: '<code>peruvian-internal-conflict</code>・<code>guatemalan-civil-war</code>と並ぶラ米長期内戦、<code>sri-lankan-civil-war</code>と類似の長期化。',
    universality: '<strong>麻薬経済</strong>と<strong>反乱経済</strong>の融合。FARCの50年以上の生存は<strong>領土支配型反乱</strong>の典型。',
    modernLessons: '<strong>メキシコ麻薬戦争</strong>等の参照点。2016和平合意は長期内戦終結モデル。',
    preventable: '1948ボゴタソ後の国民戦線体制の包摂性欠如が起点。土地改革持続があれば動員基盤縮小可能。',
    reproducibility: '警戒指標：<strong>土地不平等×麻薬経済×国家不在地域</strong>。ラ米で構造的リスク。',
  },
  'soviet-afghan-war': {
    commonalities: '<code>vietnam-war</code>と並ぶ大国介入失敗、<code>afghanistan-war</code>(米)の前史。<code>iran-iraq-war</code>と同時代中央アジア紛争。',
    universality: '<strong>帝国の墓場</strong>パターン。<strong>逆ドミノ</strong>(米のムジャヒディン支援が後のアル・カーイダを生む)。Steve Coll <em>Ghost Wars</em>古典。',
    modernLessons: '<strong>米中対立</strong>下のアフガン情勢、<strong>テロリズム逆流</strong>分析の核心。<strong>ロシア・ウクライナ戦争(2022-)</strong>のロシア軍ドクトリンへの影響。',
    preventable: 'ブレジネフの介入決定が分岐点。アミン政権粛清放置あれば泥沼化回避可能だった。',
    reproducibility: '警戒指標：<strong>近隣不安定政権×イデオロギー使命×ゲリラ地形</strong>。継続的リスク。',
  },
  'philippine-american-war': {
    commonalities: '<code>spanish-american-war</code>の直接帰結、<code>vietnam-war</code>と類似の対反乱戦先駆。<code>cuban-revolution</code>と類似の米国裏庭問題。',
    universality: '<strong>解放者から占領者へ</strong>のパラドックス。Stanley Karnow <em>In Our Image</em>は米帝国主義の自己欺瞞を分析。',
    modernLessons: '<strong>米中対立</strong>下のフィリピンの戦略的位置、<strong>南シナ海</strong>での米同盟の歴史的根源。',
    preventable: 'マッキンリー政権の独立承認(アギナルド政権容認)があれば回避可能だった。',
    reproducibility: '警戒指標：<strong>解放戦争後の占領×現地統治計画欠如</strong>。<code>iraq-war</code>等で反復観察。',
  },
  'burmese-independence-war': {
    commonalities: '<code>indian-rebellion</code>系譜の英帝国分離、<code>malayan-emergency</code>と類似の脱植民地化期紛争。',
    universality: '<strong>多民族国家形成困難</strong>。アウンサン暗殺で統合機運喪失、現代<strong>ミャンマー内戦</strong>に直結する民族問題の起源。',
    modernLessons: '<strong>ミャンマー内戦(2021-)</strong>の歴史的根源、ロヒンギャ問題の構造的背景。',
    preventable: 'パンロン会議精神の継続があれば連邦的統合可能だった。アウンサン暗殺(1947)が決定的。',
    reproducibility: '警戒指標：<strong>多民族独立国家×統合者暗殺×軍部台頭</strong>。脱植民地化遺産。',
  },
  'kenyan-independence-war': {
    commonalities: '<code>algerian-war</code>と類似の入植者植民地戦争、<code>malayan-emergency</code>と並ぶ英COIN作戦。',
    universality: '<strong>マウマウの神話化</strong>と<strong>キクユ収容所</strong>(David Anderson <em>Histories of the Hanged</em>)。<strong>正史と修正史</strong>の論争事例。',
    modernLessons: 'ケニア最近の英国補償判決(2013)は<strong>植民地責任問題</strong>の現代化、世界各地の歴史補償論議に影響。',
    preventable: '土地改革と政治参加拡大の早期実施があれば武装化回避可能だった。',
    reproducibility: '警戒指標：<strong>入植者土地独占×先住民政治排除</strong>。脱植民地化遺産として現存。',
  },
  'ethiopian-civil-war': {
    commonalities: '<code>second-italo-ethiopian-war</code>後の体制問題、<code>somali-civil-war</code>と並ぶアフリカの角紛争。<code>angolan-civil-war</code>と類似の冷戦代理戦争。',
    universality: '<strong>皇帝制崩壊</strong>と<strong>マルクス主義軍政</strong>(デルグ)の暴走。エリトリア独立運動との連動は<strong>biafra-war</strong>と類似。',
    modernLessons: '<strong>ティグライ戦争(2020-)</strong>の歴史的根源、<strong>アフリカの角</strong>地政学の核心。',
    preventable: 'ハイレ・セラシエ末期の改革加速があれば革命回避可能だったとの議論。1973年飢饉対応失敗が決定打。',
    reproducibility: '警戒指標：<strong>長期皇帝制×飢饉×軍部マルクス主義化</strong>。アフリカで構造的リスク。',
  },
};
