import { LessonsData } from './types';

/** 現代（2000-）戦争の教訓データ */
export const LESSONS_CONTEMPORARY: Record<string, LessonsData> = {
  'afghanistan-war': {
    commonalities: 'ベトナム戦争・ソ連アフガン戦争と同型。<strong>外部大国による国家建設の失敗</strong>—現地の部族構造・腐敗政権・聖域（パキスタン）を放置し、20年で1兆ドル以上を投じて崩壊。',
    universality: '<strong>非対称戦争の構造的非対称性</strong>—占領側は「勝ち続けねば負け」、ゲリラ側は「負けなければ勝ち」（Henry Kissinger）。Fearonの私的情報モデルでは、現地勢力は時間選好で外部撤退を待つ合理的均衡。',
    modernLessons: '<strong>軍事力では国家は建設できない</strong>。腐敗した代理政権・聖域・正統性欠如の三点が揃えば、いかなる装備・予算でも崩壊する。<br/>外部介入の出口戦略を入口で設計せよ。',
    preventable: '2001年の対テロ報復は防げなかった可能性が高い。だが<strong>2003年以降の国家建設へのミッション拡張は回避可能</strong>—トラボラ後に撤退していれば泥沼化を防げたとの見方が主流（RAND研究）。',
    reproducibility: '<strong>極めて高い</strong>。サヘル・イエメン・シリアで同型反復中。「外部軍事力＋腐敗代理政権＋聖域」の三点セットは現代非対称戦の基本パターン。',
  },
  'iraq-war': {
    commonalities: '<strong>大量破壊兵器という誤情報・誤認知に基づく予防戦争</strong>。スエズ危機・ベトナム介入と同様、情報過信と確証バイアスが戦略判断を歪めた古典例。',
    universality: 'Jervis<strong>「Perception and Misperception」</strong>—指導者は既存信念に合致する情報を過大評価する。ラムズフェルド/チェイニーのイラク=核脅威認知は事前に固定され、CIAの慎重な評価は無視された。',
    modernLessons: '<strong>情報戦・プロパガンダの自爆効果</strong>。誤った正当化で開戦すれば、事後の正統性は崩壊し同盟（仏独）も離反する。<br/>占領計画の不在＋脱バース党化＋軍解体がISIS誕生の温床に。',
    preventable: '<strong>完全に防止可能だった</strong>。査察継続と外交圧力で抑止できたとの史家コンセンサス。チェイニー副大統領を中心とする政治意思が情報を選択した政治戦争。',
    reproducibility: '<strong>高い</strong>。「敵の意図を最悪に解釈し予防攻撃」のロジックは台湾海峡・対イラン・対北朝鮮で再現可能。情報機関の独立性・議会の検証機能の有無が分岐点。',
  },
  'libyan-civil-war': {
    commonalities: 'チュニジア・エジプト「アラブの春」連鎖の一環。<strong>NATO介入による独裁打倒→権力真空→無政府化</strong>はイラク・アフガンと完全同型。',
    universality: '<strong>権力真空理論</strong>—独裁政権は社会の自己組織化を破壊するため、急激な崩壊は内戦化する（Charles Tilly）。安保理決議1973の「文民保護」が体制転覆に転用された前例として、ロシア・中国の不信を決定的に深めた。',
    modernLessons: '<strong>R2P（保護する責任）の濫用は次の介入を不可能にする</strong>。シリア介入が安保理で阻止された直接原因。<br/>独裁打倒には事後計画が必須—リビアは無計画の象徴。',
    preventable: '内戦化は防止困難だが、<strong>NATOの体制転覆への踏み込みは選択肢があった</strong>。ベンガジ防衛のみに留めれば、ロシア中国との信頼関係を維持できた可能性。',
    reproducibility: '<strong>非常に高い</strong>。「人道介入→政権崩壊→無政府」モデルはサヘル全域に拡散中。リビアの武器庫流出がマリ・ボコハラム強化の物的基盤に。',
  },
  'syrian-civil-war': {
    commonalities: 'レバノン内戦・ボスニア戦争と同型の<strong>多宗派モザイク社会の崩壊＋外部代理戦争</strong>。アサド少数派（アラウィー派）支配構造はサダムのスンニ少数派支配と相似。',
    universality: '<strong>代理戦争の永続化メカニズム</strong>—Fearonの「commitment problem」（信頼できる撤退合意の不可能性）。ロシア・イラン・トルコ・米・湾岸諸国が並行支援するため、内的均衡では終結しない。',
    modernLessons: '<strong>「レッドライン」を引いて守らねば信頼は崩壊する</strong>（オバマ化学兵器対応）。<br/>反体制派支援の選別失敗→IS誕生。情報戦・サイバー戦・難民武器化（欧州への圧力）の総合戦の原型。',
    preventable: '初期段階（2011-12）の限定介入or対露交渉で抑制可能だった可能性。<strong>2013年化学兵器ライン後の不行動が決定的転換点</strong>とする見解が有力。',
    reproducibility: '<strong>高い</strong>。多宗派国家＋強権独裁＋外部代理勢力の組み合わせはイラク・イエメン・レバノンで反復。難民の地政学的武器化はベラルーシ国境・トルコでも再現中。',
  },
  'ukraine-war': {
    commonalities: '<strong>クリミア戦争・第一次大戦の再来構造</strong>—大国の勢力圏争い・バッファゾーン論・帝国回復ナラティブ。プーチンの「歴史的ロシア」観はカイザーの汎ゲルマン主義と相似。',
    universality: '<strong>安全保障ジレンマ＋帝国衰退の合流</strong>。NATO東方拡大とロシア帝国意識の相互恐怖（Mearsheimer vs McFaul論争）。Fearon型の私的情報—プーチンはウクライナの抵抗意志と西側団結を過小評価（誤算）。',
    modernLessons: '<strong>核兵器は地域戦を抑止しない</strong>—核保有国でも通常戦争の閾値は超える。<br/>経済制裁の限界と効果の二面性。情報戦・サイバー戦・ドローン戦の標準化。<br/>同盟の信頼性（Article 5）が抑止の基盤であることの再確認。',
    preventable: '議論あり。<strong>NATO拡大の慎重化・ミンスク合意履行・1994ブダペスト覚書の安全保障強化</strong>のいずれかで回避可能だったとの見解（Mearsheimer/Walt）。逆に「プーチンの帝国意思は不可避」論（Snyder/Applebaum）も有力。',
    reproducibility: '<strong>極めて高い</strong>。台湾海峡（中国の歴史回復ナラティブ）・コーカサス・中央アジアで同型リスク。「核保有国による隣国侵攻」前例化が最大の構造リスク。',
  },
  'gaza-war': {
    commonalities: '第一次〜四次中東戦争・第二次インティファーダの累積。<strong>未解決の領土・難民・主権問題が周期的爆発</strong>するパターン。10.7はヨム・キプール（1973）的奇襲構造。',
    universality: '<strong>非対称戦争＋宗教ナラティブ＋既存秩序破綻</strong>。Fearon型の<strong>commitment problem</strong>（双方とも合意を信頼できない）。指導者個人要因（ネタニヤフ司法改革で支持基盤動揺＋ハマス指導部のイラン軸接続）。',
    modernLessons: '<strong>占領の長期化は必ず爆発する</strong>。アブラハム合意で「パレスチナ問題棚上げ」を試みた地政学が破綻。<br/>市民被害の情報拡散（SNS）が国際正統性を決定する時代—軍事勝利と政治敗北の乖離。',
    preventable: '10.7の奇襲は情報失敗で防止可能だった可能性大（イスラエル安全保障局の警告無視）。<strong>長期構造としては二国家解決の停滞が爆発の温床</strong>。',
    reproducibility: '<strong>確実に再発</strong>。占領＋封鎖＋宗教ナラティブ＋外部支援の構造は不変。レバノン・シリア・イエメン・イランの「抵抗の枢軸」化で地域大戦リスク継続。',
  },
  'yemen-civil-war': {
    commonalities: 'シリア内戦と同型の<strong>サウジvsイラン代理戦争</strong>。レバノン内戦同様、宗派（フーシ＝ザイド派シーア）と地域・部族が複層化。',
    universality: '<strong>代理戦争＋飢餓武器化＋人道危機の永続化</strong>。サウジ封鎖政策で世界最悪の人道危機（UN認定）。シーレーン（バーブ・エル・マンデブ）支配が紅海危機・グローバル海運に直結。',
    modernLessons: '<strong>地域代理戦争のグローバル波及</strong>—フーシ紅海攻撃で世界貿易が混乱。<br/>武器輸出（米英→サウジ）の倫理問題。子ども兵士・飢餓死者の不可視化。',
    preventable: '2015年サウジ介入を回避できれば長期化阻止可能だった。<strong>サレハ統治期（〜2011）の権力分有失敗が遠因</strong>。',
    reproducibility: '<strong>高い</strong>。「弱小国＋宗派分断＋シーレーン＋大国代理」モデルはホルムズ・バーブエルマンデブ・マラッカで反復可能。',
  },
  'sudan-civil-war-2023': {
    commonalities: 'ダルフール紛争（2003-）・南スーダン分離（2011）の延長。<strong>軍2派閥（SAF vs RSF）の権力闘争＋国際代理</strong>はリビア・イエメンと同型。',
    universality: '<strong>権力分有合意の崩壊メカニズム</strong>—バシール後の文民移行プロセスで2軍が同盟→分裂。Fearon型のpower-sharing instability（軍指導者は自軍弱体化を恐れ統合に応じない）。',
    modernLessons: '<strong>クーデター後の文民移行は最も脆弱</strong>。RSF（ワグネル接続）vs SAF（エジプト・サウジ寄り）でグローバル代理化。<br/>UAE金取引・ロシア紅海港・中国油田のmineral war構造。',
    preventable: '2021年クーデター時に国際社会が強硬対応すれば抑制可能だったとの見解。<strong>RSFをバシール期に解体しなかったのが構造的失敗</strong>。',
    reproducibility: '<strong>非常に高い</strong>。アフリカで「並行軍隊（パラレルアーミー）」を抱える国は多数（リビア・チャド・CAR等）。鉱物資源＋ワグネル型民間軍事会社が触媒。',
  },
  'mali-conflict': {
    commonalities: 'リビア武器流出を直接的引き金とする<strong>サヘル危機</strong>。アフガン・イラク同様、外部軍（仏セルバル/バルカン）撤退後にジハーディスト復活。',
    universality: '<strong>気候変動＋人口圧＋国家失敗の三重苦</strong>。サヘル干ばつで遊牧民・農民紛争が激化、ジハーディストが調停者として勢力拡大。Robert Kaplanの「The Coming Anarchy」型崩壊。',
    modernLessons: '<strong>仏のアフリカ撤退とロシア（ワグネル）進出の地政学交代</strong>。<br/>連続クーデター（2020/21）で民主化逆行。<br/>外部軍事プレゼンスのみでは国家建設不可—アフガンと同じ教訓の反復。',
    preventable: 'リビア介入時の武器拡散管理で被害軽減可能だった。<strong>2012年トゥアレグ蜂起時の早期政治解決</strong>が分岐点。',
    reproducibility: '<strong>進行中で拡大</strong>。ブルキナファソ・ニジェール・チャドへ波及。気候変動の進行で構造的に悪化—世界の「次の戦争前線」。',
  },
  'boko-haram-insurgency': {
    commonalities: 'マリ・ソマリア・サヘル全域のジハーディスト網と接続。<strong>植民地由来の人為的国境＋宗教断層＋政府不在</strong>はナイジェリア北部の構造的特徴。',
    universality: '<strong>地方統治の失敗＋若年人口爆発＋宗教動員</strong>。北部ナイジェリアの貧困・教育不足・腐敗が温床。「西洋教育は罪」というイデオロギーは植民地的近代化への反動。',
    modernLessons: '<strong>軍事討伐のみでは過激主義は消えない</strong>—貧困・教育・統治の三本柱の不可欠性。<br/>女子生徒誘拐（チボク2014）のグローバル拡散はSNS時代の象徴。<br/>多国籍合同軍（MNJTF）モデルの限界。',
    preventable: '初期（2002-09）の警察対応失敗が決定的。<strong>ユスフ処刑（2009）でシェカウ過激化を招いた治安失策</strong>。',
    reproducibility: '<strong>高い</strong>。チャド湖周辺の同型条件（気候・人口・宗教）が揃う。ISWAPへの分裂で内部競争激化。アフリカ全域で類似運動が反復中。',
  },
  'nagorno-karabakh-2020': {
    commonalities: '第一次ナゴルノ・カラバフ戦争（1988-94）の構造的続編。<strong>ソ連崩壊の凍結紛争</strong>がドローン技術革新で解凍された事例。',
    universality: '<strong>軍事技術の非対称ブレイクスルー</strong>—トルコ製バイラクタルTB2が古典的塹壕戦を無効化。Stephen Biddleの「Modern System」理論—装備差より運用差が勝敗を決める好例。',
    modernLessons: '<strong>ドローン時代の戦争形態の象徴</strong>。<br/>ロシアの後退とトルコの中央アジア進出—地域秩序再編。<br/>停戦監視のロシア依存→2023年アルメニア人追放（民族浄化）で完結。',
    preventable: 'ミンスク・グループ（OSCE）の調停失敗が遠因。<strong>1994停戦後の30年で双方とも譲歩しなかった</strong>制度的失敗。',
    reproducibility: '<strong>非常に高い</strong>。旧ソ連凍結紛争（沿ドニエストル・南オセチア・アブハジア）はすべて同型リスク。ドローン技術拡散で攻撃側優位の時代に。',
  },
  'myanmar-civil-war': {
    commonalities: 'カチン・カレン少数民族紛争（1948〜）の延長＋2021クーデター。<strong>軍政vs民主派＋多民族抵抗</strong>はシリア・スーダンと同型。',
    universality: '<strong>軍事政権の自己保存ロジック</strong>—Aung San Suu Kyi政権下で軍特権が侵食される恐怖が2021クーデターの動機。Fearon型のcommitment problem（軍は権力放棄後の安全を信頼できない）。',
    modernLessons: '<strong>民主化過程の脆弱性</strong>—軍特権温存の経過措置（2008憲法）が裏目。<br/>3DPプリンタ製武器・暗号通信のPDF（人民防衛軍）が新時代の抵抗運動。<br/>中露支援で国際制裁が無効化。',
    preventable: '2008憲法での軍特権温存が構造的欠陥。<strong>NLD政権下での軍縮交渉失敗</strong>が分岐点。',
    reproducibility: '<strong>高い</strong>。タイ・パキスタン・エジプトで軍政復活パターンは反復。「ハイブリッド民主主義」の脆弱性を示す典型例。',
  },
  'tigray-war': {
    commonalities: '<strong>連邦制崩壊＋民族浄化</strong>。エリトリアとの旧因縁＋アビィ首相の中央集権化が衝突。ボスニア・ルワンダと類似の民族紛争構造。',
    universality: '<strong>民主化指導者の戦争転換</strong>—アビィはノーベル平和賞（2019）受賞直後に開戦。Daron Acemogluの「narrow corridor」逸脱例。包囲・飢餓・性暴力は古典的民族浄化手段。',
    modernLessons: '<strong>平和賞受賞者でも戦争を起こす</strong>—個人の善意は構造に従属。<br/>連邦制（民族連邦主義）の脆弱性。<br/>国際社会の関心薄（コロナ・ウクライナと並行）が暴虐を許した情報暗黒化。',
    preventable: '2018年TPLF（ティグレ人民解放戦線）排除時の対話失敗が遠因。<strong>連邦再編の段階的実施</strong>で回避可能だった可能性。',
    reproducibility: '<strong>高い</strong>。アフリカ多民族国家（ナイジェリア・ケニア・南アフリカ等）で同型リスク。気候・資源圧で連邦制への遠心力が強まる。',
  },
  'south-sudan-civil-war': {
    commonalities: '独立（2011）後わずか2年で内戦化。<strong>解放運動の権力闘争転化</strong>はジンバブエ・エリトリアと同型。',
    universality: '<strong>独立後の制度欠陥</strong>—解放運動が国家建設能力を持たず、民族連合（ディンカvsヌエル）が分裂。石油収入の独占がレント国家化を加速。',
    modernLessons: '<strong>独立は終点ではなく始点</strong>。米国の独立支援（南北対立緩和）後の国家建設失敗。<br/>子ども兵士・性暴力・飢餓の人道危機。<br/>UNMISSの限界—平和維持はあるが平和構築は不可。',
    preventable: '2013年キール・マチャール対立時の早期調停で抑制可能。<strong>解放運動を制度に置換する移行期間設計の失敗</strong>。',
    reproducibility: '<strong>高い</strong>。新興独立国（コソボ・東ティモール等）で類似リスク。資源国家＋民族多元＋制度未熟の三点が条件。',
  },
  'central-african-civil-war': {
    commonalities: '<strong>セレカ（ムスリム）vsアンチ・バラカ（キリスト教）</strong>—宗教対立装いの権力闘争。スーダン・ナイジェリア・南スーダンとアフリカ大陸断層に位置。',
    universality: '<strong>失敗国家の連鎖</strong>—中央政府の不在＋鉱物資源（ダイヤ・金）＋外部軍事会社（ワグネル）。Paul Collierの「resource curse」典型。',
    modernLessons: '<strong>ロシアのアフリカ進出の橋頭堡</strong>—ワグネル金鉱権益と引き換えの政権防衛。<br/>仏軍撤退とロシア進出の交代。<br/>国際社会の関心ゼロが暴虐を許す。',
    preventable: '2003年ボジゼ・クーデター時の対応失敗が遠因。<strong>連続クーデター文化の制度化</strong>を断ち切る機会喪失。',
    reproducibility: '<strong>確実</strong>。サヘル＋中部アフリカで同型条件が広がる。ワグネル型民間軍事会社の現地化で構造的悪化。',
  },
};
