import { War } from './types';

/** 古代戦争（追加分） */
export const WARS_ANCIENT_EXTRA: War[] = [
  {
    id: 'han-xiongnu-wars',
    year: -133, endYear: 89,
    name: '漢匈奴戦争',
    region: 1, type: 'war', era: 'ancient',
    theater: '中国北辺・モンゴル高原・西域',
    mapHighlight: 'asia',
    markers: [
      { coordinates: [108.9398, 34.3416], label: '長安（前漢都）', isMain: true, ally: true },
      { coordinates: [112.4540, 34.6197], label: '洛陽（後漢都）', isMain: true, ally: true },
      { coordinates: [112.4334, 40.8424], label: '馬邑（紀元前133年・誘引作戦）', isMain: true },
      { coordinates: [106.0000, 44.0000], label: '漠北の戦い（紀元前119年・衛青・霍去病）', isMain: true },
      { coordinates: [91.1322, 47.8864], label: '稽落山・燕然山（89年・北匈奴撃破）', isMain: true, enemy: true },
      { coordinates: [94.6624, 40.1421], label: '敦煌（西域経営の前線）' },
    ],
    weight: 3,
    tags: ['資源争奪', '帝国衰退', '安全保障ジレンマ', '遊牧vs農耕'],
    ideologies: ['漢儒教秩序', '匈奴遊牧国家'],
    causes: ['chu-han-contention'],
    influences: ['three-kingdoms-china', 'migration-period-wars'],
  },
  {
    id: 'gallic-wars-caesar',
    year: -58, endYear: -50,
    name: 'ガリア戦争',
    region: 0, type: 'war', era: 'ancient',
    theater: 'ガリア（現フランス・ベルギー）・ブリタニア・ライン川流域',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [12.4964, 41.9028], label: 'ローマ（元老院）', isMain: true, ally: true },
      { coordinates: [6.1432, 46.2044], label: 'ジュネーヴ（紀元前58年・ヘルウェティイ族阻止）', isMain: true },
      { coordinates: [4.5000, 47.5366], label: 'アレシア包囲戦（紀元前52年・ウェルキンゲトリクス降伏）', isMain: true, enemy: true },
      { coordinates: [1.0833, 51.1167], label: 'ブリタニア遠征（紀元前55-54年）' },
      { coordinates: [7.0982, 50.7374], label: 'ライン川渡橋（紀元前55年）' },
    ],
    weight: 2,
    tags: ['資源争奪', '指導者個人要因', '情報戦・プロパガンダ'],
    ideologies: ['ローマ帝国主義', 'ガリア部族社会'],
    causes: ['second-punic-war', 'third-punic-war'],
    influences: ['caesars-civil-war', 'roman-republic-fall'],
  },
  {
    id: 'teutoburg-forest',
    year: 9, endYear: 9,
    name: 'トイトブルク森の戦い',
    region: 0, type: 'war', era: 'ancient',
    theater: 'ゲルマニア（現ドイツ北西部）',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [8.1267, 52.4080], label: 'カルクリーゼ（戦場推定地・9年9月）', isMain: true, enemy: true },
      { coordinates: [12.4964, 41.9028], label: 'ローマ（アウグストゥス帝）', isMain: true, ally: true },
      { coordinates: [6.9603, 50.9375], label: 'コロニア・アグリッピナ（ライン軍団基地）' },
      { coordinates: [7.6261, 51.9607], label: 'ウェーザー川流域（ケルスキー族領）', isMain: true },
      { coordinates: [8.7000, 52.0000], label: '退却路の隘路（3個軍団壊滅）' },
    ],
    weight: 2,
    tags: ['誤算・誤認知', '指導者個人要因', 'ナショナリズム'],
    ideologies: ['ローマ帝国主義', 'ゲルマン部族独立'],
    causes: ['gallic-wars-caesar', 'roman-republic-fall'],
    influences: ['migration-period-wars'],
  },
  {
    id: 'roman-parthian-wars',
    year: -54, endYear: 217,
    name: 'ローマ・パルティア戦争',
    region: 2, type: 'war', era: 'ancient',
    theater: 'メソポタミア・シリア・アルメニア',
    mapHighlight: 'middleeast',
    markers: [
      { coordinates: [39.0594, 36.8625], label: 'カルラエの戦い（紀元前53年・クラッスス戦死）', isMain: true, enemy: true },
      { coordinates: [44.5805, 33.0939], label: 'クテシフォン（パルティア王都）', isMain: true, enemy: true },
      { coordinates: [36.3094, 33.5138], label: 'シリア属州都ダマスカス周辺', isMain: true, ally: true },
      { coordinates: [44.0144, 39.9526], label: 'アルメニア（緩衝国争奪地）', isMain: true },
      { coordinates: [39.0167, 37.1500], label: 'エデッサ（217年カラカラ暗殺地）', isMain: true },
      { coordinates: [12.4964, 41.9028], label: 'ローマ（共和政末期〜帝政期）', ally: true },
    ],
    weight: 2,
    tags: ['安全保障ジレンマ', '資源争奪', '帝国衰退'],
    ideologies: ['ローマ帝国主義', 'パルティア・アルサケス朝'],
    causes: ['caesars-civil-war'],
    influences: ['crisis-of-third-century', 'jewish-roman-wars'],
  },
  {
    id: 'crisis-of-third-century',
    year: 235, endYear: 284,
    name: '3世紀の危機',
    region: 0, type: 'war', era: 'ancient',
    theater: 'ローマ帝国全域（ライン・ドナウ・東方）',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [12.4964, 41.9028], label: 'ローマ（軍人皇帝の乱立）', isMain: true },
      { coordinates: [6.6322, 49.7595], label: 'トリーア（ガリア帝国260-274）', isMain: true, enemy: true },
      { coordinates: [38.2706, 34.5559], label: 'パルミラ（パルミラ帝国270-273・ゼノビア）', isMain: true, enemy: true },
      { coordinates: [40.0000, 37.0000], label: 'エデッサの戦い（260年・ウァレリアヌス捕囚）', isMain: true },
      { coordinates: [16.3738, 48.2082], label: 'ドナウ国境（ゴート族・マルコマンニ族侵入）' },
      { coordinates: [16.4375, 43.5081], label: 'スプリト（ディオクレティアヌス・284年帝国再建）', ally: true },
    ],
    weight: 2,
    tags: ['帝国衰退', '権力真空', '経済危機', '指導者個人要因'],
    ideologies: ['ローマ帝政動揺', 'テトラルキア'],
    causes: ['roman-parthian-wars', 'roman-republic-fall'],
    influences: ['migration-period-wars'],
  },
  {
    id: 'five-barbarians-china',
    year: 304, endYear: 439,
    name: '五胡十六国の動乱',
    region: 1, type: 'war', era: 'ancient',
    theater: '華北・中原',
    mapHighlight: 'asia',
    markers: [
      { coordinates: [112.4540, 34.6197], label: '洛陽（311年永嘉の乱・西晋崩壊）', isMain: true, enemy: true },
      { coordinates: [108.9398, 34.3416], label: '長安（316年陥落）', isMain: true, enemy: true },
      { coordinates: [111.5190, 36.0894], label: '平陽（304年劉淵漢趙建国）', isMain: true },
      { coordinates: [115.4640, 32.9389], label: '淝水の戦い（383年・東晋勝利）', isMain: true },
      { coordinates: [113.6253, 39.8000], label: '平城（北魏都・439年華北統一）', isMain: true, ally: true },
      { coordinates: [118.7969, 32.0603], label: '建康（東晋・南朝）', ally: true },
    ],
    weight: 3,
    tags: ['帝国衰退', '権力真空', '民族浄化', '経済危機', '遊牧vs農耕'],
    ideologies: ['漢族正統', '五胡部族連合', '仏教伝播'],
    causes: ['three-kingdoms-china', 'han-xiongnu-wars'],
    influences: ['migration-period-wars'],
  },
];
