import { War } from './types';

/** 先史〜古代文明（〜BC700）の戦争 */
export const WARS_PREHISTORIC: War[] = [
  {
    id: 'battle-of-megiddo-1457bc',
    year: -1457, endYear: -1457,
    name: 'メギドの戦い（記録に残る最古の会戦）',
    region: 2, type: 'war', era: 'prehistoric',
    theater: 'カナン（現イスラエル北部・イズレエル平原）',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [35.18, 32.59], label: 'メギド（Tel Megiddo）— 戦場', isMain: true },
      { coordinates: [32.65, 25.7], label: 'テーベ（古代エジプト都）', isMain: true, ally: true },
      { coordinates: [35.7, 31.0], label: 'カナン連合軍集結地', enemy: true },
      { coordinates: [34.65, 31.5], label: 'ガザ（エジプト軍進撃路）' },
      { coordinates: [35.0, 32.5], label: 'アルナ峠（奇襲ルート）' },
    ],
    weight: 3,
    tags: ['ナショナリズム', '帝国衰退', '指導者個人要因'],
    ideologies: ['ファラオ神権', 'カナン都市国家'],
    causes: [],
    influences: ['battle-of-kadesh', 'sea-peoples-bronze-collapse'],
  },
  {
    id: 'battle-of-kadesh',
    year: -1274, endYear: -1274,
    name: 'カデシュの戦い（最古の和平条約）',
    region: 2, type: 'war', era: 'prehistoric',
    theater: 'シリア・オロンテス川流域',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [36.52, 34.57], label: 'カデシュ（Tell Nebi Mend）— 戦場', isMain: true },
      { coordinates: [32.65, 25.7], label: 'テーベ（ラムセス2世のエジプト）', isMain: true, ally: true },
      { coordinates: [34.62, 40.02], label: 'ハットゥシャ（ヒッタイト都）', isMain: true, enemy: true },
      { coordinates: [36.3, 33.5], label: 'オロンテス川渡河地点' },
      { coordinates: [36.7, 34.7], label: 'ヒッタイト軍伏兵地' },
    ],
    weight: 3,
    tags: ['資源争奪', '安全保障ジレンマ', '指導者個人要因'],
    ideologies: ['ファラオ神権', 'ヒッタイト大王制'],
    causes: ['battle-of-megiddo-1457bc'],
    influences: ['sea-peoples-bronze-collapse'],
  },
  {
    id: 'trojan-war',
    year: -1250, endYear: -1180,
    name: 'トロイア戦争（伝説と考古学）',
    region: 2, type: 'war', era: 'prehistoric',
    theater: '小アジア西岸（現トルコ・ヒサルルク）・エーゲ海',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [26.24, 39.96], label: 'トロイア／ヒサルルク（Layer VIIa）', isMain: true, enemy: true },
      { coordinates: [22.74, 37.73], label: 'ミケーネ（アガメムノン王宮）', isMain: true, ally: true },
      { coordinates: [25.15, 35.34], label: 'クノッソス（ミノア圏）' },
      { coordinates: [26.41, 40.14], label: 'ヘレスポントス海峡（補給線）' },
      { coordinates: [22.42, 37.07], label: 'スパルタ（ヘレネー出身地）' },
    ],
    weight: 2,
    tags: ['ナショナリズム', '資源争奪', '指導者個人要因'],
    ideologies: ['ミケーネ王権', 'ホメロス的英雄観'],
    causes: [],
    influences: ['sea-peoples-bronze-collapse'],
  },
  {
    id: 'sea-peoples-bronze-collapse',
    year: -1200, endYear: -1150,
    name: '海の民の侵攻と青銅器時代の崩壊',
    region: 2, type: 'war', era: 'prehistoric',
    theater: '東地中海全域（アナトリア・レヴァント・エジプト）',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [34.62, 40.02], label: 'ハットゥシャ（ヒッタイト崩壊 BC1190頃）', isMain: true, enemy: true },
      { coordinates: [35.78, 35.52], label: 'ウガリト（焼亡 BC1185頃）', isMain: true, enemy: true },
      { coordinates: [32.65, 25.7], label: 'テーベ（ラムセス3世のエジプト・生き残り）', isMain: true, ally: true },
      { coordinates: [31.83, 30.83], label: 'ナイル・デルタ会戦（BC1175頃）', isMain: true },
      { coordinates: [22.74, 37.73], label: 'ミケーネ（崩壊）', enemy: true },
      { coordinates: [34.78, 31.67], label: 'ペリシテ人定住地（ガザ・アシュケロン）' },
    ],
    weight: 3,
    tags: ['帝国衰退', '権力真空', '経済危機', '資源争奪'],
    ideologies: ['青銅器王宮経済', '鉄器時代移行'],
    causes: ['battle-of-kadesh', 'trojan-war'],
    influences: ['battle-of-muye', 'neo-assyrian-conquests'],
  },
  {
    id: 'battle-of-muye',
    year: -1046, endYear: -1046,
    name: '牧野の戦い（殷周易姓革命）',
    region: 1, type: 'revolution', era: 'prehistoric',
    theater: '中国・黄河中流域（現河南省）',
    mapHighlight: 'asia',
    markers: [
      { coordinates: [113.91, 35.30], label: '牧野（現新郷市付近）— 決戦地', isMain: true },
      { coordinates: [114.38, 35.93], label: '朝歌（殷の都）', isMain: true, enemy: true },
      { coordinates: [108.55, 34.27], label: '岐山・周原（周の本拠）', isMain: true, ally: true },
      { coordinates: [110.80, 34.78], label: '孟津（諸侯結集の地）' },
      { coordinates: [112.45, 34.62], label: '洛邑（後の東周都・成周）' },
    ],
    weight: 3,
    tags: ['革命', '権力真空', '指導者個人要因'],
    ideologies: ['天命思想', '徳治主義', '宗法封建制'],
    causes: ['sea-peoples-bronze-collapse'],
    influences: ['spring-autumn-warring-states'],
  },
  {
    id: 'spring-autumn-warring-states',
    year: -770, endYear: -221,
    name: '春秋戦国時代',
    region: 1, type: 'war', era: 'prehistoric',
    theater: '中国本土（黄河・長江流域全域）',
    mapHighlight: 'asia',
    markers: [
      { coordinates: [112.45, 34.62], label: '洛邑（東周成立 BC770）', isMain: true },
      { coordinates: [115.47, 35.43], label: '城濮の戦い（BC632・晋vs楚）', isMain: true },
      { coordinates: [108.94, 34.34], label: '咸陽（秦の都・統一の起点）', isMain: true, ally: true },
      { coordinates: [114.30, 30.59], label: '楚（長江中流）', enemy: true },
      { coordinates: [120.62, 31.30], label: '呉・越（江南）' },
      { coordinates: [117.12, 36.65], label: '臨淄（斉の都・稷下学宮）' },
      { coordinates: [114.50, 38.04], label: '邯鄲（趙の都・長平の戦い BC260）' },
    ],
    weight: 3,
    tags: ['帝国衰退', '権力真空', '安全保障ジレンマ', '同盟暴走'],
    ideologies: ['儒家', '法家', '道家', '墨家', '兵家'],
    causes: ['battle-of-muye'],
    influences: ['chu-han-contention'],
  },
  {
    id: 'neo-assyrian-conquests',
    year: -745, endYear: -612,
    name: '新アッシリア帝国の征服',
    region: 2, type: 'war', era: 'prehistoric',
    theater: 'メソポタミア・レヴァント・エジプト・アナトリア',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [43.15, 36.36], label: 'ニネヴェ（センナケリブ・アシュルバニパル都）', isMain: true, ally: true },
      { coordinates: [43.33, 36.10], label: 'ニムルド（カルフ）— 旧都', isMain: true },
      { coordinates: [43.26, 35.45], label: 'アッシュル（宗教首都）' },
      { coordinates: [34.85, 31.57], label: 'ラキシュ包囲（BC701・センナケリブ）', isMain: true, enemy: true },
      { coordinates: [35.21, 31.78], label: 'エルサレム（ヒゼキヤ王・包囲撤退）' },
      { coordinates: [35.49, 33.27], label: 'ティルス（フェニキア服属）' },
      { coordinates: [32.65, 25.70], label: 'テーベ（BC663陥落）', enemy: true },
    ],
    weight: 3,
    tags: ['帝国衰退', '民族浄化', '情報戦・プロパガンダ', '指導者個人要因'],
    ideologies: ['アッシュル神王権', '常備軍主義', '強制移住政策'],
    causes: ['sea-peoples-bronze-collapse'],
    influences: ['fall-of-nineveh'],
  },
  {
    id: 'fall-of-nineveh',
    year: -612, endYear: -609,
    name: 'ニネヴェ陥落（アッシリア滅亡）',
    region: 2, type: 'war', era: 'prehistoric',
    theater: '北メソポタミア',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [43.15, 36.36], label: 'ニネヴェ（BC612年8月陥落）', isMain: true, enemy: true },
      { coordinates: [44.42, 32.54], label: 'バビロン（ナボポラッサル新バビロニア）', isMain: true, ally: true },
      { coordinates: [50.00, 35.00], label: 'メディア（キュアクサレス王）', isMain: true, ally: true },
      { coordinates: [40.73, 36.66], label: 'ハラン（最後のアッシリア王アッシュル・ウバリト2世 BC609）', isMain: true },
      { coordinates: [38.01, 36.83], label: 'カルケミシュ（BC605・エジプト援軍敗北）' },
    ],
    weight: 2,
    tags: ['帝国衰退', '同盟暴走', '権力真空'],
    ideologies: ['新バビロニア', 'メディア連合'],
    causes: ['neo-assyrian-conquests'],
    influences: [],
  },
];
