import { War } from './types';

/** 古代戦争（紀元前〜500年） */
export const WARS_ANCIENT: War[] = [
  {
    id: 'persian-wars',
    year: -499, endYear: -449,
    name: 'ペルシア戦争',
    region: 0, type: 'war', era: 'ancient',
    theater: 'エーゲ海・ギリシャ本土・小アジア',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [23.7275, 37.9838], label: 'アテネ', isMain: true },
      { coordinates: [23.9785, 38.1538], label: 'マラトン（紀元前490）', isMain: true },
      { coordinates: [22.5360, 38.7967], label: 'テルモピュライ（紀元前480）', isMain: true },
      { coordinates: [23.5400, 37.9667], label: 'サラミス海戦（紀元前480）', isMain: true },
      { coordinates: [23.2333, 38.2167], label: 'プラタイア（紀元前479）' },
      { coordinates: [52.8916, 29.9354], label: 'ペルセポリス（ペルシア帝国）', enemy: true },
    ],
    weight: 3,
    tags: ['帝国衰退', 'ナショナリズム', '誤算・誤認知'],
    ideologies: ['ポリス民主政', 'ペルシア専制'],
    causes: [],
    influences: ['peloponnesian-war', 'alexander-conquests'],
  },
  {
    id: 'peloponnesian-war',
    year: -431, endYear: -404,
    name: 'ペロポネソス戦争',
    region: 0, type: 'war', era: 'ancient',
    theater: 'ギリシャ本土・エーゲ海・シチリア',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [23.7275, 37.9838], label: 'アテネ（デロス同盟盟主）', isMain: true, ally: true },
      { coordinates: [22.4302, 37.0755], label: 'スパルタ（ペロポネソス同盟）', isMain: true, enemy: true },
      { coordinates: [15.0873, 37.5079], label: 'シラクサ（シチリア遠征 紀元前415-413）', isMain: true },
      { coordinates: [26.4108, 40.1486], label: 'アイゴスポタモイ海戦（紀元前405）', isMain: true },
      { coordinates: [22.7333, 38.4500], label: 'デルフォイ' },
    ],
    weight: 3,
    tags: ['安全保障ジレンマ', '同盟暴走', '帝国衰退'],
    ideologies: ['アテネ民主政', 'スパルタ寡頭政'],
    causes: ['persian-wars'],
    influences: ['alexander-conquests'],
  },
  {
    id: 'alexander-conquests',
    year: -334, endYear: -323,
    name: 'アレクサンドロス大王東征',
    region: 1, type: 'war', era: 'ancient',
    theater: '小アジア・エジプト・ペルシア・中央アジア・インダス',
    mapHighlight: 'asia',
    markers: [
      { coordinates: [22.5417, 40.6403], label: 'ペラ（マケドニア王都）', isMain: true, ally: true },
      { coordinates: [36.1667, 36.8333], label: 'イッソスの戦い（紀元前333）', isMain: true },
      { coordinates: [29.9187, 31.2001], label: 'アレクサンドリア建設（紀元前331）', isMain: true },
      { coordinates: [43.1500, 36.3500], label: 'ガウガメラの戦い（紀元前331）', isMain: true },
      { coordinates: [44.4275, 32.5364], label: 'バビロン（紀元前323年大王没）', isMain: true },
      { coordinates: [73.0479, 32.8167], label: 'ヒュダスペス川の戦い（紀元前326）', enemy: true },
    ],
    weight: 3,
    tags: ['帝国衰退', '指導者個人要因', '権力真空'],
    ideologies: ['ヘレニズム', '東西文明融合'],
    causes: ['persian-wars', 'peloponnesian-war'],
    influences: ['second-punic-war'],
  },
  {
    id: 'second-punic-war',
    year: -218, endYear: -201,
    name: '第二次ポエニ戦争',
    region: 0, type: 'war', era: 'ancient',
    theater: 'イベリア半島・アルプス・イタリア・北アフリカ',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [10.3333, 36.8528], label: 'カルタゴ（北アフリカ）', isMain: true, enemy: true },
      { coordinates: [12.4964, 41.9028], label: 'ローマ', isMain: true, ally: true },
      { coordinates: [-0.4906, 39.4699], label: 'サグントゥム（開戦の地 紀元前219）' },
      { coordinates: [16.1297, 41.3050], label: 'カンナエの戦い（紀元前216）', isMain: true },
      { coordinates: [10.0000, 36.3000], label: 'ザマの戦い（紀元前202）', isMain: true },
      { coordinates: [7.0000, 45.5000], label: 'アルプス越え（紀元前218）' },
    ],
    weight: 3,
    tags: ['資源争奪', '指導者個人要因', '安全保障ジレンマ'],
    ideologies: ['ローマ共和政', 'カルタゴ商業国家'],
    causes: [],
    influences: ['third-punic-war', 'caesars-civil-war'],
  },
  {
    id: 'third-punic-war',
    year: -149, endYear: -146,
    name: '第三次ポエニ戦争',
    region: 0, type: 'war', era: 'ancient',
    theater: '北アフリカ（カルタゴ）',
    mapHighlight: 'africa',
    markers: [
      { coordinates: [10.3333, 36.8528], label: 'カルタゴ（紀元前146年完全破壊）', isMain: true, enemy: true },
      { coordinates: [12.4964, 41.9028], label: 'ローマ', isMain: true, ally: true },
      { coordinates: [10.1815, 36.8065], label: 'ウティカ（ローマ拠点）' },
      { coordinates: [10.6500, 36.7833], label: 'ネアポリス周辺包囲線' },
    ],
    weight: 2,
    tags: ['帝国衰退', '民族浄化', '資源争奪'],
    ideologies: ['ローマ帝国主義'],
    causes: ['second-punic-war'],
    influences: ['caesars-civil-war'],
  },
  {
    id: 'chu-han-contention',
    year: -206, endYear: -202,
    name: '楚漢戦争',
    region: 1, type: 'war', era: 'ancient',
    theater: '中国本土（中原・関中・楚地）',
    mapHighlight: 'asia',
    markers: [
      { coordinates: [108.9398, 34.3416], label: '咸陽（秦都）', isMain: true },
      { coordinates: [117.1500, 33.4500], label: '垓下の戦い（紀元前202）', isMain: true },
      { coordinates: [113.6253, 34.7466], label: '滎陽（持久戦の要地）' },
      { coordinates: [108.9402, 34.3416], label: '長安（漢建国）', isMain: true, ally: true },
      { coordinates: [117.1840, 34.2614], label: '彭城（項羽の楚都）', enemy: true },
    ],
    weight: 3,
    tags: ['権力真空', '革命', '指導者個人要因'],
    ideologies: ['法家', '儒家', '漢王朝'],
    causes: [],
    influences: ['three-kingdoms-china'],
  },
  {
    id: 'caesars-civil-war',
    year: -49, endYear: -45,
    name: 'カエサル内戦',
    region: 0, type: 'revolution', era: 'ancient',
    theater: 'イタリア・ギリシャ・エジプト・スペイン',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [12.4964, 41.9028], label: 'ローマ（元老院）', isMain: true },
      { coordinates: [12.3911, 44.0937], label: 'ルビコン川渡河（紀元前49）', isMain: true },
      { coordinates: [22.4000, 39.2500], label: 'ファルサルスの戦い（紀元前48）', isMain: true },
      { coordinates: [29.9187, 31.2001], label: 'アレクサンドリア（ポンペイウス暗殺）' },
      { coordinates: [-4.7794, 37.8882], label: 'ムンダの戦い（紀元前45）' },
    ],
    weight: 2,
    tags: ['権力真空', '指導者個人要因', '革命'],
    ideologies: ['共和政', '独裁・帝政移行'],
    causes: ['second-punic-war', 'third-punic-war'],
    influences: ['roman-republic-fall'],
  },
  {
    id: 'roman-republic-fall',
    year: -43, endYear: -30,
    name: 'ローマ共和政崩壊（オクタヴィアヌス内戦）',
    region: 0, type: 'revolution', era: 'ancient',
    theater: '地中海全域',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [12.4964, 41.9028], label: 'ローマ（第二次三頭政治）', isMain: true },
      { coordinates: [24.1000, 40.9000], label: 'フィリッピの戦い（紀元前42）', isMain: true },
      { coordinates: [20.7644, 38.9500], label: 'アクティウムの海戦（紀元前31）', isMain: true },
      { coordinates: [29.9187, 31.2001], label: 'アレクサンドリア（クレオパトラ・アントニウス自害 紀元前30）', isMain: true, enemy: true },
      { coordinates: [12.4964, 41.9028], label: 'プリンキパトゥス成立（紀元前27）' },
    ],
    weight: 3,
    tags: ['権力真空', '革命', '指導者個人要因', '帝国衰退'],
    ideologies: ['共和政', 'プリンキパトゥス（元首政）'],
    causes: ['caesars-civil-war'],
    influences: ['jewish-roman-wars', 'migration-period-wars'],
  },
  {
    id: 'jewish-roman-wars',
    year: 66, endYear: 73,
    name: 'ユダヤ戦争',
    region: 2, type: 'war', era: 'ancient',
    theater: 'ユダヤ属州（パレスチナ）',
    mapHighlight: 'middleeast',
    markers: [
      { coordinates: [35.2137, 31.7683], label: 'エルサレム包囲（70年・第二神殿崩壊）', isMain: true, ally: true },
      { coordinates: [35.3536, 31.3147], label: 'マサダ（73年陥落）', isMain: true },
      { coordinates: [35.2950, 32.7000], label: 'ヨタパタ攻囲戦（67年）' },
      { coordinates: [12.4964, 41.9028], label: 'ローマ（フラウィウス朝の正統性）', isMain: true, enemy: true },
      { coordinates: [35.0997, 33.0058], label: 'カエサレア（ローマ属州都）' },
    ],
    weight: 2,
    tags: ['宗教対立', 'ナショナリズム', '帝国衰退'],
    ideologies: ['ユダヤ教メシアニズム', 'ローマ帝国主義'],
    causes: ['roman-republic-fall'],
    influences: ['migration-period-wars'],
  },
  {
    id: 'three-kingdoms-china',
    year: 184, endYear: 280,
    name: '三国時代戦乱（後漢末〜赤壁・三国鼎立）',
    region: 1, type: 'war', era: 'ancient',
    theater: '中国本土',
    mapHighlight: 'asia',
    markers: [
      { coordinates: [112.4540, 34.6197], label: '洛陽（後漢都）', isMain: true },
      { coordinates: [113.5800, 30.0500], label: '赤壁の戦い（208年）', isMain: true },
      { coordinates: [104.0668, 30.5728], label: '成都（蜀漢）', isMain: true, ally: true },
      { coordinates: [118.7969, 32.0603], label: '建業（呉）', isMain: true },
      { coordinates: [114.3055, 30.5928], label: '武昌（呉拠点）' },
      { coordinates: [114.4980, 36.0978], label: '鄴（魏拠点）', isMain: true, enemy: true },
    ],
    weight: 3,
    tags: ['帝国衰退', '権力真空', '経済危機'],
    ideologies: ['儒教秩序崩壊', '黄巾道'],
    causes: ['chu-han-contention'],
    influences: ['migration-period-wars'],
  },
  {
    id: 'migration-period-wars',
    year: 376, endYear: 476,
    name: 'ゲルマン民族大移動',
    region: 0, type: 'war', era: 'ancient',
    theater: 'ヨーロッパ全域',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [26.5667, 41.6772], label: 'アドリアノープルの戦い（378年）', isMain: true },
      { coordinates: [12.4964, 41.9028], label: 'ローマ劫掠（410年・西ゴート族）', isMain: true },
      { coordinates: [4.0500, 49.1000], label: 'カタラウヌム平原の戦い（451年・対アッティラ）', isMain: true },
      { coordinates: [12.4964, 41.9028], label: '西ローマ帝国滅亡（476年）', isMain: true },
      { coordinates: [28.9784, 41.0082], label: 'コンスタンティノープル（東ローマ）', ally: true },
      { coordinates: [37.6173, 55.7558], label: 'フン族西進拠点', enemy: true },
    ],
    weight: 3,
    tags: ['帝国衰退', '権力真空', '経済危機', 'ナショナリズム', '遊牧vs農耕'],
    ideologies: ['ゲルマン部族社会', 'ローマ衰退'],
    causes: ['roman-republic-fall', 'three-kingdoms-china'],
    influences: ['gothic-war-justinian'],
  },
  {
    id: 'gothic-war-justinian',
    year: 535, endYear: 554,
    name: 'ユスティニアヌスのゴート戦争',
    region: 0, type: 'war', era: 'ancient',
    theater: 'イタリア半島',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [28.9784, 41.0082], label: 'コンスタンティノープル（東ローマ）', isMain: true, ally: true },
      { coordinates: [12.4964, 41.9028], label: 'ローマ（536年ベリサリウス占領）', isMain: true },
      { coordinates: [12.2035, 44.4185], label: 'ラヴェンナ（東ゴート王都・540年陥落）', isMain: true, enemy: true },
      { coordinates: [12.7833, 43.2333], label: 'タギナエの戦い（552年）', isMain: true },
      { coordinates: [14.2681, 40.8358], label: 'モンス・ラクタリウス（553年・東ゴート滅亡）' },
    ],
    weight: 2,
    tags: ['帝国衰退', '指導者個人要因', '経済危機'],
    ideologies: ['ローマ復興（renovatio imperii）', 'アリウス派ゴート'],
    causes: ['migration-period-wars'],
    influences: [],
  },
];
