import { War, EraId } from './types';

export const ERA_CONFIG: Record<EraId, { label: string; start: number; end: number }> = {
  'early-modern':   { label: '近世（1700〜）', start: 1700, end: 1899 },
  '20th-century':   { label: '20世紀',         start: 1900, end: 1999 },
  'contemporary':   { label: '現代',            start: 2000, end: 2030 },
};

export const WARS: War[] = [

  /* ─────────────────── 近世（1700-1899） ─────────────────── */

  {
    id: 'great-northern-war',
    year: 1700, endYear: 1721,
    name: '大北方戦争',
    region: 0, type: 'war', era: 'early-modern',
    theater: '北欧・バルト海・東欧',
    mapHighlight: 'europe',
    markers: [
      { cx: 185, cy: 12, label: 'ストックホルム（スウェーデン・カール12世）', isMain: true },
      { cx: 215, cy: 18, label: 'モスクワ（ロシア・ピョートル大帝）', enemy: true },
      { cx: 190, cy: 16, label: 'ナルヴァ（1700年初戦・スウェーデン勝利）' },
      { cx: 210, cy: 24, label: 'ポルタヴァ（1709年決戦・ロシア勝利）', isMain: true },
      { cx: 193, cy: 14, label: 'ニスタット（1721年講和条約）' },
    ],
  },
  {
    id: 'war-of-spanish-succession',
    year: 1701, endYear: 1714,
    name: 'スペイン継承戦争',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'ヨーロッパ全域・北米（アン女王戦争）',
    mapHighlight: 'europe',
    markers: [
      { cx: 160, cy: 50, label: 'マドリード（フェリペ5世）', isMain: true },
      { cx: 170, cy: 42, label: 'フランス（ルイ14世）', enemy: true },
      { cx: 162, cy: 28, label: '英国・蘭・墺（同盟）', ally: true },
      { cx: 166, cy: 38, label: 'ブレンハイム（1704決戦）', isMain: true },
      { cx: 170, cy: 35, label: 'ユトレヒト（条約1713）' },
    ],
  },
  {
    id: 'war-of-polish-succession',
    year: 1733, endYear: 1738,
    name: 'ポーランド継承戦争',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'ポーランド・イタリア半島・ライン川流域',
    mapHighlight: 'europe',
    markers: [
      { cx: 193, cy: 22, label: 'ワルシャワ（選挙地・スタニスワフ1世支持）', isMain: true },
      { cx: 185, cy: 35, label: 'ウィーン（オーストリア・ハプスブルク）', enemy: true },
      { cx: 170, cy: 42, label: 'パリ（フランス・ルイ15世）', ally: true },
      { cx: 215, cy: 22, label: 'サンクトペテルブルク（ロシア）', enemy: true },
      { cx: 183, cy: 36, label: 'ダンツィヒ包囲戦（1734年）', isMain: true },
    ],
  },
  {
    id: 'war-of-austrian-succession',
    year: 1740, endYear: 1748,
    name: 'オーストリア継承戦争',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'ヨーロッパ全域・北米（ジョージ王戦争）・インド',
    mapHighlight: 'europe',
    markers: [
      { cx: 185, cy: 35, label: 'ウィーン（マリア・テレジア）', isMain: true },
      { cx: 183, cy: 22, label: 'ベルリン（フリードリヒ2世・プロイセン）', enemy: true },
      { cx: 185, cy: 30, label: 'シュレジエン（プロイセン侵攻・1740.12）', isMain: true },
      { cx: 170, cy: 42, label: 'フランス（対墺同盟）', enemy: true },
      { cx: 175, cy: 38, label: 'フォントノワ（1745決戦）' },
    ],
  },
  {
    id: 'russo-turkish-war-1768',
    year: 1768, endYear: 1774,
    name: '露土戦争（1768-1774）',
    region: 0, type: 'war', era: 'early-modern',
    theater: '黒海北岸・バルカン半島・エーゲ海',
    mapHighlight: 'eastern-europe',
    markers: [
      { cx: 215, cy: 22, label: 'サンクトペテルブルク（ロシア・エカチェリーナ2世）', isMain: true },
      { cx: 205, cy: 50, label: 'コンスタンティノープル（オスマン帝国）', enemy: true },
      { cx: 207, cy: 32, label: 'カグル（1770年ルミャンツェフ勝利）', isMain: true },
      { cx: 205, cy: 40, label: 'チェスメ海戦（1770年ロシア艦隊勝利）', isMain: true },
      { cx: 208, cy: 30, label: 'キュチュク・カイナルジャ（1774年条約）' },
    ],
  },
  {
    id: 'seven-years-war',
    year: 1756, endYear: 1763,
    name: '七年戦争',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'ヨーロッパ・北米・インド・カリブ海',
    mapHighlight: 'europe',
    markers: [
      { cx: 183, cy: 22, label: 'プロイセン（ベルリン）', isMain: true },
      { cx: 185, cy: 35, label: 'オーストリア（ウィーン）', enemy: true },
      { cx: 170, cy: 42, label: 'フランス', enemy: true },
      { cx: 210, cy: 18, label: 'ロシア', enemy: true },
      { cx: 162, cy: 28, label: '英国（同盟）', ally: true },
    ],
  },
  {
    id: 'american-independence',
    year: 1775, endYear: 1783,
    name: 'アメリカ独立戦争',
    region: 3, type: 'war', era: 'early-modern',
    theater: '北アメリカ東海岸',
    mapHighlight: 'north-america',
    markers: [
      { cx: 112, cy: 52, label: 'ボストン' },
      { cx: 107, cy: 65, label: 'フィラデルフィア' },
      { cx: 100, cy: 85, label: 'ヨークタウン（決戦）', isMain: true },
      { cx: 170, cy: 42, label: '仏（支援）', ally: true },
      { cx: 162, cy: 28, label: '英', enemy: true },
    ],
  },
  {
    id: 'french-revolution',
    year: 1789, endYear: 1799,
    name: 'フランス革命',
    region: 0, type: 'revolution', era: 'early-modern',
    theater: 'フランス・ヨーロッパ',
    mapHighlight: 'europe',
    markers: [
      { cx: 170, cy: 42, label: 'パリ（バスティーユ）', isMain: true },
      { cx: 174, cy: 40, label: 'ヴェルサイユ' },
      { cx: 185, cy: 35, label: 'オーストリア', enemy: true },
      { cx: 162, cy: 28, label: '英（干渉）', enemy: true },
    ],
  },
  {
    id: 'haitian-revolution',
    year: 1791, endYear: 1804,
    name: 'ハイチ革命',
    region: 3, type: 'revolution', era: 'early-modern',
    theater: 'サン＝ドマング（ハイチ）',
    mapHighlight: 'north-america',
    markers: [
      { cx: 100, cy: 110, label: 'ル・カップ（蜂起1791.8.22）', isMain: true },
      { cx: 102, cy: 112, label: 'ポルトープランス（独立宣言1804.1.1）', isMain: true },
      { cx: 170, cy: 42, label: 'パリ（仏：黒人法・ナポレオン遠征）', enemy: true },
      { cx: 162, cy: 28, label: '英国（介入失敗）', enemy: true },
      { cx: 105, cy: 105, label: 'ヴェルティエール（最終決戦1803.11）' },
    ],
  },
  {
    id: 'napoleonic-wars',
    year: 1803, endYear: 1815,
    name: 'ナポレオン戦争',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'ヨーロッパ全域・エジプト',
    mapHighlight: 'europe',
    markers: [
      { cx: 170, cy: 42, label: 'パリ（ナポレオン本拠）', isMain: true },
      { cx: 186, cy: 33, label: 'アウステルリッツ（1805決戦）', isMain: false },
      { cx: 215, cy: 22, label: 'モスクワ（1812遠征）' },
      { cx: 183, cy: 28, label: 'ライプツィヒ（諸国民の戦い1813）' },
      { cx: 168, cy: 36, label: 'ワーテルロー（最終決戦1815）', isMain: true },
    ],
  },
  {
    id: 'war-of-1812',
    year: 1812, endYear: 1815,
    name: '1812年戦争（米英戦争）',
    region: 3, type: 'war', era: 'early-modern',
    theater: '北米五大湖・大西洋・ニューオリンズ',
    mapHighlight: 'north-america',
    markers: [
      { cx: 103, cy: 60, label: 'ワシントンD.C.（焼き討ち1814.8）', isMain: true },
      { cx: 105, cy: 55, label: '五大湖（エリー湖海戦）' },
      { cx: 100, cy: 105, label: 'ニューオリンズ（決戦1815.1）', isMain: true },
      { cx: 162, cy: 28, label: '英国', enemy: true },
      { cx: 110, cy: 50, label: 'ボルチモア（星条旗誕生）' },
    ],
  },
  {
    id: 'latin-american-independence',
    year: 1810, endYear: 1825,
    name: 'ラテンアメリカ独立戦争',
    region: 3, type: 'revolution', era: 'early-modern',
    theater: '南米全域',
    mapHighlight: 'south-america',
    markers: [
      { cx: 92, cy: 195, label: 'ボヤカ（ボリーバル勝利1819.8）', isMain: true },
      { cx: 100, cy: 245, label: 'チャカブコ・マイプー（サン・マルティン勝利1817-18）', isMain: true },
      { cx: 95, cy: 220, label: 'アヤクーチョ（最終戦1824.12）', isMain: true },
      { cx: 88, cy: 235, label: 'ブエノスアイレス（5月革命1810.5）' },
      { cx: 165, cy: 50, label: 'マドリード（スペイン）', enemy: true },
    ],
  },
  {
    id: 'greek-independence-war',
    year: 1821, endYear: 1832,
    name: 'ギリシャ独立戦争',
    region: 0, type: 'revolution', era: 'early-modern',
    theater: 'バルカン半島・エーゲ海',
    mapHighlight: 'eastern-europe',
    markers: [
      { cx: 192, cy: 50, label: 'アテネ（独立首都）', isMain: true },
      { cx: 195, cy: 48, label: 'ミソロンギ（包囲・バイロン死）', isMain: true },
      { cx: 200, cy: 46, label: 'ナヴァリノ（連合艦隊勝利1827）' },
      { cx: 205, cy: 50, label: 'コンスタンティノープル（オスマン）', enemy: true },
      { cx: 162, cy: 28, label: '英・仏・露（介入）', ally: true },
    ],
  },
  {
    id: 'mexican-american-war',
    year: 1846, endYear: 1848,
    name: '米墨戦争',
    region: 3, type: 'war', era: 'early-modern',
    theater: 'メキシコ北部・カリフォルニア',
    mapHighlight: 'north-america',
    markers: [
      { cx: 80, cy: 90, label: 'メキシコ・シティ（陥落1847.9）', isMain: true },
      { cx: 75, cy: 80, label: 'モンテレイ・ブエナビスタ（決戦）' },
      { cx: 72, cy: 75, label: 'リオ・グランデ（開戦地）' },
      { cx: 65, cy: 70, label: 'カリフォルニア（占領）' },
      { cx: 62, cy: 75, label: 'サンフェ・トラム（米領化）' },
    ],
  },
  {
    id: 'taiping-rebellion',
    year: 1850, endYear: 1864,
    name: '太平天国の乱',
    region: 1, type: 'revolution', era: 'early-modern',
    theater: '中国南部・長江流域',
    mapHighlight: 'east-asia',
    markers: [
      { cx: 273, cy: 47, label: '南京（天京・首都）', isMain: true },
      { cx: 270, cy: 52, label: '広西省金田村（蜂起地）', isMain: true },
      { cx: 272, cy: 45, label: '武昌（占領）' },
      { cx: 268, cy: 42, label: '北京（清朝）', enemy: true },
      { cx: 273, cy: 45, label: '上海（湘軍・常勝軍）' },
    ],
  },
  {
    id: 'indian-rebellion',
    year: 1857, endYear: 1858,
    name: 'インド大反乱（セポイの乱）',
    region: 1, type: 'colonial', era: 'early-modern',
    theater: '北インド・中央インド',
    mapHighlight: 'south-asia',
    markers: [
      { cx: 252, cy: 95, label: 'デリー（ムガル皇帝復位）', isMain: true },
      { cx: 256, cy: 100, label: 'ラクナウ（包囲戦）', isMain: true },
      { cx: 258, cy: 102, label: 'カーンプル（虐殺）' },
      { cx: 254, cy: 92, label: 'メーラト（蜂起地）' },
      { cx: 162, cy: 28, label: '英国（東インド会社）', enemy: true },
    ],
  },
  {
    id: 'crimean-war',
    year: 1853, endYear: 1856,
    name: 'クリミア戦争',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'クリミア半島・黒海沿岸',
    mapHighlight: 'crimea',
    markers: [
      { cx: 208, cy: 40, label: 'セヴァストポリ（包囲戦）', isMain: true },
      { cx: 205, cy: 48, label: 'コンスタンティノープル（英仏拠点）', ally: true },
      { cx: 215, cy: 22, label: 'ロシア帝国', enemy: true },
      { cx: 162, cy: 28, label: '英国', ally: true },
      { cx: 170, cy: 42, label: 'フランス', ally: true },
    ],
  },
  {
    id: 'second-opium-war',
    year: 1856, endYear: 1860,
    name: '第二次アヘン戦争（アロー戦争）',
    region: 1, type: 'colonial', era: 'early-modern',
    theater: '中国南東部・北京',
    mapHighlight: 'east-asia',
    markers: [
      { cx: 268, cy: 42, label: '北京（円明園焼き討ち1860.10）', isMain: true },
      { cx: 270, cy: 50, label: '広州（占領1858）', isMain: true },
      { cx: 269, cy: 44, label: '天津（条約締結地1858）' },
      { cx: 162, cy: 28, label: '英・仏（連合軍）', ally: true },
      { cx: 215, cy: 22, label: 'ロシア（沿海州獲得）', ally: true },
    ],
  },
  {
    id: 'italian-unification',
    year: 1859, endYear: 1871,
    name: 'イタリア統一戦争（リソルジメント）',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'イタリア半島全域',
    mapHighlight: 'europe',
    markers: [
      { cx: 175, cy: 42, label: 'トリノ→ローマ（首都変遷）', isMain: true },
      { cx: 175, cy: 45, label: 'マジェンタ・ソルフェリーノ（1859決戦）', isMain: true },
      { cx: 178, cy: 50, label: 'シチリア（ガリバルディ赤シャツ千人遠征1860）' },
      { cx: 174, cy: 47, label: 'ヴェネチア（1866併合）' },
      { cx: 176, cy: 48, label: 'ローマ（1870併合・教皇国家終焉）', isMain: true },
    ],
  },
  {
    id: 'american-civil-war',
    year: 1861, endYear: 1865,
    name: '南北戦争',
    region: 3, type: 'war', era: 'early-modern',
    theater: '北アメリカ東部・南部',
    mapHighlight: 'north-america',
    markers: [
      { cx: 104, cy: 70, label: 'リッチモンド（南軍首都）', enemy: true },
      { cx: 105, cy: 65, label: 'ゲティズバーグ（1863決戦）', isMain: true },
      { cx: 103, cy: 60, label: 'ワシントンD.C.（北軍首都）', ally: true },
      { cx: 99, cy: 78, label: 'アポマトックス（南軍降伏）' },
    ],
  },
  {
    id: 'boshin-war',
    year: 1868, endYear: 1869,
    name: '戊辰戦争',
    region: 1, type: 'revolution', era: 'early-modern',
    theater: '日本列島',
    mapHighlight: 'east-asia',
    markers: [
      { cx: 290, cy: 48, label: '京都（鳥羽伏見1868.1）', isMain: true },
      { cx: 291, cy: 47, label: '江戸（無血開城1868.5）', isMain: true },
      { cx: 292, cy: 46, label: '会津若松（陥落1868.11）' },
      { cx: 293, cy: 44, label: '函館・五稜郭（最終戦1869.5）' },
      { cx: 290, cy: 50, label: '薩摩・長州（新政府軍）', ally: true },
    ],
  },
  {
    id: 'russo-turkish-war-1877',
    year: 1877, endYear: 1878,
    name: '露土戦争（1877-78）',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'バルカン・カフカス',
    mapHighlight: 'eastern-europe',
    markers: [
      { cx: 215, cy: 22, label: 'サンクトペテルブルク（露）', isMain: true },
      { cx: 195, cy: 42, label: 'プレヴェン（5か月包囲戦）', isMain: true },
      { cx: 200, cy: 45, label: 'コンスタンティノープル直前（停戦）' },
      { cx: 192, cy: 38, label: 'サン・ステファノ条約（1878.3）' },
      { cx: 183, cy: 22, label: 'ベルリン（条約改定1878.6）' },
    ],
  },
  {
    id: 'paraguayan-war',
    year: 1864, endYear: 1870,
    name: 'パラグアイ戦争（三国同盟戦争）',
    region: 3, type: 'war', era: 'early-modern',
    theater: 'パラグアイ全土・周辺地域',
    mapHighlight: 'south-america',
    markers: [
      { cx: 92, cy: 235, label: 'アスンシオン（パラグアイ首都）', isMain: true },
      { cx: 95, cy: 240, label: 'セロ・コラ（ロペス戦死1870.3.1）', isMain: true },
      { cx: 100, cy: 230, label: 'ウマイタ要塞（1868.7陥落）' },
      { cx: 88, cy: 235, label: 'ブエノスアイレス（亜・三国同盟）', enemy: true },
      { cx: 90, cy: 230, label: 'リオデジャネイロ（伯）', enemy: true },
    ],
  },
  {
    id: 'franco-prussian-war',
    year: 1870, endYear: 1871,
    name: '普仏戦争',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'フランス・アルザス＝ロレーヌ',
    mapHighlight: 'europe',
    markers: [
      { cx: 183, cy: 22, label: 'プロイセン（ベルリン）', isMain: true },
      { cx: 173, cy: 37, label: 'スダン（ナポレオン3世捕虜）', isMain: true },
      { cx: 174, cy: 33, label: 'メス（包囲戦）' },
      { cx: 170, cy: 42, label: 'パリ（包囲・コミューン）' },
      { cx: 174, cy: 40, label: 'ヴェルサイユ（ドイツ帝国宣言）' },
    ],
  },
  {
    id: 'opium-war',
    year: 1840, endYear: 1842,
    name: 'アヘン戦争',
    region: 1, type: 'war', era: 'early-modern',
    theater: '中国南東部沿岸',
    mapHighlight: 'east-asia',
    markers: [
      { cx: 270, cy: 50, label: '広州（戦端）', isMain: true },
      { cx: 275, cy: 48, label: '香港（割譲）', isMain: true },
      { cx: 273, cy: 45, label: '寧波・上海（占領）' },
      { cx: 272, cy: 43, label: '南京（条約締結）' },
      { cx: 162, cy: 28, label: '英国', ally: true },
    ],
  },
  {
    id: 'first-sino-japanese-war',
    year: 1894, endYear: 1895,
    name: '日清戦争',
    region: 1, type: 'war', era: 'early-modern',
    theater: '朝鮮半島・満洲・黄海',
    mapHighlight: 'east-asia',
    markers: [
      { cx: 290, cy: 48, label: '東京（大本営）', isMain: true },
      { cx: 271, cy: 42, label: '旅順（陥落）', isMain: true },
      { cx: 278, cy: 47, label: '平壌（陸上決戦）' },
      { cx: 268, cy: 42, label: '北京（清国）', enemy: true },
      { cx: 280, cy: 50, label: '黄海（海戦）' },
    ],
  },
  {
    id: 'russo-japanese-war',
    year: 1904, endYear: 1905,
    name: '日露戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: '満洲・朝鮮・対馬海峡',
    mapHighlight: 'east-asia',
    markers: [
      { cx: 290, cy: 48, label: '東京（大本営）', isMain: true },
      { cx: 271, cy: 42, label: '旅順（203高地）', isMain: true },
      { cx: 268, cy: 36, label: '奉天（最大陸上決戦）' },
      { cx: 284, cy: 55, label: '対馬海峡（バルチック艦隊壊滅）', isMain: true },
      { cx: 215, cy: 22, label: 'サンクトペテルブルク（ロシア）', enemy: true },
    ],
  },

  {
    id: 'spanish-american-war',
    year: 1898, endYear: 1898,
    name: '米西戦争',
    region: 3, type: 'war', era: 'early-modern',
    theater: 'キューバ・プエルトリコ・フィリピン・グアム',
    mapHighlight: 'north-america',
    markers: [
      { cx: 100, cy: 105, label: 'ハバナ港（メイン号爆沈1898.2）', isMain: true },
      { cx: 102, cy: 110, label: 'サンチアゴ（決戦1898.7）' },
      { cx: 104, cy: 112, label: 'プエルトリコ（占領）' },
      { cx: 290, cy: 78, label: 'マニラ湾（フィリピン1898.5）', isMain: true },
      { cx: 295, cy: 80, label: 'グアム（無血占領）' },
    ],
  },

  {
    id: 'second-boer-war',
    year: 1899, endYear: 1902,
    name: '第二次ボーア戦争',
    region: 2, type: 'colonial', era: 'early-modern',
    theater: '南アフリカ（トランスヴァール・オレンジ自由国）',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 188, cy: 165, label: 'プレトリア（ボーア首都・陥落1900.6）', isMain: true },
      { cx: 185, cy: 168, label: 'ヨハネスブルク（金鉱）' },
      { cx: 192, cy: 162, label: 'レディスミス（包囲戦）' },
      { cx: 187, cy: 167, label: '強制収容所（女性・子供死亡）', isMain: true },
      { cx: 162, cy: 28, label: '英国', ally: true },
    ],
  },
  {
    id: 'boxer-rebellion',
    year: 1899, endYear: 1901,
    name: '義和団事件',
    region: 1, type: 'revolution', era: '20th-century',
    theater: '北中国・北京',
    mapHighlight: 'east-asia',
    markers: [
      { cx: 268, cy: 42, label: '北京（公使館包囲1900.6）', isMain: true },
      { cx: 269, cy: 44, label: '天津（連合軍上陸地）', isMain: true },
      { cx: 268, cy: 40, label: '紫禁城（西太后逃亡）' },
      { cx: 290, cy: 48, label: '日本（連合軍最大派遣）', ally: true },
      { cx: 215, cy: 22, label: 'ロシア（満洲占領）', ally: true },
    ],
  },

  {
    id: 'satsuma-rebellion',
    year: 1877, endYear: 1877,
    name: '西南戦争',
    region: 1, type: 'revolution', era: 'early-modern',
    theater: '南九州（鹿児島・熊本・宮崎）',
    mapHighlight: 'east-asia',
    markers: [
      { cx: 290, cy: 50, label: '鹿児島（西郷蜂起・最終戦城山）', isMain: true },
      { cx: 290, cy: 49, label: '熊本城（籠城戦1877.2-4）', isMain: true },
      { cx: 291, cy: 50, label: '田原坂（最大激戦1877.3）' },
      { cx: 290, cy: 47, label: '東京（明治政府）', enemy: true },
      { cx: 291, cy: 49, label: '延岡・宮崎（撤退戦）' },
    ],
  },

  /* ─────────────────── 20世紀（1900-1999） ─────────────────── */

  {
    id: 'second-sino-japanese-war',
    year: 1937, endYear: 1945,
    name: '日中戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: '中国全土',
    mapHighlight: 'east-asia',
    markers: [
      { cx: 282, cy: 42, label: '盧溝橋（開戦1937.7.7）', isMain: true },
      { cx: 272, cy: 43, label: '南京（虐殺1937.12）', isMain: true },
      { cx: 273, cy: 45, label: '上海（激戦1937）' },
      { cx: 268, cy: 50, label: '重慶（国民政府移転）' },
      { cx: 290, cy: 48, label: '東京（大本営）', enemy: true },
    ],
  },
  {
    id: 'first-indochina-war',
    year: 1946, endYear: 1954,
    name: '第一次インドシナ戦争',
    region: 1, type: 'colonial', era: '20th-century',
    theater: 'ベトナム・ラオス・カンボジア',
    mapHighlight: 'southeast-asia',
    markers: [
      { cx: 271, cy: 62, label: 'ハノイ（ベトミン拠点）', isMain: true },
      { cx: 268, cy: 60, label: 'ディエンビエンフー（決戦1954.5.7）', isMain: true },
      { cx: 272, cy: 58, label: 'カオバン（中越国境補給）' },
      { cx: 273, cy: 75, label: 'サイゴン（仏軍司令部）', enemy: true },
      { cx: 170, cy: 42, label: 'パリ（フランス本国）', enemy: true },
    ],
  },
  {
    id: 'greek-civil-war',
    year: 1946, endYear: 1949,
    name: 'ギリシャ内戦',
    region: 0, type: 'revolution', era: '20th-century',
    theater: 'ギリシャ北部・山岳地帯',
    mapHighlight: 'eastern-europe',
    markers: [
      { cx: 192, cy: 50, label: 'アテネ（王党派政府）', isMain: true },
      { cx: 195, cy: 47, label: 'グランモス山（最終戦1949.8）', isMain: true },
      { cx: 193, cy: 48, label: 'ヴィツィ山（共産党ゲリラ）' },
      { cx: 162, cy: 28, label: '英・米（トルーマン・ドクトリン）', ally: true },
      { cx: 195, cy: 45, label: 'ユーゴスラビア（チトー支援→断絶1948）' },
    ],
  },
  {
    id: 'chinese-civil-war',
    year: 1946, endYear: 1949,
    name: '中国国共内戦',
    region: 1, type: 'revolution', era: '20th-century',
    theater: '中国全土',
    mapHighlight: 'east-asia',
    markers: [
      { cx: 268, cy: 42, label: '北京（解放1949.1）', isMain: true },
      { cx: 273, cy: 45, label: '上海（解放1949.5）' },
      { cx: 275, cy: 40, label: '延安（共産党根拠地）', isMain: true },
      { cx: 268, cy: 35, label: '瀋陽（東北戦線決戦）' },
      { cx: 285, cy: 55, label: '台北（国民党敗走1949）', enemy: true },
    ],
  },
  {
    id: 'malayan-emergency',
    year: 1948, endYear: 1960,
    name: 'マラヤ非常事態',
    region: 1, type: 'colonial', era: '20th-century',
    theater: 'マラヤ連邦（現マレーシア）',
    mapHighlight: 'southeast-asia',
    markers: [
      { cx: 280, cy: 95, label: 'クアラルンプール（首都）', isMain: true },
      { cx: 282, cy: 98, label: 'ジャングル（共産党MNLAゲリラ拠点）', isMain: true },
      { cx: 285, cy: 92, label: '新村（住民隔離村約500か所）' },
      { cx: 162, cy: 28, label: '英国（テンプラー高等弁務官）', ally: true },
      { cx: 268, cy: 50, label: '中国（MCP支援）', enemy: true },
    ],
  },
  {
    id: 'first-arab-israeli-war',
    year: 1948, endYear: 1949,
    name: '第一次中東戦争（パレスチナ戦争）',
    region: 2, type: 'war', era: '20th-century',
    theater: 'パレスチナ・周辺アラブ諸国',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 204, cy: 65, label: 'テルアビブ（独立宣言1948.5.14）', isMain: true },
      { cx: 205, cy: 60, label: 'エルサレム（分割）', isMain: true },
      { cx: 202, cy: 68, label: 'ガザ（エジプト統治）' },
      { cx: 198, cy: 75, label: 'カイロ（エジプト）', enemy: true },
      { cx: 210, cy: 55, label: 'ダマスカス（シリア）', enemy: true },
    ],
  },
  {
    id: 'first-indo-pakistani-war',
    year: 1947, endYear: 1948,
    name: '第一次印パ戦争（カシミール紛争）',
    region: 1, type: 'war', era: '20th-century',
    theater: 'カシミール地方',
    mapHighlight: 'south-asia',
    markers: [
      { cx: 252, cy: 88, label: 'スリナガル（カシミール首都）', isMain: true },
      { cx: 250, cy: 86, label: 'ムザッファラバード（パキスタン側）', enemy: true },
      { cx: 252, cy: 95, label: 'デリー（インド）', ally: true },
      { cx: 248, cy: 92, label: 'カラチ（パキスタン）', enemy: true },
      { cx: 254, cy: 90, label: 'ジャンムー（インド側）' },
    ],
  },
  {
    id: 'suez-crisis',
    year: 1956, endYear: 1956,
    name: 'スエズ動乱（第二次中東戦争）',
    region: 2, type: 'war', era: '20th-century',
    theater: 'スエズ運河・シナイ半島',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 200, cy: 72, label: 'スエズ運河（国有化・侵攻）', isMain: true },
      { cx: 198, cy: 75, label: 'カイロ（ナセル）', isMain: true },
      { cx: 204, cy: 65, label: 'テルアビブ（イスラエル）', ally: true },
      { cx: 162, cy: 28, label: '英国', ally: true },
      { cx: 170, cy: 42, label: 'フランス', ally: true },
    ],
  },
  {
    id: 'cuban-revolution',
    year: 1953, endYear: 1959,
    name: 'キューバ革命',
    region: 3, type: 'revolution', era: '20th-century',
    theater: 'キューバ全土',
    mapHighlight: 'north-america',
    markers: [
      { cx: 102, cy: 110, label: 'ハバナ（カストロ入城1959.1.8）', isMain: true },
      { cx: 105, cy: 115, label: 'シエラ・マエストラ（ゲリラ拠点）', isMain: true },
      { cx: 100, cy: 112, label: 'モンカダ兵舎（蜂起1953.7.26）' },
      { cx: 103, cy: 113, label: 'サンタクララ（ゲバラ最終戦1958.12）' },
      { cx: 110, cy: 65, label: '米国（バチスタ支援）', enemy: true },
    ],
  },
  {
    id: 'hungarian-uprising',
    year: 1956, endYear: 1956,
    name: 'ハンガリー動乱',
    region: 0, type: 'revolution', era: '20th-century',
    theater: 'ハンガリー全土',
    mapHighlight: 'eastern-europe',
    markers: [
      { cx: 188, cy: 32, label: 'ブダペスト（蜂起1956.10.23）', isMain: true },
      { cx: 190, cy: 33, label: '国会議事堂（虐殺）', isMain: true },
      { cx: 192, cy: 30, label: 'ソ連軍司令部' },
      { cx: 215, cy: 22, label: 'モスクワ（フルシチョフ）', enemy: true },
      { cx: 187, cy: 30, label: 'オーストリア（難民20万受入）', ally: true },
    ],
  },
  {
    id: 'algerian-war',
    year: 1954, endYear: 1962,
    name: 'アルジェリア戦争',
    region: 2, type: 'colonial', era: '20th-century',
    theater: 'アルジェリア全域',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 173, cy: 78, label: 'アルジェ（首都・市街戦1957）', isMain: true },
      { cx: 178, cy: 82, label: 'オレス山地（FLN拠点）' },
      { cx: 170, cy: 80, label: 'オラン（仏軍拠点）' },
      { cx: 170, cy: 42, label: 'パリ（仏本国）', enemy: true },
    ],
  },
  {
    id: 'guatemalan-civil-war',
    year: 1960, endYear: 1996,
    name: 'グアテマラ内戦',
    region: 3, type: 'revolution', era: '20th-century',
    theater: 'グアテマラ全土',
    mapHighlight: 'north-america',
    markers: [
      { cx: 82, cy: 110, label: 'グアテマラ・シティ（首都）', isMain: true },
      { cx: 85, cy: 113, label: 'マヤ高原（先住民虐殺地帯）', isMain: true },
      { cx: 80, cy: 115, label: 'イクシル地域（80年代焼土作戦）' },
      { cx: 110, cy: 65, label: '米国（CIAクーデター1954・軍事援助）', enemy: true },
      { cx: 102, cy: 110, label: 'キューバ（左翼ゲリラ支援）', ally: true },
    ],
  },
  {
    id: 'salvadoran-civil-war',
    year: 1979, endYear: 1992,
    name: 'エルサルバドル内戦',
    region: 3, type: 'revolution', era: '20th-century',
    theater: 'エルサルバドル全土',
    mapHighlight: 'north-america',
    markers: [
      { cx: 85, cy: 115, label: 'サンサルバドル（首都）', isMain: true },
      { cx: 88, cy: 118, label: 'エル・モソテ虐殺（1981.12）', isMain: true },
      { cx: 86, cy: 116, label: 'モラサン州（FMLN拠点）' },
      { cx: 110, cy: 65, label: '米国（年60億ドル軍事援助）', enemy: true },
      { cx: 92, cy: 125, label: 'マナグア（ニカラグア・FMLN支援）', ally: true },
    ],
  },
  {
    id: 'sino-vietnamese-war',
    year: 1979, endYear: 1979,
    name: '中越戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: '中越国境（ベトナム北部）',
    mapHighlight: 'southeast-asia',
    markers: [
      { cx: 271, cy: 60, label: 'ランソン（最大激戦）', isMain: true },
      { cx: 272, cy: 58, label: 'カオバン（侵攻地）' },
      { cx: 271, cy: 62, label: 'ハノイ（北越首都）', enemy: true },
      { cx: 268, cy: 50, label: '北京（鄧小平・「懲罰」）', ally: true },
      { cx: 215, cy: 22, label: 'モスクワ（越支援）', enemy: true },
    ],
  },
  {
    id: 'namibian-independence-war',
    year: 1966, endYear: 1990,
    name: 'ナミビア独立戦争',
    region: 2, type: 'colonial', era: '20th-century',
    theater: 'ナミビア（南西アフリカ）',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 175, cy: 165, label: 'ヴィントフック（首都・1990独立）', isMain: true },
      { cx: 178, cy: 160, label: 'カプリヴィ・オバンボランド（戦闘地）', isMain: true },
      { cx: 188, cy: 168, label: '南アフリカ（占領・アパルトヘイト）', enemy: true },
      { cx: 178, cy: 145, label: 'アンゴラ（SWAPO拠点）', ally: true },
      { cx: 180, cy: 162, label: 'クイトクアナヴァレ（1988決戦）' },
    ],
  },
  {
    id: 'first-nagorno-karabakh-war',
    year: 1988, endYear: 1994,
    name: '第一次ナゴルノ・カラバフ戦争',
    region: 0, type: 'war', era: '20th-century',
    theater: 'ナゴルノ・カラバフ',
    mapHighlight: 'eastern-europe',
    markers: [
      { cx: 215, cy: 50, label: 'ステパナケルト（NK首都）', isMain: true },
      { cx: 217, cy: 52, label: 'シューシャ（1992.5アルメニア占領）', isMain: true },
      { cx: 213, cy: 48, label: 'エレバン（アルメニア）', ally: true },
      { cx: 218, cy: 50, label: 'バクー（アゼルバイジャン）', enemy: true },
      { cx: 216, cy: 51, label: 'ホジャリ虐殺（1992.2、推計600人）' },
    ],
  },
  {
    id: 'lebanese-civil-war',
    year: 1975, endYear: 1990,
    name: 'レバノン内戦',
    region: 2, type: 'war', era: '20th-century',
    theater: 'レバノン全土',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 207, cy: 60, label: 'ベイルート（緑の境界線）', isMain: true },
      { cx: 206, cy: 62, label: 'サブラ・シャティーラ（虐殺1982）', isMain: true },
      { cx: 208, cy: 58, label: 'ダマスカス（シリア介入）', enemy: true },
      { cx: 204, cy: 65, label: 'テルアビブ（イスラエル侵攻1982）', enemy: true },
      { cx: 207, cy: 63, label: 'ティール（PLO拠点）' },
    ],
  },
  {
    id: 'angolan-civil-war',
    year: 1975, endYear: 2002,
    name: 'アンゴラ内戦',
    region: 2, type: 'war', era: '20th-century',
    theater: 'アンゴラ全土',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 178, cy: 145, label: 'ルアンダ（首都・MPLA政府）', isMain: true },
      { cx: 175, cy: 148, label: 'ウアンボ（UNITA本拠地）', enemy: true },
      { cx: 180, cy: 142, label: 'カビンダ（油田地帯）' },
      { cx: 215, cy: 22, label: 'ソ連・キューバ（MPLA支援）', ally: true },
      { cx: 110, cy: 65, label: '米・南アフリカ（UNITA支援）', enemy: true },
    ],
  },
  {
    id: 'peruvian-internal-conflict',
    year: 1980, endYear: 2000,
    name: 'ペルー内戦（センデロ・ルミノソ）',
    region: 3, type: 'revolution', era: '20th-century',
    theater: 'ペルー全土・アヤクーチョ州',
    mapHighlight: 'south-america',
    markers: [
      { cx: 88, cy: 220, label: 'リマ（首都・タルサ作戦1992）', isMain: true },
      { cx: 92, cy: 218, label: 'アヤクーチョ（蜂起地・センデロ拠点）', isMain: true },
      { cx: 90, cy: 222, label: 'チュスチ（最初の蜂起1980.5）' },
      { cx: 95, cy: 220, label: 'アンデス山脈農村（虐殺地帯）' },
      { cx: 88, cy: 215, label: 'グスマン逮捕（1992.9.12）' },
    ],
  },
  {
    id: 'iran-iraq-war',
    year: 1980, endYear: 1988,
    name: 'イラン・イラク戦争',
    region: 2, type: 'war', era: '20th-century',
    theater: 'イラン西部・イラク東部',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 213, cy: 65, label: 'バグダード（イラク首都）', isMain: true },
      { cx: 225, cy: 65, label: 'テヘラン（イラン首都）', enemy: true },
      { cx: 216, cy: 70, label: 'バスラ（南部激戦）' },
      { cx: 222, cy: 70, label: 'アバダン（油田・包囲）' },
      { cx: 219, cy: 67, label: 'ハラブジャ（化学兵器1988）', isMain: true },
    ],
  },
  {
    id: 'chechen-wars',
    year: 1994, endYear: 2009,
    name: 'チェチェン戦争',
    region: 0, type: 'war', era: '20th-century',
    theater: 'ロシア・チェチェン共和国',
    mapHighlight: 'eastern-europe',
    markers: [
      { cx: 215, cy: 50, label: 'グロズヌイ（壊滅的市街戦）', isMain: true },
      { cx: 218, cy: 52, label: 'カフカス山中（ゲリラ拠点）', isMain: true },
      { cx: 215, cy: 22, label: 'モスクワ（ロシア政府）', enemy: true },
      { cx: 220, cy: 50, label: 'ベスラン（学校占拠2004.9）' },
      { cx: 217, cy: 51, label: 'モスクワ劇場占拠（2002.10）' },
    ],
  },
  {
    id: 'rwandan-genocide',
    year: 1994, endYear: 1994,
    name: 'ルワンダ虐殺',
    region: 2, type: 'revolution', era: '20th-century',
    theater: 'ルワンダ全土',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 188, cy: 130, label: 'キガリ（首都・蜂起地）', isMain: true },
      { cx: 185, cy: 135, label: 'ニャマタ教会（虐殺現場）', isMain: true },
      { cx: 192, cy: 132, label: 'ブタレ（南部・激戦）' },
      { cx: 180, cy: 128, label: 'ゴマ（難民流出先）' },
    ],
  },
  {
    id: 'kosovo-war',
    year: 1998, endYear: 1999,
    name: 'コソボ紛争',
    region: 0, type: 'war', era: '20th-century',
    theater: 'コソボ自治州',
    mapHighlight: 'eastern-europe',
    markers: [
      { cx: 192, cy: 38, label: 'プリシュティナ（首都）', isMain: true },
      { cx: 190, cy: 40, label: 'ラチャク（虐殺1999.1）', isMain: true },
      { cx: 195, cy: 36, label: 'ベオグラード（NATO空爆）', enemy: true },
      { cx: 110, cy: 65, label: '米・NATO', ally: true },
    ],
  },
  {
    id: 'sri-lankan-civil-war',
    year: 1983, endYear: 2009,
    name: 'スリランカ内戦',
    region: 1, type: 'war', era: '20th-century',
    theater: 'スリランカ北部・東部',
    mapHighlight: 'south-asia',
    markers: [
      { cx: 252, cy: 115, label: 'コロンボ（首都・政府）', isMain: true },
      { cx: 256, cy: 110, label: 'ジャフナ（タミル・タイガー拠点）', isMain: true },
      { cx: 258, cy: 112, label: 'キリノチ（LTTE首都→陥落2009.1）' },
      { cx: 260, cy: 116, label: 'ムッライティーヴ（最終戦2009.5）' },
      { cx: 252, cy: 100, label: 'インド（IPKF介入1987-90）', ally: true },
    ],
  },
  {
    id: 'second-congo-war',
    year: 1998, endYear: 2003,
    name: '第二次コンゴ戦争（アフリカ大戦）',
    region: 2, type: 'war', era: '20th-century',
    theater: 'コンゴ民主共和国全土',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 188, cy: 140, label: 'キンシャサ（首都・カビラ政権）', isMain: true },
      { cx: 192, cy: 138, label: 'ゴマ・ブカヴ（東部反乱拠点）', isMain: true },
      { cx: 188, cy: 130, label: 'ルワンダ・ウガンダ（侵攻軍）', enemy: true },
      { cx: 178, cy: 145, label: 'アンゴラ・ジンバブエ（政府支援）', ally: true },
      { cx: 195, cy: 142, label: 'コンゴ東部（鉱物資源紛争地）' },
    ],
  },
  {
    id: 'somali-civil-war',
    year: 1991, endYear: 2025,
    name: 'ソマリア内戦',
    region: 2, type: 'war', era: '20th-century',
    theater: 'ソマリア全土・モガディシュ',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 210, cy: 120, label: 'モガディシュ（首都・ブラックホーク墜落1993.10）', isMain: true },
      { cx: 215, cy: 115, label: 'プントランド（北東部・自治）' },
      { cx: 207, cy: 118, label: 'ソマリランド（北西部・事実上独立）' },
      { cx: 208, cy: 122, label: 'キスマヨ（アル・シャバブ拠点）', isMain: true },
      { cx: 205, cy: 117, label: 'バイドア（飢饉中心地）' },
    ],
  },
  {
    id: 'kargil-war',
    year: 1999, endYear: 1999,
    name: 'カーギル戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: 'カシミール・カーギル地区',
    mapHighlight: 'south-asia',
    markers: [
      { cx: 252, cy: 88, label: 'カーギル（戦闘地）', isMain: true },
      { cx: 253, cy: 87, label: 'ドラス・ティーガ高地（標高5千m級）', isMain: true },
      { cx: 252, cy: 95, label: 'デリー（インド）', ally: true },
      { cx: 248, cy: 92, label: 'イスラマバード（パキスタン）', enemy: true },
      { cx: 251, cy: 89, label: 'スリナガル（前線基地）' },
    ],
  },
  {
    id: 'algerian-civil-war',
    year: 1991, endYear: 2002,
    name: 'アルジェリア内戦（暗黒の10年）',
    region: 2, type: 'revolution', era: '20th-century',
    theater: 'アルジェリア全土',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 173, cy: 78, label: 'アルジェ（首都・テロの中心）', isMain: true },
      { cx: 175, cy: 80, label: 'ベンタルハ虐殺（1997.9）', isMain: true },
      { cx: 178, cy: 82, label: 'オレス山地（GIAゲリラ）' },
      { cx: 170, cy: 76, label: 'オラン（FIS主要支持地）' },
      { cx: 170, cy: 42, label: 'パリ（仏：エール・フランス機ハイジャック1994）', enemy: true },
    ],
  },
  {
    id: 'bosnian-war',
    year: 1992, endYear: 1995,
    name: 'ボスニア戦争',
    region: 0, type: 'war', era: '20th-century',
    theater: 'ボスニア・ヘルツェゴビナ',
    mapHighlight: 'eastern-europe',
    markers: [
      { cx: 188, cy: 38, label: 'サラエボ（包囲1425日）', isMain: true },
      { cx: 190, cy: 36, label: 'スレブレニツァ（虐殺1995.7）', isMain: true },
      { cx: 186, cy: 40, label: 'モスタル（橋破壊1993）' },
      { cx: 192, cy: 35, label: 'ベオグラード（セルビア）', enemy: true },
    ],
  },
  {
    id: 'balkan-wars',
    year: 1912, endYear: 1913,
    name: 'バルカン戦争',
    region: 0, type: 'war', era: '20th-century',
    theater: 'バルカン半島',
    mapHighlight: 'eastern-europe',
    markers: [
      { cx: 192, cy: 38, label: 'ソフィア（ブルガリア）', isMain: true },
      { cx: 195, cy: 42, label: 'コンスタンティノープル直前（撤退）', isMain: true },
      { cx: 188, cy: 40, label: 'スコピエ（マケドニア争奪）' },
      { cx: 200, cy: 45, label: 'オスマン帝国（バルカン領土喪失）', enemy: true },
      { cx: 185, cy: 38, label: 'サラエボ（1914火種の地）' },
    ],
  },
  {
    id: 'irish-independence-war',
    year: 1919, endYear: 1921,
    name: 'アイルランド独立戦争',
    region: 0, type: 'colonial', era: '20th-century',
    theater: 'アイルランド全島',
    mapHighlight: 'europe',
    markers: [
      { cx: 153, cy: 25, label: 'ダブリン（蜂起・首都）', isMain: true },
      { cx: 150, cy: 30, label: 'コーク（IRA最大拠点）', isMain: true },
      { cx: 152, cy: 22, label: 'ベルファスト（北部・英連合派）', enemy: true },
      { cx: 162, cy: 28, label: 'ロンドン（英国）', enemy: true },
      { cx: 154, cy: 26, label: 'クロークパーク（血の日曜1920.11）' },
    ],
  },
  {
    id: 'mexican-revolution',
    year: 1910, endYear: 1920,
    name: 'メキシコ革命',
    region: 3, type: 'revolution', era: '20th-century',
    theater: 'メキシコ全土',
    mapHighlight: 'north-america',
    markers: [
      { cx: 80, cy: 90, label: 'メキシコ・シティ（首都・政権争奪）', isMain: true },
      { cx: 75, cy: 85, label: 'チワワ（パンチョ・ビリャ拠点）', isMain: true },
      { cx: 82, cy: 95, label: 'モレロス州（サパタ・農民革命）' },
      { cx: 110, cy: 65, label: '米国（ウィルソン・ピアース介入）', enemy: true },
      { cx: 78, cy: 95, label: 'シウダー・フアレス（マデロ蜂起1910.11）' },
    ],
  },
  {
    id: 'world-war-1',
    year: 1914, endYear: 1918,
    name: '第一次世界大戦',
    region: 0, type: 'war', era: '20th-century',
    theater: '西部戦線・東部戦線・中東・海洋',
    mapHighlight: 'europe',
    markers: [
      { cx: 185, cy: 34, label: 'サラエボ（暗殺・1914）', isMain: true },
      { cx: 173, cy: 35, label: 'ヴェルダン（1916消耗戦）', isMain: true },
      { cx: 167, cy: 33, label: 'ソンム川（1916・初日57470名死傷）' },
      { cx: 183, cy: 22, label: 'ベルリン（独）', enemy: true },
      { cx: 170, cy: 42, label: 'パリ（仏）', ally: true },
    ],
  },
  {
    id: 'russian-revolution',
    year: 1917, endYear: 1922,
    name: 'ロシア革命・内戦',
    region: 0, type: 'revolution', era: '20th-century',
    theater: 'ロシア全域',
    mapHighlight: 'eastern-europe',
    markers: [
      { cx: 205, cy: 18, label: 'ペトログラード（二月・十月革命）', isMain: true },
      { cx: 215, cy: 22, label: 'モスクワ（首都移転）' },
      { cx: 218, cy: 32, label: 'ツァリーツィン（内戦激戦）' },
      { cx: 207, cy: 38, label: 'エカテリンブルク（皇帝処刑）' },
    ],
  },
  {
    id: 'second-italo-ethiopian-war',
    year: 1935, endYear: 1936,
    name: '第二次エチオピア戦争',
    region: 2, type: 'colonial', era: '20th-century',
    theater: 'エチオピア（アビシニア）',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 200, cy: 118, label: 'アディスアベバ（占領1936.5）', isMain: true },
      { cx: 198, cy: 115, label: 'マイチャウ（最終戦・毒ガス使用1936.3）', isMain: true },
      { cx: 195, cy: 110, label: 'エリトリア（伊植民地・出撃基地）' },
      { cx: 175, cy: 42, label: 'ローマ（ムッソリーニ）', enemy: true },
      { cx: 162, cy: 28, label: '英・仏（国際連盟制裁失敗）', ally: true },
    ],
  },
  {
    id: 'spanish-civil-war',
    year: 1936, endYear: 1939,
    name: 'スペイン内戦',
    region: 0, type: 'revolution', era: '20th-century',
    theater: 'スペイン全域',
    mapHighlight: 'europe',
    markers: [
      { cx: 160, cy: 50, label: 'マドリード（首都・共和国側）', isMain: true },
      { cx: 158, cy: 46, label: 'ゲルニカ（独空軍爆撃1937）', isMain: true },
      { cx: 162, cy: 52, label: 'バルセロナ（陥落1939）' },
      { cx: 183, cy: 22, label: 'ベルリン（独・支援）', ally: false, enemy: true },
      { cx: 175, cy: 42, label: 'ローマ（伊・支援）', enemy: true },
    ],
  },
  {
    id: 'winter-war',
    year: 1939, endYear: 1940,
    name: '冬戦争（ソ連・フィンランド戦争）',
    region: 0, type: 'war', era: '20th-century',
    theater: 'カレリア地峡・フィンランド東部',
    mapHighlight: 'eastern-europe',
    markers: [
      { cx: 195, cy: 18, label: 'ヘルシンキ（フィンランド）', isMain: true },
      { cx: 200, cy: 20, label: 'マンネルヘイム線（防衛線）', isMain: true },
      { cx: 205, cy: 18, label: 'レニングラード（ソ連目的地）', enemy: true },
      { cx: 198, cy: 22, label: 'スオムッサルミ（包囲撃破）' },
      { cx: 215, cy: 22, label: 'モスクワ（スターリン）', enemy: true },
    ],
  },
  {
    id: 'world-war-2-europe',
    year: 1939, endYear: 1945,
    name: '第二次世界大戦（欧州）',
    region: 0, type: 'war', era: '20th-century',
    theater: 'ヨーロッパ全域・北アフリカ',
    mapHighlight: 'europe',
    markers: [
      { cx: 183, cy: 22, label: 'ベルリン（独・陥落1945）', isMain: true },
      { cx: 218, cy: 32, label: 'スターリングラード（1942-43転換点）', isMain: true },
      { cx: 164, cy: 32, label: 'ノルマンディー（Dデイ1944）', isMain: true },
      { cx: 170, cy: 42, label: 'パリ（解放1944）', ally: true },
      { cx: 186, cy: 30, label: 'アウシュヴィッツ（ホロコースト）' },
    ],
  },
  {
    id: 'pacific-war',
    year: 1941, endYear: 1945,
    name: '太平洋戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: '太平洋・東アジア・東南アジア',
    mapHighlight: 'east-asia',
    markers: [
      { cx: 290, cy: 48, label: '東京（大本営）', enemy: true },
      { cx: 295, cy: 60, label: 'パールハーバー奇襲（1941）', isMain: true },
      { cx: 290, cy: 55, label: 'ミッドウェー海戦（1942転換）', isMain: true },
      { cx: 285, cy: 62, label: '沖縄（1945・民間人12万死）' },
      { cx: 287, cy: 50, label: '広島・長崎（原爆1945）', isMain: true },
    ],
  },
  {
    id: 'korean-war',
    year: 1950, endYear: 1953,
    name: '朝鮮戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: '朝鮮半島全域',
    mapHighlight: 'east-asia',
    markers: [
      { cx: 280, cy: 45, label: '平壌（北朝鮮首都）', enemy: true },
      { cx: 282, cy: 48, label: 'ソウル（三度陥落と奪回）', isMain: true },
      { cx: 281, cy: 47, label: '仁川（マッカーサー上陸1950）' },
      { cx: 268, cy: 42, label: '中国（1950年秋介入）', enemy: true },
      { cx: 110, cy: 65, label: '米国（国連軍主力）', ally: true },
    ],
  },
  {
    id: 'second-indo-pakistani-war',
    year: 1965, endYear: 1965,
    name: '第二次印パ戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: 'カシミール・パンジャブ国境',
    mapHighlight: 'south-asia',
    markers: [
      { cx: 252, cy: 88, label: 'カシミール（潜入作戦・チョットラ作戦）', isMain: true },
      { cx: 250, cy: 92, label: 'ラホール戦線（印軍越境）', isMain: true },
      { cx: 252, cy: 95, label: 'デリー（印・シャストリ首相）', ally: true },
      { cx: 248, cy: 92, label: 'カラチ（パ・アユーブ・カーン）', enemy: true },
      { cx: 215, cy: 22, label: 'タシケント（停戦合意）' },
    ],
  },
  {
    id: 'vietnam-war',
    year: 1955, endYear: 1975,
    name: 'ベトナム戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: 'ベトナム・ラオス・カンボジア',
    mapHighlight: 'southeast-asia',
    markers: [
      { cx: 271, cy: 62, label: 'ハノイ（北ベトナム）', enemy: true },
      { cx: 273, cy: 75, label: 'サイゴン（南ベトナム首都・陥落1975）', isMain: true },
      { cx: 268, cy: 68, label: 'ケサン基地（激戦1968）' },
      { cx: 270, cy: 70, label: 'ホーチミンルート（補給路）' },
      { cx: 110, cy: 65, label: '米国（50万人派兵）', ally: true },
    ],
  },
  {
    id: 'bangladesh-liberation-war',
    year: 1971, endYear: 1971,
    name: 'バングラデシュ独立戦争（第三次印パ戦争）',
    region: 1, type: 'revolution', era: '20th-century',
    theater: '東パキスタン（現バングラデシュ）',
    mapHighlight: 'south-asia',
    markers: [
      { cx: 262, cy: 100, label: 'ダッカ（首都・占領→解放）', isMain: true },
      { cx: 252, cy: 98, label: 'デリー（インド軍介入）', ally: true },
      { cx: 248, cy: 92, label: 'カラチ（西パキスタン）', enemy: true },
      { cx: 260, cy: 102, label: 'チッタゴン（虐殺現場）' },
      { cx: 215, cy: 22, label: 'モスクワ（印支援）', ally: true },
    ],
  },
  {
    id: 'cambodian-genocide',
    year: 1975, endYear: 1979,
    name: 'カンボジア大虐殺（クメール・ルージュ統治）',
    region: 1, type: 'revolution', era: '20th-century',
    theater: 'カンボジア全土',
    mapHighlight: 'southeast-asia',
    markers: [
      { cx: 273, cy: 78, label: 'プノンペン（強制疎開1975.4.17）', isMain: true },
      { cx: 274, cy: 80, label: 'トゥール・スレン刑務所（S-21）', isMain: true },
      { cx: 275, cy: 82, label: 'チュンエク（キリングフィールド）' },
      { cx: 271, cy: 62, label: 'ベトナム（侵攻1978.12）', ally: true },
      { cx: 268, cy: 50, label: '中国（クメール支援）', enemy: true },
    ],
  },
  {
    id: 'falklands-war',
    year: 1982, endYear: 1982,
    name: 'フォークランド紛争',
    region: 3, type: 'war', era: '20th-century',
    theater: '南大西洋・フォークランド諸島',
    mapHighlight: 'south-america',
    markers: [
      { cx: 105, cy: 240, label: 'ポート・スタンリー（諸島首都）', isMain: true },
      { cx: 88, cy: 235, label: 'ブエノスアイレス（亜）', enemy: true },
      { cx: 162, cy: 28, label: 'ロンドン（英・サッチャー）', ally: true },
      { cx: 102, cy: 232, label: 'グースグリーン（陸上戦）' },
      { cx: 100, cy: 245, label: 'ベルグラノ号撃沈（1982.5）' },
    ],
  },
  {
    id: 'sino-indian-war',
    year: 1962, endYear: 1962,
    name: '中印戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: 'ヒマラヤ国境（ラダック・アルナチャル・プラデシュ）',
    mapHighlight: 'south-asia',
    markers: [
      { cx: 258, cy: 85, label: 'アクサイチン（西部戦線）', isMain: true },
      { cx: 263, cy: 88, label: 'タワン・ボムディラ（東部戦線・1962.10-11）', isMain: true },
      { cx: 268, cy: 50, label: '北京（毛沢東）', enemy: true },
      { cx: 252, cy: 95, label: 'デリー（ネルー）', ally: true },
      { cx: 215, cy: 22, label: 'ソ連（中立傾向、印に間接支援）' },
    ],
  },
  {
    id: 'biafra-war',
    year: 1967, endYear: 1970,
    name: 'ナイジェリア・ビアフラ戦争',
    region: 2, type: 'revolution', era: '20th-century',
    theater: 'ナイジェリア東部（ビアフラ）',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 175, cy: 130, label: 'エヌグ→アバ（ビアフラ首都変遷）', isMain: true },
      { cx: 170, cy: 132, label: 'ラゴス（ナイジェリア連邦首都）', enemy: true },
      { cx: 178, cy: 132, label: 'ポートハーコート（陥落1968.5）' },
      { cx: 175, cy: 134, label: 'ウムアヒア（最後の首都・飢饉中心）', isMain: true },
      { cx: 162, cy: 28, label: '英国（連邦支援）', enemy: true },
    ],
  },
  {
    id: 'six-day-war',
    year: 1967, endYear: 1967,
    name: '第三次中東戦争（六日間戦争）',
    region: 2, type: 'war', era: '20th-century',
    theater: 'シナイ半島・ヨルダン川西岸・ゴラン高原',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 204, cy: 65, label: 'テルアビブ（イスラエル）', isMain: true },
      { cx: 205, cy: 60, label: 'エルサレム（東エルサレム占領）', isMain: true },
      { cx: 202, cy: 72, label: 'シナイ半島（エジプト軍撃破）' },
      { cx: 208, cy: 58, label: 'ゴラン高原（シリアから奪取）' },
      { cx: 200, cy: 65, label: 'ヨルダン川西岸（占領）' },
    ],
  },
  {
    id: 'yom-kippur-war',
    year: 1973, endYear: 1973,
    name: '第四次中東戦争（ヨム・キプール戦争）',
    region: 2, type: 'war', era: '20th-century',
    theater: 'シナイ半島・ゴラン高原',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 204, cy: 65, label: 'テルアビブ（イスラエル）', isMain: true },
      { cx: 202, cy: 72, label: 'スエズ運河（エジプト渡河）', isMain: true },
      { cx: 208, cy: 58, label: 'ゴラン高原（シリア攻勢）' },
      { cx: 198, cy: 75, label: 'カイロ（エジプト）', enemy: true },
      { cx: 210, cy: 55, label: 'ダマスカス（シリア）', enemy: true },
    ],
  },
  {
    id: 'iranian-revolution',
    year: 1978, endYear: 1979,
    name: 'イラン革命',
    region: 2, type: 'revolution', era: '20th-century',
    theater: 'イラン全土',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 225, cy: 65, label: 'テヘラン（首都・革命中心）', isMain: true },
      { cx: 224, cy: 62, label: 'コム（ホメイニ拠点）', isMain: true },
      { cx: 226, cy: 70, label: 'タブリーズ（蜂起発端）' },
      { cx: 110, cy: 65, label: '米国（パーレビ亡命受入）', enemy: true },
      { cx: 170, cy: 42, label: 'パリ（ホメイニ亡命地）' },
    ],
  },
  {
    id: 'east-timor-occupation',
    year: 1975, endYear: 1999,
    name: '東ティモール独立闘争',
    region: 1, type: 'colonial', era: '20th-century',
    theater: '東ティモール',
    mapHighlight: 'southeast-asia',
    markers: [
      { cx: 295, cy: 105, label: 'ディリ（首都・侵攻1975.12.7）', isMain: true },
      { cx: 297, cy: 108, label: 'バリボ（豪州ジャーナリスト殺害）' },
      { cx: 298, cy: 110, label: 'サンタクルス墓地（虐殺1991.11）', isMain: true },
      { cx: 290, cy: 102, label: 'ジャカルタ（インドネシア政府）', enemy: true },
      { cx: 290, cy: 110, label: '住民投票（1999.8.30）' },
    ],
  },
  {
    id: 'nicaraguan-revolution',
    year: 1978, endYear: 1979,
    name: 'ニカラグア・サンディニスタ革命',
    region: 3, type: 'revolution', era: '20th-century',
    theater: 'ニカラグア全土',
    mapHighlight: 'north-america',
    markers: [
      { cx: 92, cy: 125, label: 'マナグア（首都・1979.7.19入城）', isMain: true },
      { cx: 95, cy: 122, label: 'マタガルパ・エステリ（最終攻勢）', isMain: true },
      { cx: 90, cy: 128, label: 'グラナダ（ソモサ要塞）' },
      { cx: 88, cy: 130, label: 'サンディニスタ（FSLN）拠点' },
      { cx: 110, cy: 65, label: '米国（ソモサ→コントラ支援）', enemy: true },
    ],
  },
  {
    id: 'colombian-conflict',
    year: 1964, endYear: 2016,
    name: 'コロンビア内戦（FARC戦争）',
    region: 3, type: 'revolution', era: '20th-century',
    theater: 'コロンビア全土',
    mapHighlight: 'south-america',
    markers: [
      { cx: 92, cy: 195, label: 'ボゴタ（首都・2016和平合意）', isMain: true },
      { cx: 88, cy: 200, label: 'マルケタリア（FARC発祥地1964）', isMain: true },
      { cx: 85, cy: 198, label: 'マグダレナ・メディオ（パラ拠点）' },
      { cx: 90, cy: 202, label: 'カリ・メデジン（麻薬カルテル拠点）' },
      { cx: 110, cy: 65, label: '米国（プラン・コロンビア2000〜）', ally: true },
    ],
  },
  {
    id: 'soviet-afghan-war',
    year: 1979, endYear: 1989,
    name: 'ソ連・アフガニスタン戦争',
    region: 2, type: 'war', era: '20th-century',
    theater: 'アフガニスタン全域',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 237, cy: 58, label: 'カブール（首都・ソ連占領）', isMain: true },
      { cx: 235, cy: 55, label: 'サランパス（補給路）' },
      { cx: 233, cy: 60, label: 'カンダハル（ムジャヒディーン拠点）' },
      { cx: 215, cy: 22, label: 'モスクワ（ソ連）', enemy: true },
      { cx: 110, cy: 65, label: '米（CIA・武器支援）', ally: true },
    ],
  },
  {
    id: 'gulf-war',
    year: 1990, endYear: 1991,
    name: '湾岸戦争',
    region: 2, type: 'war', era: '20th-century',
    theater: 'クウェート・イラク南部',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 218, cy: 68, label: 'クウェート（イラクが侵攻）', isMain: true },
      { cx: 213, cy: 65, label: 'バグダード（空爆）', enemy: true },
      { cx: 216, cy: 70, label: 'バスラ（地上戦）' },
      { cx: 110, cy: 65, label: '米国（多国籍軍主力）', ally: true },
      { cx: 216, cy: 72, label: 'サウジアラビア（出撃基地）', ally: true },
    ],
  },

  /* ─────────────────── 現代（2000-） ─────────────────── */

  {
    id: 'afghanistan-war',
    year: 2001, endYear: 2021,
    name: 'アフガニスタン戦争',
    region: 2, type: 'war', era: 'contemporary',
    theater: 'アフガニスタン全域',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 237, cy: 58, label: 'カブール（首都・タリバン陥落→奪還）', isMain: true },
      { cx: 233, cy: 60, label: 'カンダハル（タリバン本拠）', enemy: true },
      { cx: 240, cy: 56, label: 'トラボラ（ビンラディン逃亡）' },
      { cx: 110, cy: 65, label: '米国・NATO（主力）', ally: true },
      { cx: 235, cy: 55, label: 'ヘルマンド州（激戦区）' },
    ],
  },
  {
    id: 'iraq-war',
    year: 2003, endYear: 2011,
    name: 'イラク戦争',
    region: 2, type: 'war', era: 'contemporary',
    theater: 'イラク全域',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 213, cy: 65, label: 'バグダード（陥落2003.4.9）', isMain: true },
      { cx: 212, cy: 60, label: 'ティクリート（フセイン拘束）' },
      { cx: 214, cy: 62, label: 'ファルージャ（市街戦2004）', isMain: true },
      { cx: 216, cy: 68, label: 'バスラ（英軍担当）' },
      { cx: 110, cy: 65, label: '米・英（有志連合）', ally: true },
    ],
  },
  {
    id: 'boko-haram-insurgency',
    year: 2009, endYear: 2025,
    name: 'ボコ・ハラム反乱',
    region: 2, type: 'revolution', era: 'contemporary',
    theater: 'ナイジェリア北東部・チャド湖周辺',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 175, cy: 125, label: 'マイドゥグリ（ボコ・ハラム発祥地）', isMain: true },
      { cx: 178, cy: 122, label: 'チボク（女子生徒276人誘拐2014.4）', isMain: true },
      { cx: 173, cy: 128, label: 'サンビサ森林（ジハーディスト拠点）' },
      { cx: 180, cy: 120, label: 'チャド湖周辺（ISWAP支配地）' },
      { cx: 170, cy: 132, label: 'アブジャ（ナイジェリア連邦首都）', enemy: true },
    ],
  },
  {
    id: 'libyan-civil-war',
    year: 2011, endYear: 2011,
    name: 'リビア内戦（カダフィ崩壊）',
    region: 2, type: 'revolution', era: 'contemporary',
    theater: 'リビア全土',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 178, cy: 80, label: 'トリポリ（首都・カダフィ拠点）', isMain: true },
      { cx: 188, cy: 78, label: 'ベンガジ（蜂起地）', isMain: true },
      { cx: 183, cy: 82, label: 'シルテ（カダフィ殺害2011.10.20）' },
      { cx: 180, cy: 78, label: 'ミスラタ（包囲戦）' },
      { cx: 110, cy: 65, label: 'NATO（空爆）', ally: true },
    ],
  },
  {
    id: 'yemen-civil-war',
    year: 2014, endYear: 2025,
    name: 'イエメン内戦',
    region: 2, type: 'war', era: 'contemporary',
    theater: 'イエメン全土・紅海',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 218, cy: 85, label: 'サナア（フーシ派制圧2014.9）', isMain: true },
      { cx: 220, cy: 88, label: 'アデン（暫定政府）', enemy: true },
      { cx: 215, cy: 87, label: 'ホデイダ（紅海港・激戦）', isMain: true },
      { cx: 216, cy: 72, label: 'リヤド（サウジ主導連合）', enemy: true },
      { cx: 225, cy: 65, label: 'イラン（フーシ支援）', ally: true },
    ],
  },
  {
    id: 'nagorno-karabakh-2020',
    year: 2020, endYear: 2020,
    name: '第二次ナゴルノ・カラバフ戦争',
    region: 0, type: 'war', era: 'contemporary',
    theater: 'ナゴルノ・カラバフ',
    mapHighlight: 'eastern-europe',
    markers: [
      { cx: 215, cy: 50, label: 'ステパナケルト（首都・砲撃）', isMain: true },
      { cx: 217, cy: 52, label: 'シューシャ（陥落11.8）', isMain: true },
      { cx: 213, cy: 48, label: 'エレバン（アルメニア）', enemy: true },
      { cx: 218, cy: 50, label: 'バクー（アゼルバイジャン）', ally: true },
      { cx: 210, cy: 45, label: 'アンカラ（トルコ・ドローン提供）', ally: true },
    ],
  },
  {
    id: 'south-sudan-civil-war',
    year: 2013, endYear: 2025,
    name: '南スーダン内戦',
    region: 2, type: 'war', era: 'contemporary',
    theater: '南スーダン',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 200, cy: 115, label: 'ジュバ（首都・キール政権）', isMain: true },
      { cx: 198, cy: 117, label: 'ボル・マラカル（マチャール拠点）', isMain: true },
      { cx: 202, cy: 113, label: 'ベンティウ（油田地帯）' },
      { cx: 195, cy: 118, label: '北部ハルツーム（旧スーダン政府）', enemy: true },
      { cx: 110, cy: 65, label: '米国（独立支援→失望）', ally: true },
    ],
  },
  {
    id: 'mali-conflict',
    year: 2012, endYear: 2025,
    name: 'マリ内戦（サヘル危機）',
    region: 2, type: 'war', era: 'contemporary',
    theater: 'マリ北部・サヘル全域',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 165, cy: 100, label: 'バマコ（首都・連続クーデター）', isMain: true },
      { cx: 170, cy: 95, label: 'トンブクトゥ（占領→奪還2013.1）', isMain: true },
      { cx: 168, cy: 92, label: 'ガオ・キダル（トゥアレグ・ジハーディスト拠点）' },
      { cx: 170, cy: 42, label: 'パリ（仏軍セルバル作戦2013-22）', ally: true },
      { cx: 215, cy: 22, label: 'モスクワ（ワグネル進出2021〜）', enemy: true },
    ],
  },
  {
    id: 'central-african-civil-war',
    year: 2012, endYear: 2025,
    name: '中央アフリカ内戦',
    region: 2, type: 'war', era: 'contemporary',
    theater: '中央アフリカ共和国',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 185, cy: 130, label: 'バンギ（首都）', isMain: true },
      { cx: 188, cy: 128, label: '北部（セレカ・ムスリム連合拠点）', isMain: true },
      { cx: 183, cy: 132, label: '南西部（アンチ・バラカ・キリスト教民兵）' },
      { cx: 215, cy: 22, label: 'ロシア（ワグネル進出2018〜）', ally: true },
      { cx: 170, cy: 42, label: 'パリ（仏軍サンガリス2013-16）', ally: true },
    ],
  },
  {
    id: 'syrian-civil-war',
    year: 2011, endYear: 2024,
    name: 'シリア内戦',
    region: 2, type: 'revolution', era: 'contemporary',
    theater: 'シリア全域',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 208, cy: 58, label: 'ダマスカス（首都・政府側）', isMain: true },
      { cx: 207, cy: 55, label: 'ホムス（反政府勢力拠点）' },
      { cx: 209, cy: 52, label: 'アレッポ（最大激戦・2016陥落）', isMain: true },
      { cx: 211, cy: 57, label: 'ラッカ（IS首都→2017解放）' },
      { cx: 215, cy: 22, label: 'ロシア（政府支援）', ally: true },
    ],
  },
  {
    id: 'myanmar-civil-war',
    year: 2021, endYear: 2025,
    name: 'ミャンマー内戦（クーデター後）',
    region: 1, type: 'revolution', era: 'contemporary',
    theater: 'ミャンマー全土',
    mapHighlight: 'southeast-asia',
    markers: [
      { cx: 268, cy: 65, label: 'ネピドー（軍政首都）', isMain: true },
      { cx: 270, cy: 68, label: 'ヤンゴン（旧首都・抗議中心）' },
      { cx: 272, cy: 60, label: 'カチン州・カレン州（少数民族抵抗）', isMain: true },
      { cx: 266, cy: 70, label: 'PDF（人民防衛軍）拠点' },
      { cx: 268, cy: 50, label: '中国（軍政支援）', enemy: true },
    ],
  },
  {
    id: 'tigray-war',
    year: 2020, endYear: 2022,
    name: 'ティグレ戦争',
    region: 2, type: 'war', era: 'contemporary',
    theater: 'エチオピア北部・ティグレ州',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 198, cy: 115, label: 'メケレ（ティグレ州都）', isMain: true },
      { cx: 200, cy: 118, label: 'アディスアベバ（連邦政府）', enemy: true },
      { cx: 196, cy: 113, label: 'アクスム（古代王都・虐殺）', isMain: true },
      { cx: 195, cy: 110, label: 'エリトリア（連邦軍と共同作戦）', ally: true },
      { cx: 199, cy: 116, label: 'デバルク（連邦軍進撃ライン）' },
    ],
  },
  {
    id: 'sudan-civil-war-2023',
    year: 2023, endYear: 2025,
    name: 'スーダン内戦',
    region: 2, type: 'war', era: 'contemporary',
    theater: 'スーダン全土',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 200, cy: 110, label: 'ハルツーム（首都・激戦）', isMain: true },
      { cx: 195, cy: 115, label: 'ダルフール（虐殺再発）', isMain: true },
      { cx: 198, cy: 108, label: 'オムドゥルマン（双子都市）' },
      { cx: 205, cy: 112, label: 'ポートスーダン（暫定首都）' },
      { cx: 216, cy: 72, label: 'UAE（RSF支援疑惑）', enemy: true },
    ],
  },
  {
    id: 'gaza-war',
    year: 2023, endYear: 2025,
    name: 'ガザ戦争',
    region: 2, type: 'war', era: 'contemporary',
    theater: 'ガザ地区・イスラエル南部',
    mapHighlight: 'middle-east',
    markers: [
      { cx: 204, cy: 65, label: 'テルアビブ（イスラエル）', isMain: true },
      { cx: 203, cy: 67, label: 'ガザ市（北部・地上侵攻）', isMain: true },
      { cx: 202, cy: 69, label: 'ハーンユーニス・ラファ（南部）' },
      { cx: 205, cy: 60, label: 'エルサレム' },
      { cx: 225, cy: 65, label: 'テヘラン（イラン・支援）', enemy: true },
    ],
  },
  {
    id: 'ukraine-war',
    year: 2022, endYear: 2025,
    name: 'ロシア・ウクライナ戦争',
    region: 0, type: 'war', era: 'contemporary',
    theater: 'ウクライナ全域',
    mapHighlight: 'eastern-europe',
    markers: [
      { cx: 200, cy: 28, label: 'キーウ（首都・初期攻防）', isMain: true },
      { cx: 205, cy: 35, label: 'マリウポリ（包囲・陥落2022.5）', isMain: true },
      { cx: 204, cy: 32, label: 'バフムート（最長激戦）' },
      { cx: 203, cy: 34, label: 'ヘルソン（解放2022.11）' },
      { cx: 215, cy: 22, label: 'モスクワ（ロシア）', enemy: true },
    ],
  },
];

export const REGIONS = ['欧州', 'アジア', '中東・アフリカ', '南北米'] as const;
