import { War, EraId } from './types';
import { WARS_PREHISTORIC } from './wars-prehistoric';
import { WARS_ANCIENT } from './wars-ancient';
import { WARS_ANCIENT_EXTRA } from './wars-ancient-extra';
import { WARS_MEDIEVAL } from './wars-medieval';
import { WARS_MEDIEVAL_EXTRA } from './wars-medieval-extra';
import { WARS_RENAISSANCE } from './wars-renaissance';

export const ERA_CONFIG: Record<EraId, { label: string; start: number; end: number }> = {
  'prehistoric':    { label: '先史〜古代文明（〜BC700）', start: -3000, end: -700 },
  'ancient':        { label: '古代（BC700〜AD500）', start: -700, end: 500 },
  'medieval':       { label: '中世（500〜1450）', start: 500,  end: 1450 },
  'renaissance':    { label: '近世初期（1450〜1700）', start: 1450, end: 1700 },
  'early-modern':   { label: '近世（1700〜）',   start: 1700, end: 1899 },
  '20th-century':   { label: '20世紀',           start: 1900, end: 1999 },
  'contemporary':   { label: '現代',             start: 2000, end: 2030 },
};

const _WARS_INLINE: War[] = [

  /* ─────────────────── 近世（1700-1899） ─────────────────── */

  {
    id: 'great-northern-war',
    year: 1700, endYear: 1721,
    name: '大北方戦争',
    region: 0, type: 'war', era: 'early-modern',
    theater: '北欧・バルト海・東欧',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [18.1, 59.3], label: 'ストックホルム（スウェーデン・カール12世）', isMain: true },
      { coordinates: [37.6, 55.8], label: 'モスクワ（ロシア・ピョートル大帝）', enemy: true },
      { coordinates: [28.2, 59.4], label: 'ナルヴァ（1700年初戦・スウェーデン勝利）' },
      { coordinates: [34.5, 49.6], label: 'ポルタヴァ（1709年決戦・ロシア勝利）', isMain: true },
      { coordinates: [22.0, 60.8], label: 'ニスタット（1721年講和条約）' },
    ],
    weight: 2,
    tags: ['帝国衰退', 'ナショナリズム', '誤算・誤認知'],
    ideologies: ['絶対王政', '重商主義'],
    causes: [],
    influences: ['seven-years-war'],
  },
  {
    id: 'war-of-spanish-succession',
    year: 1701, endYear: 1714,
    name: 'スペイン継承戦争',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'ヨーロッパ全域・北米（アン女王戦争）',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [-3.7, 40.4], label: 'マドリード（フェリペ5世）', isMain: true },
      { coordinates: [2.3, 48.9], label: 'フランス（ルイ14世）', enemy: true },
      { coordinates: [-0.1, 51.5], label: '英国・蘭・墺（同盟）', ally: true },
      { coordinates: [10.7, 48.5], label: 'ブレンハイム（1704決戦）', isMain: true },
      { coordinates: [5.1, 52.1], label: 'ユトレヒト（条約1713）' },
    ],
    weight: 2,
    tags: ['帝国衰退', '同盟暴走', '誤算・誤認知', '王朝継承'],
    ideologies: ['絶対王政', '勢力均衡'],
    causes: [],
    influences: ['war-of-austrian-succession'],
  },
  {
    id: 'war-of-polish-succession',
    year: 1733, endYear: 1738,
    name: 'ポーランド継承戦争',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'ポーランド・イタリア半島・ライン川流域',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [21.0, 52.2], label: 'ワルシャワ（選挙地・スタニスワフ1世支持）', isMain: true },
      { coordinates: [16.4, 48.2], label: 'ウィーン（オーストリア・ハプスブルク）', enemy: true },
      { coordinates: [2.3, 48.9], label: 'パリ（フランス・ルイ15世）', ally: true },
      { coordinates: [30.3, 59.9], label: 'サンクトペテルブルク（ロシア）', enemy: true },
      { coordinates: [18.6, 54.4], label: 'ダンツィヒ包囲戦（1734年）', isMain: true },
    ],
    weight: 1,
    tags: ['帝国衰退', '同盟暴走', '指導者個人要因', '王朝継承'],
    ideologies: ['絶対王政', '勢力均衡'],
    causes: ['war-of-spanish-succession'],
    influences: ['war-of-austrian-succession'],
  },
  {
    id: 'war-of-austrian-succession',
    year: 1740, endYear: 1748,
    name: 'オーストリア継承戦争',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'ヨーロッパ全域・北米（ジョージ王戦争）・インド',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [16.4, 48.2], label: 'ウィーン（マリア・テレジア）', isMain: true },
      { coordinates: [13.4, 52.5], label: 'ベルリン（フリードリヒ2世・プロイセン）', enemy: true },
      { coordinates: [17.0, 51.1], label: 'シュレジエン（プロイセン侵攻・1740.12）', isMain: true },
      { coordinates: [2.3, 48.9], label: 'フランス（対墺同盟）', enemy: true },
      { coordinates: [3.5, 50.6], label: 'フォントノワ（1745決戦）' },
    ],
    cotenLinks: [
      { title: 'フリードリヒ大王編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E3%83%95%E3%83%AA%E3%83%BC%E3%83%89%E3%83%AA%E3%83%92%E5%A4%A7%E7%8E%8B' },
    ],
    weight: 2,
    tags: ['帝国衰退', '同盟暴走', '誤算・誤認知', '王朝継承'],
    ideologies: ['絶対王政', '勢力均衡'],
    causes: ['war-of-polish-succession'],
    influences: ['seven-years-war'],
  },
  {
    id: 'russo-turkish-war-1768',
    year: 1768, endYear: 1774,
    name: '露土戦争（1768-1774）',
    region: 0, type: 'war', era: 'early-modern',
    theater: '黒海北岸・バルカン半島・エーゲ海',
    mapHighlight: 'eastern-europe',
    markers: [
      { coordinates: [30.3, 59.9], label: 'サンクトペテルブルク（ロシア・エカチェリーナ2世）', isMain: true },
      { coordinates: [28.9, 41.0], label: 'コンスタンティノープル（オスマン帝国）', enemy: true },
      { coordinates: [28.2, 45.9], label: 'カグル（1770年ルミャンツェフ勝利）', isMain: true },
      { coordinates: [26.4, 38.3], label: 'チェスメ海戦（1770年ロシア艦隊勝利）', isMain: true },
      { coordinates: [27.9, 43.9], label: 'キュチュク・カイナルジャ（1774年条約）' },
    ],
    cotenLinks: [
      { title: 'オスマン帝国編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E3%82%AA%E3%82%B9%E3%83%9E%E3%83%B3%E5%B8%9D%E5%9B%BD' },
    ],
    weight: 2,
    tags: ['帝国衰退', '資源争奪', '宗教対立'],
    ideologies: ['絶対王政', '汎スラブ主義', '正教会'],
    causes: [],
    influences: ['greek-independence-war', 'russo-turkish-war-1877'],
  },
  {
    id: 'seven-years-war',
    year: 1756, endYear: 1763,
    name: '七年戦争',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'ヨーロッパ・北米・インド・カリブ海',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [13.4, 52.5], label: 'プロイセン（ベルリン）', isMain: true },
      { coordinates: [16.4, 48.2], label: 'オーストリア（ウィーン）', enemy: true },
      { coordinates: [2.3, 48.9], label: 'フランス', enemy: true },
      { coordinates: [37.6, 55.8], label: 'ロシア', enemy: true },
      { coordinates: [-0.1, 51.5], label: '英国（同盟）', ally: true },
    ],
    cotenLinks: [
      { title: 'フリードリヒ大王編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E3%83%95%E3%83%AA%E3%83%BC%E3%83%89%E3%83%AA%E3%83%92%E5%A4%A7%E7%8E%8B' },
    ],
    weight: 3,
    tags: ['同盟暴走', '資源争奪', '帝国衰退'],
    ideologies: ['絶対王政', '重商主義'],
    causes: ['war-of-austrian-succession'],
    influences: ['american-independence', 'french-revolution'],
  },
  {
    id: 'american-independence',
    year: 1775, endYear: 1783,
    name: 'アメリカ独立戦争',
    region: 3, type: 'war', era: 'early-modern',
    theater: '北アメリカ東海岸',
    mapHighlight: 'north-america',
    markers: [
      { coordinates: [-71.1, 42.4], label: 'ボストン' },
      { coordinates: [-75.2, 40.0], label: 'フィラデルフィア' },
      { coordinates: [-76.5, 37.2], label: 'ヨークタウン（決戦）', isMain: true },
      { coordinates: [2.3, 48.9], label: '仏（支援）', ally: true },
      { coordinates: [-0.1, 51.5], label: '英', enemy: true },
    ],
    cotenLinks: [
      { title: 'アメリカ開拓史編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E3%82%A2%E3%83%A1%E3%83%AA%E3%82%AB%E9%96%8B%E6%8B%93%E5%8F%B2' },
    ],
    weight: 3,
    tags: ['革命', 'ナショナリズム', '植民地解放'],
    ideologies: ['共和主義', '啓蒙思想', '自由主義'],
    causes: ['seven-years-war'],
    influences: ['french-revolution', 'haitian-revolution', 'latin-american-independence'],
  },
  {
    id: 'french-revolution',
    year: 1789, endYear: 1799,
    name: 'フランス革命',
    region: 0, type: 'revolution', era: 'early-modern',
    theater: 'フランス・ヨーロッパ',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [2.3, 48.9], label: 'パリ（バスティーユ）', isMain: true },
      { coordinates: [2.1, 48.8], label: 'ヴェルサイユ' },
      { coordinates: [16.4, 48.2], label: 'オーストリア', enemy: true },
      { coordinates: [-0.1, 51.5], label: '英（干渉）', enemy: true },
    ],
    cotenLinks: [
      { title: 'フランス革命編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E3%83%95%E3%83%A9%E3%83%B3%E3%82%B9%E9%9D%A9%E5%91%BD' },
    ],
    weight: 3,
    tags: ['革命', '経済危機', 'ナショナリズム'],
    ideologies: ['共和主義', '啓蒙思想', '自由主義', '民族自決'],
    causes: ['american-independence', 'seven-years-war'],
    influences: ['napoleonic-wars', 'haitian-revolution', 'latin-american-independence'],
  },
  {
    id: 'haitian-revolution',
    year: 1791, endYear: 1804,
    name: 'ハイチ革命',
    region: 3, type: 'revolution', era: 'early-modern',
    theater: 'サン＝ドマング（ハイチ）',
    mapHighlight: 'north-america',
    markers: [
      { coordinates: [-72.3, 19.7], label: 'ル・カップ（蜂起1791.8.22）', isMain: true },
      { coordinates: [-72.3, 18.5], label: 'ポルトープランス（独立宣言1804.1.1）', isMain: true },
      { coordinates: [2.3, 48.9], label: 'パリ（仏：黒人法・ナポレオン遠征）', enemy: true },
      { coordinates: [-0.1, 51.5], label: '英国（介入失敗）', enemy: true },
      { coordinates: [-72.1, 19.5], label: 'ヴェルティエール（最終決戦1803.11）' },
    ],
    weight: 2,
    tags: ['革命', '植民地解放', 'ナショナリズム'],
    ideologies: ['反植民地主義', '共和主義', '啓蒙思想'],
    causes: ['french-revolution', 'american-independence'],
    influences: ['latin-american-independence'],
  },
  {
    id: 'napoleonic-wars',
    year: 1803, endYear: 1815,
    name: 'ナポレオン戦争',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'ヨーロッパ全域・エジプト',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [2.3, 48.9], label: 'パリ（ナポレオン本拠）', isMain: true },
      { coordinates: [16.8, 49.1], label: 'アウステルリッツ（1805決戦）', isMain: false },
      { coordinates: [37.6, 55.8], label: 'モスクワ（1812遠征）' },
      { coordinates: [12.4, 51.3], label: 'ライプツィヒ（諸国民の戦い1813）' },
      { coordinates: [4.4, 50.7], label: 'ワーテルロー（最終決戦1815）', isMain: true },
    ],
    cotenLinks: [
      { title: 'フランス革命編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E3%83%95%E3%83%A9%E3%83%B3%E3%82%B9%E9%9D%A9%E5%91%BD' },
    ],
    weight: 3,
    tags: ['ナショナリズム', '革命', '同盟暴走', '指導者個人要因', '軍事革命'],
    ideologies: ['ナショナリズム', '共和主義', 'ボナパルティズム'],
    causes: ['french-revolution'],
    influences: ['latin-american-independence', 'greek-independence-war', 'italian-unification', 'mexican-american-war'],
  },
  {
    id: 'war-of-1812',
    year: 1812, endYear: 1815,
    name: '1812年戦争（米英戦争）',
    region: 3, type: 'war', era: 'early-modern',
    theater: '北米五大湖・大西洋・ニューオリンズ',
    mapHighlight: 'north-america',
    markers: [
      { coordinates: [-77.0, 38.9], label: 'ワシントンD.C.（焼き討ち1814.8）', isMain: true },
      { coordinates: [-83.0, 42.0], label: '五大湖（エリー湖海戦）' },
      { coordinates: [-90.1, 30.0], label: 'ニューオリンズ（決戦1815.1）', isMain: true },
      { coordinates: [-0.1, 51.5], label: '英国', enemy: true },
      { coordinates: [-76.6, 39.3], label: 'ボルチモア（星条旗誕生）' },
    ],
    weight: 1,
    tags: ['ナショナリズム', '誤算・誤認知'],
    ideologies: ['ナショナリズム', '共和主義'],
    causes: ['napoleonic-wars'],
    influences: [],
  },
  {
    id: 'latin-american-independence',
    year: 1810, endYear: 1825,
    name: 'ラテンアメリカ独立戦争',
    region: 3, type: 'revolution', era: 'early-modern',
    theater: '南米全域',
    mapHighlight: 'south-america',
    markers: [
      { coordinates: [-73.4, 5.5], label: 'ボヤカ（ボリーバル勝利1819.8）', isMain: true },
      { coordinates: [-70.7, -33.5], label: 'チャカブコ・マイプー（サン・マルティン勝利1817-18）', isMain: true },
      { coordinates: [-74.2, -13.2], label: 'アヤクーチョ（最終戦1824.12）', isMain: true },
      { coordinates: [-58.4, -34.6], label: 'ブエノスアイレス（5月革命1810.5）' },
      { coordinates: [-3.7, 40.4], label: 'マドリード（スペイン）', enemy: true },
    ],
    weight: 2,
    tags: ['革命', '植民地解放', 'ナショナリズム', '帝国衰退'],
    ideologies: ['共和主義', '民族自決', '反植民地主義'],
    causes: ['napoleonic-wars', 'haitian-revolution', 'american-independence'],
    influences: [],
  },
  {
    id: 'greek-independence-war',
    year: 1821, endYear: 1832,
    name: 'ギリシャ独立戦争',
    region: 0, type: 'revolution', era: 'early-modern',
    theater: 'バルカン半島・エーゲ海',
    mapHighlight: 'eastern-europe',
    markers: [
      { coordinates: [23.7, 37.9], label: 'アテネ（独立首都）', isMain: true },
      { coordinates: [21.4, 38.4], label: 'ミソロンギ（包囲・バイロン死）', isMain: true },
      { coordinates: [21.7, 37.0], label: 'ナヴァリノ（連合艦隊勝利1827）' },
      { coordinates: [28.9, 41.0], label: 'コンスタンティノープル（オスマン）', enemy: true },
      { coordinates: [-0.1, 51.5], label: '英・仏・露（介入）', ally: true },
    ],
    weight: 2,
    tags: ['ナショナリズム', '植民地解放', '帝国衰退', '宗教対立'],
    ideologies: ['民族自決', 'ナショナリズム', '正教会'],
    causes: ['napoleonic-wars', 'russo-turkish-war-1768'],
    influences: ['balkan-wars', 'russo-turkish-war-1877'],
  },
  {
    id: 'mexican-american-war',
    year: 1846, endYear: 1848,
    name: '米墨戦争',
    region: 3, type: 'war', era: 'early-modern',
    theater: 'メキシコ北部・カリフォルニア',
    mapHighlight: 'north-america',
    markers: [
      { coordinates: [-99.1, 19.4], label: 'メキシコ・シティ（陥落1847.9）', isMain: true },
      { coordinates: [-100.3, 25.7], label: 'モンテレイ・ブエナビスタ（決戦）' },
      { coordinates: [-99.5, 26.0], label: 'リオ・グランデ（開戦地）' },
      { coordinates: [-119.4, 36.8], label: 'カリフォルニア（占領）' },
      { coordinates: [-105.9, 35.7], label: 'サンフェ・トラム（米領化）' },
    ],
    cotenLinks: [
      { title: 'アメリカ開拓史編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E3%82%A2%E3%83%A1%E3%83%AA%E3%82%AB%E9%96%8B%E6%8B%93%E5%8F%B2' },
    ],
    weight: 2,
    tags: ['ナショナリズム', '資源争奪'],
    ideologies: ['明白なる運命', '帝国主義'],
    causes: [],
    influences: ['american-civil-war'],
  },
  {
    id: 'taiping-rebellion',
    year: 1850, endYear: 1864,
    name: '太平天国の乱',
    region: 1, type: 'revolution', era: 'early-modern',
    theater: '中国南部・長江流域',
    mapHighlight: 'east-asia',
    markers: [
      { coordinates: [118.8, 32.1], label: '南京（天京・首都）', isMain: true },
      { coordinates: [110.4, 23.1], label: '広西省金田村（蜂起地）', isMain: true },
      { coordinates: [114.3, 30.6], label: '武昌（占領）' },
      { coordinates: [116.4, 39.9], label: '北京（清朝）', enemy: true },
      { coordinates: [121.5, 31.2], label: '上海（湘軍・常勝軍）' },
    ],
    weight: 2,
    tags: ['革命', '経済危機', '宗教対立', '帝国衰退'],
    ideologies: ['千年王国主義', '反清復明'],
    causes: ['opium-war'],
    influences: ['second-opium-war', 'boxer-rebellion'],
  },
  {
    id: 'indian-rebellion',
    year: 1857, endYear: 1858,
    name: 'インド大反乱（セポイの乱）',
    region: 1, type: 'colonial', era: 'early-modern',
    theater: '北インド・中央インド',
    mapHighlight: 'south-asia',
    markers: [
      { coordinates: [77.2, 28.6], label: 'デリー（ムガル皇帝復位）', isMain: true },
      { coordinates: [80.9, 26.8], label: 'ラクナウ（包囲戦）', isMain: true },
      { coordinates: [80.3, 26.5], label: 'カーンプル（虐殺）' },
      { coordinates: [77.7, 28.9], label: 'メーラト（蜂起地）' },
      { coordinates: [-0.1, 51.5], label: '英国（東インド会社）', enemy: true },
    ],
    weight: 2,
    tags: ['植民地解放', 'ナショナリズム', '宗教対立'],
    ideologies: ['反植民地主義', 'ナショナリズム'],
    causes: [],
    influences: [],
  },
  {
    id: 'crimean-war',
    year: 1853, endYear: 1856,
    name: 'クリミア戦争',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'クリミア半島・黒海沿岸',
    mapHighlight: 'crimea',
    markers: [
      { coordinates: [33.5, 44.6], label: 'セヴァストポリ（包囲戦）', isMain: true },
      { coordinates: [28.9, 41.0], label: 'コンスタンティノープル（英仏拠点）', ally: true },
      { coordinates: [37.6, 55.8], label: 'ロシア帝国', enemy: true },
      { coordinates: [-0.1, 51.5], label: '英国', ally: true },
      { coordinates: [2.3, 48.9], label: 'フランス', ally: true },
    ],
    weight: 2,
    tags: ['帝国衰退', '同盟暴走', '資源争奪', '宗教対立'],
    ideologies: ['勢力均衡', '汎スラブ主義', '正教会'],
    causes: ['russo-turkish-war-1768'],
    influences: ['italian-unification', 'russo-turkish-war-1877'],
  },
  {
    id: 'second-opium-war',
    year: 1856, endYear: 1860,
    name: '第二次アヘン戦争（アロー戦争）',
    region: 1, type: 'colonial', era: 'early-modern',
    theater: '中国南東部・北京',
    mapHighlight: 'east-asia',
    markers: [
      { coordinates: [116.4, 39.9], label: '北京（円明園焼き討ち1860.10）', isMain: true },
      { coordinates: [113.3, 23.1], label: '広州（占領1858）', isMain: true },
      { coordinates: [117.2, 39.1], label: '天津（条約締結地1858）' },
      { coordinates: [-0.1, 51.5], label: '英・仏（連合軍）', ally: true },
      { coordinates: [37.6, 55.8], label: 'ロシア（沿海州獲得）', ally: true },
    ],
    weight: 2,
    tags: ['帝国衰退', '資源争奪', '植民地解放', '文明衝突'],
    ideologies: ['帝国主義', '自由貿易'],
    causes: ['opium-war'],
    influences: ['taiping-rebellion', 'boxer-rebellion'],
  },
  {
    id: 'italian-unification',
    year: 1859, endYear: 1871,
    name: 'イタリア統一戦争（リソルジメント）',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'イタリア半島全域',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [12.5, 41.9], label: 'トリノ→ローマ（首都変遷）', isMain: true },
      { coordinates: [8.9, 45.4], label: 'マジェンタ・ソルフェリーノ（1859決戦）', isMain: true },
      { coordinates: [13.4, 37.5], label: 'シチリア（ガリバルディ赤シャツ千人遠征1860）' },
      { coordinates: [12.3, 45.4], label: 'ヴェネチア（1866併合）' },
      { coordinates: [12.5, 41.9], label: 'ローマ（1870併合・教皇国家終焉）', isMain: true },
    ],
    weight: 2,
    tags: ['ナショナリズム', '革命'],
    ideologies: ['ナショナリズム', 'リソルジメント', '自由主義'],
    causes: ['napoleonic-wars', 'crimean-war'],
    influences: ['franco-prussian-war', 'world-war-1'],
  },
  {
    id: 'american-civil-war',
    year: 1861, endYear: 1865,
    name: '南北戦争',
    region: 3, type: 'war', era: 'early-modern',
    theater: '北アメリカ東部・南部',
    mapHighlight: 'north-america',
    markers: [
      { coordinates: [-77.5, 37.5], label: 'リッチモンド（南軍首都）', enemy: true },
      { coordinates: [-77.2, 39.8], label: 'ゲティズバーグ（1863決戦）', isMain: true },
      { coordinates: [-77.0, 38.9], label: 'ワシントンD.C.（北軍首都）', ally: true },
      { coordinates: [-78.8, 37.4], label: 'アポマトックス（南軍降伏）' },
    ],
    cotenLinks: [
      { title: 'リンカン編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E3%83%AA%E3%83%B3%E3%82%AB%E3%83%B3' },
    ],
    weight: 2,
    tags: ['経済危機', 'ナショナリズム', '資源争奪', '軍事革命'],
    ideologies: ['共和主義', '奴隷制', '州権主義'],
    causes: ['mexican-american-war'],
    influences: [],
  },
  {
    id: 'anglo-satsuma-war',
    year: 1863, endYear: 1863,
    name: '薩英戦争',
    region: 1, type: 'colonial', era: 'early-modern',
    theater: '鹿児島湾',
    mapHighlight: 'east-asia',
    markers: [
      { coordinates: [130.6, 31.6], label: '鹿児島湾（薩摩砲台・砲撃戦1863.8.15-17）', isMain: true },
      { coordinates: [139.6, 35.5], label: '生麦（リチャードソン殺害1862.9.14）', isMain: true },
      { coordinates: [-0.1, 51.5], label: '英国（東洋艦隊派遣）', enemy: true },
      { coordinates: [139.7, 35.7], label: '横浜（英艦隊出撃地）' },
      { coordinates: [130.6, 31.6], label: '薩摩藩（鹿児島市街500戸焼失）', ally: true },
    ],
    cotenLinks: [
      { title: '西郷隆盛編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E8%A5%BF%E9%83%B7%E9%9A%86%E7%9B%9B' },
    ],
    weight: 1,
    tags: ['植民地解放', '誤算・誤認知'],
    ideologies: ['攘夷思想', '帝国主義'],
    causes: [],
    influences: ['boshin-war', 'shimonoseki-campaign'],
  },
  {
    id: 'shimonoseki-campaign',
    year: 1863, endYear: 1864,
    name: '下関戦争（馬関戦争）',
    region: 1, type: 'colonial', era: 'early-modern',
    theater: '関門海峡',
    mapHighlight: 'east-asia',
    markers: [
      { coordinates: [130.95, 33.95], label: '下関（長州砲台・四国艦隊砲撃1864.8.5-7）', isMain: true },
      { coordinates: [130.95, 33.95], label: '前田・壇ノ浦砲台（占領・上陸戦）', isMain: true },
      { coordinates: [-0.1, 51.5], label: '英・仏・蘭・米（4ヶ国連合艦隊17隻）', enemy: true },
      { coordinates: [139.7, 35.7], label: '幕府（賠償300万ドル肩代わり）' },
      { coordinates: [131.5, 34.2], label: '萩・長州藩（攘夷→倒幕転換）', ally: true },
    ],
    weight: 1,
    tags: ['植民地解放', '誤算・誤認知'],
    ideologies: ['攘夷思想', '帝国主義'],
    causes: ['anglo-satsuma-war'],
    influences: ['boshin-war'],
  },
  {
    id: 'boshin-war',
    year: 1868, endYear: 1869,
    name: '戊辰戦争',
    region: 1, type: 'revolution', era: 'early-modern',
    theater: '日本列島',
    mapHighlight: 'east-asia',
    markers: [
      { coordinates: [135.8, 35.0], label: '京都（鳥羽伏見1868.1）', isMain: true },
      { coordinates: [139.7, 35.7], label: '江戸（無血開城1868.5）', isMain: true },
      { coordinates: [139.9, 37.5], label: '会津若松（陥落1868.11）' },
      { coordinates: [140.7, 41.8], label: '函館・五稜郭（最終戦1869.5）' },
      { coordinates: [130.6, 31.6], label: '薩摩・長州（新政府軍）', ally: true },
    ],
    weight: 2,
    tags: ['革命', 'ナショナリズム', '王朝継承'],
    ideologies: ['尊王攘夷', '近代化'],
    causes: ['anglo-satsuma-war', 'shimonoseki-campaign'],
    influences: ['satsuma-rebellion', 'first-sino-japanese-war'],
  },
  {
    id: 'russo-turkish-war-1877',
    year: 1877, endYear: 1878,
    name: '露土戦争（1877-78）',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'バルカン・カフカス',
    mapHighlight: 'eastern-europe',
    markers: [
      { coordinates: [30.3, 59.9], label: 'サンクトペテルブルク（露）', isMain: true },
      { coordinates: [24.6, 43.4], label: 'プレヴェン（5か月包囲戦）', isMain: true },
      { coordinates: [28.9, 41.5], label: 'コンスタンティノープル直前（停戦）' },
      { coordinates: [28.2, 41.0], label: 'サン・ステファノ条約（1878.3）' },
      { coordinates: [13.4, 52.5], label: 'ベルリン（条約改定1878.6）' },
    ],
    cotenLinks: [
      { title: 'オスマン帝国編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E3%82%AA%E3%82%B9%E3%83%9E%E3%83%B3%E5%B8%9D%E5%9B%BD' },
    ],
    weight: 2,
    tags: ['帝国衰退', 'ナショナリズム', '宗教対立', '同盟暴走'],
    ideologies: ['汎スラブ主義', '民族自決', '正教会'],
    causes: ['crimean-war', 'greek-independence-war'],
    influences: ['balkan-wars', 'world-war-1'],
  },
  {
    id: 'paraguayan-war',
    year: 1864, endYear: 1870,
    name: 'パラグアイ戦争（三国同盟戦争）',
    region: 3, type: 'war', era: 'early-modern',
    theater: 'パラグアイ全土・周辺地域',
    mapHighlight: 'south-america',
    markers: [
      { coordinates: [-57.6, -25.3], label: 'アスンシオン（パラグアイ首都）', isMain: true },
      { coordinates: [-55.8, -22.8], label: 'セロ・コラ（ロペス戦死1870.3.1）', isMain: true },
      { coordinates: [-57.9, -27.5], label: 'ウマイタ要塞（1868.7陥落）' },
      { coordinates: [-58.4, -34.6], label: 'ブエノスアイレス（亜・三国同盟）', enemy: true },
      { coordinates: [-43.2, -22.9], label: 'リオデジャネイロ（伯）', enemy: true },
    ],
    weight: 1,
    tags: ['ナショナリズム', '指導者個人要因', '誤算・誤認知'],
    ideologies: ['ナショナリズム'],
    causes: [],
    influences: [],
  },
  {
    id: 'franco-prussian-war',
    year: 1870, endYear: 1871,
    name: '普仏戦争',
    region: 0, type: 'war', era: 'early-modern',
    theater: 'フランス・アルザス＝ロレーヌ',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [13.4, 52.5], label: 'プロイセン（ベルリン）', isMain: true },
      { coordinates: [4.9, 49.7], label: 'スダン（ナポレオン3世捕虜）', isMain: true },
      { coordinates: [6.2, 49.1], label: 'メス（包囲戦）' },
      { coordinates: [2.3, 48.9], label: 'パリ（包囲・コミューン）' },
      { coordinates: [2.1, 48.8], label: 'ヴェルサイユ（ドイツ帝国宣言）' },
    ],
    weight: 2,
    tags: ['ナショナリズム', '誤算・誤認知', '指導者個人要因'],
    ideologies: ['ナショナリズム', '汎ゲルマン主義'],
    causes: ['italian-unification'],
    influences: ['world-war-1', 'mexican-revolution'],
  },
  {
    id: 'opium-war',
    year: 1840, endYear: 1842,
    name: 'アヘン戦争',
    region: 1, type: 'war', era: 'early-modern',
    theater: '中国南東部沿岸',
    mapHighlight: 'east-asia',
    markers: [
      { coordinates: [113.3, 23.1], label: '広州（戦端）', isMain: true },
      { coordinates: [114.2, 22.3], label: '香港（割譲）', isMain: true },
      { coordinates: [121.5, 31.2], label: '寧波・上海（占領）' },
      { coordinates: [118.8, 32.1], label: '南京（条約締結）' },
      { coordinates: [-0.1, 51.5], label: '英国', ally: true },
    ],
    weight: 2,
    tags: ['帝国衰退', '資源争奪', '植民地解放', '文明衝突'],
    ideologies: ['帝国主義', '自由貿易'],
    causes: [],
    influences: ['taiping-rebellion', 'second-opium-war', 'first-sino-japanese-war'],
  },
  {
    id: 'first-sino-japanese-war',
    year: 1894, endYear: 1895,
    name: '日清戦争',
    region: 1, type: 'war', era: 'early-modern',
    theater: '朝鮮半島・満洲・黄海',
    mapHighlight: 'east-asia',
    markers: [
      { coordinates: [139.7, 35.7], label: '東京（大本営）', isMain: true },
      { coordinates: [121.3, 38.9], label: '旅順（陥落）', isMain: true },
      { coordinates: [125.7, 39.0], label: '平壌（陸上決戦）' },
      { coordinates: [116.4, 39.9], label: '北京（清国）', enemy: true },
      { coordinates: [123.0, 38.0], label: '黄海（海戦）' },
    ],
    weight: 2,
    tags: ['ナショナリズム', '帝国衰退', '資源争奪'],
    ideologies: ['ナショナリズム', '帝国主義', '脱亜入欧'],
    causes: ['boshin-war', 'opium-war'],
    influences: ['russo-japanese-war', 'boxer-rebellion', 'second-sino-japanese-war'],
  },
  {
    id: 'russo-japanese-war',
    year: 1904, endYear: 1905,
    name: '日露戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: '満洲・朝鮮・対馬海峡',
    mapHighlight: 'east-asia',
    markers: [
      { coordinates: [139.7, 35.7], label: '東京（大本営）', isMain: true },
      { coordinates: [121.3, 38.9], label: '旅順（203高地）', isMain: true },
      { coordinates: [123.4, 41.8], label: '奉天（最大陸上決戦）' },
      { coordinates: [129.0, 34.5], label: '対馬海峡（バルチック艦隊壊滅）', isMain: true },
      { coordinates: [30.3, 59.9], label: 'サンクトペテルブルク（ロシア）', enemy: true },
    ],
    cotenLinks: [
      { title: '日露戦争編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E6%97%A5%E9%9C%B2%E6%88%A6%E4%BA%89' },
    ],
    weight: 2,
    tags: ['ナショナリズム', '資源争奪', '誤算・誤認知', '海洋覇権'],
    ideologies: ['帝国主義', 'ナショナリズム'],
    causes: ['first-sino-japanese-war', 'boxer-rebellion'],
    influences: ['russian-revolution', 'world-war-1', 'second-sino-japanese-war'],
  },

  {
    id: 'spanish-american-war',
    year: 1898, endYear: 1898,
    name: '米西戦争',
    region: 3, type: 'war', era: 'early-modern',
    theater: 'キューバ・プエルトリコ・フィリピン・グアム',
    mapHighlight: 'north-america',
    markers: [
      { coordinates: [-82.4, 23.1], label: 'ハバナ港（メイン号爆沈1898.2）', isMain: true },
      { coordinates: [-75.8, 20.0], label: 'サンチアゴ（決戦1898.7）' },
      { coordinates: [-66.1, 18.5], label: 'プエルトリコ（占領）' },
      { coordinates: [120.9, 14.5], label: 'マニラ湾（フィリピン1898.5）', isMain: true },
      { coordinates: [144.8, 13.5], label: 'グアム（無血占領）' },
    ],
    weight: 2,
    tags: ['帝国衰退', 'ナショナリズム', '情報戦・プロパガンダ', '海洋覇権'],
    ideologies: ['帝国主義', '明白なる運命'],
    causes: [],
    influences: ['philippine-american-war'],
  },

  {
    id: 'second-boer-war',
    year: 1899, endYear: 1902,
    name: '第二次ボーア戦争',
    region: 2, type: 'colonial', era: 'early-modern',
    theater: '南アフリカ（トランスヴァール・オレンジ自由国）',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [28.2, -25.7], label: 'プレトリア（ボーア首都・陥落1900.6）', isMain: true },
      { coordinates: [28.0, -26.2], label: 'ヨハネスブルク（金鉱）' },
      { coordinates: [29.8, -28.6], label: 'レディスミス（包囲戦）' },
      { coordinates: [28.0, -26.0], label: '強制収容所（女性・子供死亡）', isMain: true },
      { coordinates: [-0.1, 51.5], label: '英国', ally: true },
    ],
    weight: 1,
    tags: ['植民地解放', '資源争奪', 'ナショナリズム'],
    ideologies: ['帝国主義', 'ナショナリズム'],
    causes: [],
    influences: [],
  },
  {
    id: 'boxer-rebellion',
    year: 1899, endYear: 1901,
    name: '義和団事件',
    region: 1, type: 'revolution', era: '20th-century',
    theater: '北中国・北京',
    mapHighlight: 'east-asia',
    markers: [
      { coordinates: [116.4, 39.9], label: '北京（公使館包囲1900.6）', isMain: true },
      { coordinates: [117.2, 39.1], label: '天津（連合軍上陸地）', isMain: true },
      { coordinates: [116.4, 39.9], label: '紫禁城（西太后逃亡）' },
      { coordinates: [139.7, 35.7], label: '日本（連合軍最大派遣）', ally: true },
      { coordinates: [37.6, 55.8], label: 'ロシア（満洲占領）', ally: true },
    ],
    weight: 1,
    tags: ['帝国衰退', 'ナショナリズム', '宗教対立', '文明衝突'],
    ideologies: ['排外主義', 'ナショナリズム'],
    causes: ['first-sino-japanese-war', 'second-opium-war'],
    influences: ['russo-japanese-war'],
  },

  {
    id: 'satsuma-rebellion',
    year: 1877, endYear: 1877,
    name: '西南戦争',
    region: 1, type: 'revolution', era: 'early-modern',
    theater: '南九州（鹿児島・熊本・宮崎）',
    mapHighlight: 'east-asia',
    markers: [
      { coordinates: [130.6, 31.6], label: '鹿児島（西郷蜂起・最終戦城山）', isMain: true },
      { coordinates: [130.7, 32.8], label: '熊本城（籠城戦1877.2-4）', isMain: true },
      { coordinates: [130.7, 32.7], label: '田原坂（最大激戦1877.3）' },
      { coordinates: [139.7, 35.7], label: '東京（明治政府）', enemy: true },
      { coordinates: [131.6, 31.9], label: '延岡・宮崎（撤退戦）' },
    ],
    cotenLinks: [
      { title: '西郷隆盛編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E8%A5%BF%E9%83%B7%E9%9A%86%E7%9B%9B' },
    ],
    weight: 1,
    tags: ['革命', '指導者個人要因'],
    ideologies: ['士族', '近代化'],
    causes: ['boshin-war'],
    influences: [],
  },

  /* ─────────────────── 20世紀（1900-1999） ─────────────────── */

  {
    id: 'second-sino-japanese-war',
    year: 1937, endYear: 1945,
    name: '日中戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: '中国全土',
    mapHighlight: 'east-asia',
    markers: [
      { coordinates: [116.3, 39.9], label: '盧溝橋（開戦1937.7.7）', isMain: true },
      { coordinates: [118.8, 32.1], label: '南京（虐殺1937.12）', isMain: true },
      { coordinates: [121.5, 31.2], label: '上海（激戦1937）' },
      { coordinates: [106.6, 29.6], label: '重慶（国民政府移転）' },
      { coordinates: [139.7, 35.7], label: '東京（大本営）', enemy: true },
    ],
    weight: 2,
    tags: ['ナショナリズム', '資源争奪', '帝国衰退', '指導者個人要因'],
    ideologies: ['軍国主義', '大東亜共栄圏', 'ナショナリズム'],
    causes: ['first-sino-japanese-war', 'russo-japanese-war'],
    influences: ['pacific-war', 'chinese-civil-war'],
  },
  {
    id: 'first-indochina-war',
    year: 1946, endYear: 1954,
    name: '第一次インドシナ戦争',
    region: 1, type: 'colonial', era: '20th-century',
    theater: 'ベトナム・ラオス・カンボジア',
    mapHighlight: 'southeast-asia',
    markers: [
      { coordinates: [105.8, 21.0], label: 'ハノイ（ベトミン拠点）', isMain: true },
      { coordinates: [103.0, 21.4], label: 'ディエンビエンフー（決戦1954.5.7）', isMain: true },
      { coordinates: [106.3, 22.7], label: 'カオバン（中越国境補給）' },
      { coordinates: [106.7, 10.8], label: 'サイゴン（仏軍司令部）', enemy: true },
      { coordinates: [2.3, 48.9], label: 'パリ（フランス本国）', enemy: true },
    ],
    weight: 1,
    tags: ['植民地解放', 'ナショナリズム', '冷戦構造'],
    ideologies: ['反植民地主義', '共産主義', '民族自決'],
    causes: ['pacific-war'],
    influences: ['vietnam-war'],
  },
  {
    id: 'greek-civil-war',
    year: 1946, endYear: 1949,
    name: 'ギリシャ内戦',
    region: 0, type: 'revolution', era: '20th-century',
    theater: 'ギリシャ北部・山岳地帯',
    mapHighlight: 'eastern-europe',
    markers: [
      { coordinates: [23.7, 37.9], label: 'アテネ（王党派政府）', isMain: true },
      { coordinates: [20.8, 40.7], label: 'グランモス山（最終戦1949.8）', isMain: true },
      { coordinates: [21.1, 40.5], label: 'ヴィツィ山（共産党ゲリラ）' },
      { coordinates: [-0.1, 51.5], label: '英・米（トルーマン・ドクトリン）', ally: true },
      { coordinates: [20.5, 44.8], label: 'ユーゴスラビア（チトー支援→断絶1948）' },
    ],
    weight: 1,
    tags: ['冷戦構造', '革命', '植民地解放'],
    ideologies: ['共産主義', '反共主義'],
    causes: ['world-war-2-europe'],
    influences: [],
  },
  {
    id: 'chinese-civil-war',
    year: 1946, endYear: 1949,
    name: '中国国共内戦',
    region: 1, type: 'revolution', era: '20th-century',
    theater: '中国全土',
    mapHighlight: 'east-asia',
    markers: [
      { coordinates: [116.4, 39.9], label: '北京（解放1949.1）', isMain: true },
      { coordinates: [121.5, 31.2], label: '上海（解放1949.5）' },
      { coordinates: [109.5, 36.6], label: '延安（共産党根拠地）', isMain: true },
      { coordinates: [123.4, 41.8], label: '瀋陽（東北戦線決戦）' },
      { coordinates: [121.5, 25.0], label: '台北（国民党敗走1949）', enemy: true },
    ],
    weight: 3,
    tags: ['革命', '冷戦構造', 'ナショナリズム'],
    ideologies: ['共産主義', 'マルクス・レーニン主義', 'ナショナリズム'],
    causes: ['second-sino-japanese-war'],
    influences: ['korean-war', 'sino-vietnamese-war', 'sino-indian-war'],
  },
  {
    id: 'malayan-emergency',
    year: 1948, endYear: 1960,
    name: 'マラヤ非常事態',
    region: 1, type: 'colonial', era: '20th-century',
    theater: 'マラヤ連邦（現マレーシア）',
    mapHighlight: 'southeast-asia',
    markers: [
      { coordinates: [101.7, 3.1], label: 'クアラルンプール（首都）', isMain: true },
      { coordinates: [102.2, 4.0], label: 'ジャングル（共産党MNLAゲリラ拠点）', isMain: true },
      { coordinates: [103.8, 3.5], label: '新村（住民隔離村約500か所）' },
      { coordinates: [-0.1, 51.5], label: '英国（テンプラー高等弁務官）', ally: true },
      { coordinates: [116.4, 39.9], label: '中国（MCP支援）', enemy: true },
    ],
    weight: 1,
    tags: ['植民地解放', '冷戦構造', '革命'],
    ideologies: ['共産主義', '反植民地主義'],
    causes: ['pacific-war'],
    influences: [],
  },
  {
    id: 'first-arab-israeli-war',
    year: 1948, endYear: 1949,
    name: '第一次中東戦争（パレスチナ戦争）',
    region: 2, type: 'war', era: '20th-century',
    theater: 'パレスチナ・周辺アラブ諸国',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [34.8, 32.1], label: 'テルアビブ（独立宣言1948.5.14）', isMain: true },
      { coordinates: [35.2, 31.8], label: 'エルサレム（分割）', isMain: true },
      { coordinates: [34.5, 31.5], label: 'ガザ（エジプト統治）' },
      { coordinates: [31.2, 30.1], label: 'カイロ（エジプト）', enemy: true },
      { coordinates: [36.3, 33.5], label: 'ダマスカス（シリア）', enemy: true },
    ],
    weight: 2,
    tags: ['ナショナリズム', '宗教対立', '植民地解放'],
    ideologies: ['シオニズム', 'アラブ民族主義'],
    causes: ['world-war-2-europe'],
    influences: ['suez-crisis', 'six-day-war', 'yom-kippur-war', 'gaza-war'],
  },
  {
    id: 'first-indo-pakistani-war',
    year: 1947, endYear: 1948,
    name: '第一次印パ戦争（カシミール紛争）',
    region: 1, type: 'war', era: '20th-century',
    theater: 'カシミール地方',
    mapHighlight: 'south-asia',
    markers: [
      { coordinates: [74.8, 34.1], label: 'スリナガル（カシミール首都）', isMain: true },
      { coordinates: [73.5, 34.4], label: 'ムザッファラバード（パキスタン側）', enemy: true },
      { coordinates: [77.2, 28.6], label: 'デリー（インド）', ally: true },
      { coordinates: [67.0, 24.9], label: 'カラチ（パキスタン）', enemy: true },
      { coordinates: [74.9, 32.7], label: 'ジャンムー（インド側）' },
    ],
    weight: 1,
    tags: ['ナショナリズム', '宗教対立', '植民地解放'],
    ideologies: ['ナショナリズム', '民族自決'],
    causes: [],
    influences: ['second-indo-pakistani-war', 'bangladesh-liberation-war', 'kargil-war'],
  },
  {
    id: 'suez-crisis',
    year: 1956, endYear: 1956,
    name: 'スエズ動乱（第二次中東戦争）',
    region: 2, type: 'war', era: '20th-century',
    theater: 'スエズ運河・シナイ半島',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [32.5, 30.0], label: 'スエズ運河（国有化・侵攻）', isMain: true },
      { coordinates: [31.2, 30.1], label: 'カイロ（ナセル）', isMain: true },
      { coordinates: [34.8, 32.1], label: 'テルアビブ（イスラエル）', ally: true },
      { coordinates: [-0.1, 51.5], label: '英国', ally: true },
      { coordinates: [2.3, 48.9], label: 'フランス', ally: true },
    ],
    weight: 2,
    tags: ['帝国衰退', 'ナショナリズム', '冷戦構造', '資源争奪'],
    ideologies: ['アラブ民族主義', '反植民地主義'],
    causes: ['first-arab-israeli-war'],
    influences: ['six-day-war'],
  },
  {
    id: 'cuban-revolution',
    year: 1953, endYear: 1959,
    name: 'キューバ革命',
    region: 3, type: 'revolution', era: '20th-century',
    theater: 'キューバ全土',
    mapHighlight: 'north-america',
    markers: [
      { coordinates: [-82.4, 23.1], label: 'ハバナ（カストロ入城1959.1.8）', isMain: true },
      { coordinates: [-76.8, 20.0], label: 'シエラ・マエストラ（ゲリラ拠点）', isMain: true },
      { coordinates: [-76.6, 20.0], label: 'モンカダ兵舎（蜂起1953.7.26）' },
      { coordinates: [-79.9, 22.4], label: 'サンタクララ（ゲバラ最終戦1958.12）' },
      { coordinates: [-77.0, 38.9], label: '米国（バチスタ支援）', enemy: true },
    ],
    weight: 2,
    tags: ['革命', '冷戦構造', 'ナショナリズム'],
    ideologies: ['共産主義', '反帝国主義'],
    causes: [],
    influences: ['nicaraguan-revolution', 'salvadoran-civil-war', 'guatemalan-civil-war'],
  },
  {
    id: 'hungarian-uprising',
    year: 1956, endYear: 1956,
    name: 'ハンガリー動乱',
    region: 0, type: 'revolution', era: '20th-century',
    theater: 'ハンガリー全土',
    mapHighlight: 'eastern-europe',
    markers: [
      { coordinates: [19.0, 47.5], label: 'ブダペスト（蜂起1956.10.23）', isMain: true },
      { coordinates: [19.0, 47.5], label: '国会議事堂（虐殺）', isMain: true },
      { coordinates: [19.0, 47.5], label: 'ソ連軍司令部' },
      { coordinates: [37.6, 55.8], label: 'モスクワ（フルシチョフ）', enemy: true },
      { coordinates: [16.4, 48.2], label: 'オーストリア（難民20万受入）', ally: true },
    ],
    weight: 1,
    tags: ['革命', '冷戦構造', 'ナショナリズム'],
    ideologies: ['民族自決', '反共産主義'],
    causes: [],
    influences: [],
  },
  {
    id: 'algerian-war',
    year: 1954, endYear: 1962,
    name: 'アルジェリア戦争',
    region: 2, type: 'colonial', era: '20th-century',
    theater: 'アルジェリア全域',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [3.1, 36.7], label: 'アルジェ（首都・市街戦1957）', isMain: true },
      { coordinates: [6.6, 35.5], label: 'オレス山地（FLN拠点）' },
      { coordinates: [-0.6, 35.7], label: 'オラン（仏軍拠点）' },
      { coordinates: [2.3, 48.9], label: 'パリ（仏本国）', enemy: true },
    ],
    weight: 2,
    tags: ['植民地解放', 'ナショナリズム', '宗教対立'],
    ideologies: ['反植民地主義', 'アラブ民族主義', '民族自決'],
    causes: [],
    influences: ['algerian-civil-war'],
  },
  {
    id: 'guatemalan-civil-war',
    year: 1960, endYear: 1996,
    name: 'グアテマラ内戦',
    region: 3, type: 'revolution', era: '20th-century',
    theater: 'グアテマラ全土',
    mapHighlight: 'north-america',
    markers: [
      { coordinates: [-90.5, 14.6], label: 'グアテマラ・シティ（首都）', isMain: true },
      { coordinates: [-91.5, 15.5], label: 'マヤ高原（先住民虐殺地帯）', isMain: true },
      { coordinates: [-91.3, 15.3], label: 'イクシル地域（80年代焼土作戦）' },
      { coordinates: [-77.0, 38.9], label: '米国（CIAクーデター1954・軍事援助）', enemy: true },
      { coordinates: [-82.4, 23.1], label: 'キューバ（左翼ゲリラ支援）', ally: true },
    ],
    weight: 1,
    tags: ['冷戦構造', '革命', '民族浄化'],
    ideologies: ['共産主義', '反共主義'],
    causes: ['cuban-revolution'],
    influences: [],
  },
  {
    id: 'salvadoran-civil-war',
    year: 1979, endYear: 1992,
    name: 'エルサルバドル内戦',
    region: 3, type: 'revolution', era: '20th-century',
    theater: 'エルサルバドル全土',
    mapHighlight: 'north-america',
    markers: [
      { coordinates: [-89.2, 13.7], label: 'サンサルバドル（首都）', isMain: true },
      { coordinates: [-88.1, 13.8], label: 'エル・モソテ虐殺（1981.12）', isMain: true },
      { coordinates: [-88.0, 13.8], label: 'モラサン州（FMLN拠点）' },
      { coordinates: [-77.0, 38.9], label: '米国（年60億ドル軍事援助）', enemy: true },
      { coordinates: [-86.3, 12.1], label: 'マナグア（ニカラグア・FMLN支援）', ally: true },
    ],
    weight: 1,
    tags: ['冷戦構造', '革命'],
    ideologies: ['共産主義', '反共主義'],
    causes: ['cuban-revolution', 'nicaraguan-revolution'],
    influences: [],
  },
  {
    id: 'sino-vietnamese-war',
    year: 1979, endYear: 1979,
    name: '中越戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: '中越国境（ベトナム北部）',
    mapHighlight: 'southeast-asia',
    markers: [
      { coordinates: [106.8, 21.9], label: 'ランソン（最大激戦）', isMain: true },
      { coordinates: [106.3, 22.7], label: 'カオバン（侵攻地）' },
      { coordinates: [105.8, 21.0], label: 'ハノイ（北越首都）', enemy: true },
      { coordinates: [116.4, 39.9], label: '北京（鄧小平・「懲罰」）', ally: true },
      { coordinates: [37.6, 55.8], label: 'モスクワ（越支援）', enemy: true },
    ],
    weight: 1,
    tags: ['冷戦構造', 'ナショナリズム', '誤算・誤認知'],
    ideologies: ['共産主義', 'ナショナリズム'],
    causes: ['chinese-civil-war', 'vietnam-war'],
    influences: [],
  },
  {
    id: 'namibian-independence-war',
    year: 1966, endYear: 1990,
    name: 'ナミビア独立戦争',
    region: 2, type: 'colonial', era: '20th-century',
    theater: 'ナミビア（南西アフリカ）',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [17.1, -22.6], label: 'ヴィントフック（首都・1990独立）', isMain: true },
      { coordinates: [17.0, -18.0], label: 'カプリヴィ・オバンボランド（戦闘地）', isMain: true },
      { coordinates: [28.2, -25.7], label: '南アフリカ（占領・アパルトヘイト）', enemy: true },
      { coordinates: [13.2, -8.8], label: 'アンゴラ（SWAPO拠点）', ally: true },
      { coordinates: [19.8, -15.8], label: 'クイトクアナヴァレ（1988決戦）' },
    ],
    weight: 1,
    tags: ['植民地解放', '冷戦構造', 'ナショナリズム'],
    ideologies: ['反植民地主義', '民族自決'],
    causes: [],
    influences: [],
  },
  {
    id: 'first-nagorno-karabakh-war',
    year: 1988, endYear: 1994,
    name: '第一次ナゴルノ・カラバフ戦争',
    region: 0, type: 'war', era: '20th-century',
    theater: 'ナゴルノ・カラバフ',
    mapHighlight: 'eastern-europe',
    markers: [
      { coordinates: [46.7, 39.8], label: 'ステパナケルト（NK首都）', isMain: true },
      { coordinates: [46.7, 39.8], label: 'シューシャ（1992.5アルメニア占領）', isMain: true },
      { coordinates: [44.5, 40.2], label: 'エレバン（アルメニア）', ally: true },
      { coordinates: [49.9, 40.4], label: 'バクー（アゼルバイジャン）', enemy: true },
      { coordinates: [46.8, 39.9], label: 'ホジャリ虐殺（1992.2、推計600人）' },
    ],
    weight: 1,
    tags: ['ナショナリズム', '権力真空', '民族浄化'],
    ideologies: ['民族自決', 'ナショナリズム'],
    causes: [],
    influences: ['nagorno-karabakh-2020'],
  },
  {
    id: 'lebanese-civil-war',
    year: 1975, endYear: 1990,
    name: 'レバノン内戦',
    region: 2, type: 'war', era: '20th-century',
    theater: 'レバノン全土',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [35.5, 33.9], label: 'ベイルート（緑の境界線）', isMain: true },
      { coordinates: [35.5, 33.8], label: 'サブラ・シャティーラ（虐殺1982）', isMain: true },
      { coordinates: [36.3, 33.5], label: 'ダマスカス（シリア介入）', enemy: true },
      { coordinates: [34.8, 32.1], label: 'テルアビブ（イスラエル侵攻1982）', enemy: true },
      { coordinates: [35.3, 33.3], label: 'ティール（PLO拠点）' },
    ],
    weight: 1,
    tags: ['宗教対立', '権力真空', '情報戦・プロパガンダ'],
    ideologies: ['アラブ民族主義', 'シオニズム', 'イスラム主義'],
    causes: ['first-arab-israeli-war', 'six-day-war'],
    influences: ['syrian-civil-war'],
  },
  {
    id: 'angolan-civil-war',
    year: 1975, endYear: 2002,
    name: 'アンゴラ内戦',
    region: 2, type: 'war', era: '20th-century',
    theater: 'アンゴラ全土',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [13.2, -8.8], label: 'ルアンダ（首都・MPLA政府）', isMain: true },
      { coordinates: [15.7, -12.8], label: 'ウアンボ（UNITA本拠地）', enemy: true },
      { coordinates: [12.2, -5.6], label: 'カビンダ（油田地帯）' },
      { coordinates: [37.6, 55.8], label: 'ソ連・キューバ（MPLA支援）', ally: true },
      { coordinates: [-77.0, 38.9], label: '米・南アフリカ（UNITA支援）', enemy: true },
    ],
    weight: 1,
    tags: ['冷戦構造', '植民地解放', '資源争奪'],
    ideologies: ['共産主義', '反共主義'],
    causes: [],
    influences: ['second-congo-war'],
  },
  {
    id: 'peruvian-internal-conflict',
    year: 1980, endYear: 2000,
    name: 'ペルー内戦（センデロ・ルミノソ）',
    region: 3, type: 'revolution', era: '20th-century',
    theater: 'ペルー全土・アヤクーチョ州',
    mapHighlight: 'south-america',
    markers: [
      { coordinates: [-77.0, -12.0], label: 'リマ（首都・タルサ作戦1992）', isMain: true },
      { coordinates: [-74.2, -13.2], label: 'アヤクーチョ（蜂起地・センデロ拠点）', isMain: true },
      { coordinates: [-74.5, -13.5], label: 'チュスチ（最初の蜂起1980.5）' },
      { coordinates: [-72.0, -14.0], label: 'アンデス山脈農村（虐殺地帯）' },
      { coordinates: [-77.0, -12.0], label: 'グスマン逮捕（1992.9.12）' },
    ],
    weight: 1,
    tags: ['革命', '冷戦構造'],
    ideologies: ['毛沢東主義', '共産主義'],
    causes: [],
    influences: [],
  },
  {
    id: 'iran-iraq-war',
    year: 1980, endYear: 1988,
    name: 'イラン・イラク戦争',
    region: 2, type: 'war', era: '20th-century',
    theater: 'イラン西部・イラク東部',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [44.4, 33.3], label: 'バグダード（イラク首都）', isMain: true },
      { coordinates: [51.4, 35.7], label: 'テヘラン（イラン首都）', enemy: true },
      { coordinates: [47.8, 30.5], label: 'バスラ（南部激戦）' },
      { coordinates: [48.3, 30.3], label: 'アバダン（油田・包囲）' },
      { coordinates: [46.2, 35.2], label: 'ハラブジャ（化学兵器1988）', isMain: true },
    ],
    weight: 2,
    tags: ['ナショナリズム', '宗教対立', '資源争奪', '誤算・誤認知'],
    ideologies: ['イスラム主義', 'アラブ民族主義', 'バース主義'],
    causes: ['iranian-revolution'],
    influences: ['gulf-war'],
  },
  {
    id: 'chechen-wars',
    year: 1994, endYear: 2009,
    name: 'チェチェン戦争',
    region: 0, type: 'war', era: '20th-century',
    theater: 'ロシア・チェチェン共和国',
    mapHighlight: 'eastern-europe',
    markers: [
      { coordinates: [45.7, 43.3], label: 'グロズヌイ（壊滅的市街戦）', isMain: true },
      { coordinates: [45.5, 43.0], label: 'カフカス山中（ゲリラ拠点）', isMain: true },
      { coordinates: [37.6, 55.8], label: 'モスクワ（ロシア政府）', enemy: true },
      { coordinates: [44.7, 43.2], label: 'ベスラン（学校占拠2004.9）' },
      { coordinates: [37.6, 55.8], label: 'モスクワ劇場占拠（2002.10）' },
    ],
    weight: 1,
    tags: ['ナショナリズム', '宗教対立', '権力真空', '民族浄化'],
    ideologies: ['民族自決', 'イスラム主義'],
    causes: ['soviet-afghan-war'],
    influences: ['ukraine-war'],
  },
  {
    id: 'rwandan-genocide',
    year: 1994, endYear: 1994,
    name: 'ルワンダ虐殺',
    region: 2, type: 'revolution', era: '20th-century',
    theater: 'ルワンダ全土',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [30.1, -1.9], label: 'キガリ（首都・蜂起地）', isMain: true },
      { coordinates: [30.2, -2.3], label: 'ニャマタ教会（虐殺現場）', isMain: true },
      { coordinates: [29.7, -2.6], label: 'ブタレ（南部・激戦）' },
      { coordinates: [29.2, -1.7], label: 'ゴマ（難民流出先）' },
    ],
    weight: 2,
    tags: ['民族浄化', '植民地解放', '情報戦・プロパガンダ', '権力真空'],
    ideologies: ['民族主義'],
    causes: [],
    influences: ['second-congo-war'],
  },
  {
    id: 'kosovo-war',
    year: 1998, endYear: 1999,
    name: 'コソボ紛争',
    region: 0, type: 'war', era: '20th-century',
    theater: 'コソボ自治州',
    mapHighlight: 'eastern-europe',
    markers: [
      { coordinates: [21.2, 42.7], label: 'プリシュティナ（首都）', isMain: true },
      { coordinates: [21.0, 42.5], label: 'ラチャク（虐殺1999.1）', isMain: true },
      { coordinates: [20.5, 44.8], label: 'ベオグラード（NATO空爆）', enemy: true },
      { coordinates: [-77.0, 38.9], label: '米・NATO', ally: true },
    ],
    weight: 1,
    tags: ['民族浄化', 'ナショナリズム', '権力真空'],
    ideologies: ['民族自決', 'ナショナリズム'],
    causes: ['bosnian-war'],
    influences: ['libyan-civil-war'],
  },
  {
    id: 'sri-lankan-civil-war',
    year: 1983, endYear: 2009,
    name: 'スリランカ内戦',
    region: 1, type: 'war', era: '20th-century',
    theater: 'スリランカ北部・東部',
    mapHighlight: 'south-asia',
    markers: [
      { coordinates: [79.9, 6.9], label: 'コロンボ（首都・政府）', isMain: true },
      { coordinates: [80.0, 9.7], label: 'ジャフナ（タミル・タイガー拠点）', isMain: true },
      { coordinates: [80.4, 9.4], label: 'キリノチ（LTTE首都→陥落2009.1）' },
      { coordinates: [80.8, 9.3], label: 'ムッライティーヴ（最終戦2009.5）' },
      { coordinates: [77.2, 28.6], label: 'インド（IPKF介入1987-90）', ally: true },
    ],
    weight: 1,
    tags: ['ナショナリズム', '民族浄化', '宗教対立'],
    ideologies: ['民族自決', 'シンハラ仏教ナショナリズム'],
    causes: [],
    influences: [],
  },
  {
    id: 'second-congo-war',
    year: 1998, endYear: 2003,
    name: '第二次コンゴ戦争（アフリカ大戦）',
    region: 2, type: 'war', era: '20th-century',
    theater: 'コンゴ民主共和国全土',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [15.3, -4.3], label: 'キンシャサ（首都・カビラ政権）', isMain: true },
      { coordinates: [29.2, -1.7], label: 'ゴマ・ブカヴ（東部反乱拠点）', isMain: true },
      { coordinates: [30.1, -1.9], label: 'ルワンダ・ウガンダ（侵攻軍）', enemy: true },
      { coordinates: [13.2, -8.8], label: 'アンゴラ・ジンバブエ（政府支援）', ally: true },
      { coordinates: [28.5, -2.5], label: 'コンゴ東部（鉱物資源紛争地）' },
    ],
    weight: 2,
    tags: ['権力真空', '資源争奪', '民族浄化'],
    ideologies: ['民族主義'],
    causes: ['rwandan-genocide'],
    influences: [],
  },
  {
    id: 'somali-civil-war',
    year: 1991, endYear: 2025,
    name: 'ソマリア内戦',
    region: 2, type: 'war', era: '20th-century',
    theater: 'ソマリア全土・モガディシュ',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [45.3, 2.0], label: 'モガディシュ（首都・ブラックホーク墜落1993.10）', isMain: true },
      { coordinates: [49.5, 8.5], label: 'プントランド（北東部・自治）' },
      { coordinates: [44.1, 9.6], label: 'ソマリランド（北西部・事実上独立）' },
      { coordinates: [42.5, 0.4], label: 'キスマヨ（アル・シャバブ拠点）', isMain: true },
      { coordinates: [43.6, 3.1], label: 'バイドア（飢饉中心地）' },
    ],
    weight: 1,
    tags: ['権力真空', '宗教対立', '植民地解放'],
    ideologies: ['イスラム主義', '氏族主義'],
    causes: [],
    influences: [],
  },
  {
    id: 'kargil-war',
    year: 1999, endYear: 1999,
    name: 'カーギル戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: 'カシミール・カーギル地区',
    mapHighlight: 'south-asia',
    markers: [
      { coordinates: [76.1, 34.6], label: 'カーギル（戦闘地）', isMain: true },
      { coordinates: [75.8, 34.5], label: 'ドラス・ティーガ高地（標高5千m級）', isMain: true },
      { coordinates: [77.2, 28.6], label: 'デリー（インド）', ally: true },
      { coordinates: [73.1, 33.7], label: 'イスラマバード（パキスタン）', enemy: true },
      { coordinates: [74.8, 34.1], label: 'スリナガル（前線基地）' },
    ],
    weight: 1,
    tags: ['ナショナリズム', '核抑止', '誤算・誤認知'],
    ideologies: ['ナショナリズム'],
    causes: ['first-indo-pakistani-war', 'second-indo-pakistani-war', 'bangladesh-liberation-war'],
    influences: [],
  },
  {
    id: 'algerian-civil-war',
    year: 1991, endYear: 2002,
    name: 'アルジェリア内戦（暗黒の10年）',
    region: 2, type: 'revolution', era: '20th-century',
    theater: 'アルジェリア全土',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [3.1, 36.7], label: 'アルジェ（首都・テロの中心）', isMain: true },
      { coordinates: [3.0, 36.6], label: 'ベンタルハ虐殺（1997.9）', isMain: true },
      { coordinates: [6.6, 35.5], label: 'オレス山地（GIAゲリラ）' },
      { coordinates: [-0.6, 35.7], label: 'オラン（FIS主要支持地）' },
      { coordinates: [2.3, 48.9], label: 'パリ（仏：エール・フランス機ハイジャック1994）', enemy: true },
    ],
    weight: 1,
    tags: ['宗教対立', '革命', '民族浄化'],
    ideologies: ['イスラム主義', '世俗主義'],
    causes: ['algerian-war'],
    influences: [],
  },
  {
    id: 'bosnian-war',
    year: 1992, endYear: 1995,
    name: 'ボスニア戦争',
    region: 0, type: 'war', era: '20th-century',
    theater: 'ボスニア・ヘルツェゴビナ',
    mapHighlight: 'eastern-europe',
    markers: [
      { coordinates: [18.4, 43.8], label: 'サラエボ（包囲1425日）', isMain: true },
      { coordinates: [19.3, 44.1], label: 'スレブレニツァ（虐殺1995.7）', isMain: true },
      { coordinates: [17.8, 43.3], label: 'モスタル（橋破壊1993）' },
      { coordinates: [20.5, 44.8], label: 'ベオグラード（セルビア）', enemy: true },
    ],
    weight: 2,
    tags: ['民族浄化', 'ナショナリズム', '宗教対立', '権力真空'],
    ideologies: ['民族自決', 'ナショナリズム'],
    causes: [],
    influences: ['kosovo-war'],
  },
  {
    id: 'balkan-wars',
    year: 1912, endYear: 1913,
    name: 'バルカン戦争',
    region: 0, type: 'war', era: '20th-century',
    theater: 'バルカン半島',
    mapHighlight: 'eastern-europe',
    markers: [
      { coordinates: [23.3, 42.7], label: 'ソフィア（ブルガリア）', isMain: true },
      { coordinates: [28.9, 41.3], label: 'コンスタンティノープル直前（撤退）', isMain: true },
      { coordinates: [21.4, 42.0], label: 'スコピエ（マケドニア争奪）' },
      { coordinates: [28.9, 41.0], label: 'オスマン帝国（バルカン領土喪失）', enemy: true },
      { coordinates: [18.4, 43.8], label: 'サラエボ（1914火種の地）' },
    ],
    cotenLinks: [
      { title: 'オスマン帝国編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E3%82%AA%E3%82%B9%E3%83%9E%E3%83%B3%E5%B8%9D%E5%9B%BD' },
    ],
    weight: 2,
    tags: ['ナショナリズム', '帝国衰退', '同盟暴走'],
    ideologies: ['民族自決', '汎スラブ主義', 'ナショナリズム'],
    causes: ['russo-turkish-war-1877', 'greek-independence-war'],
    influences: ['world-war-1'],
  },
  {
    id: 'irish-independence-war',
    year: 1919, endYear: 1921,
    name: 'アイルランド独立戦争',
    region: 0, type: 'colonial', era: '20th-century',
    theater: 'アイルランド全島',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [-6.3, 53.3], label: 'ダブリン（蜂起・首都）', isMain: true },
      { coordinates: [-8.5, 51.9], label: 'コーク（IRA最大拠点）', isMain: true },
      { coordinates: [-6.0, 54.6], label: 'ベルファスト（北部・英連合派）', enemy: true },
      { coordinates: [-0.1, 51.5], label: 'ロンドン（英国）', enemy: true },
      { coordinates: [-6.3, 53.3], label: 'クロークパーク（血の日曜1920.11）' },
    ],
    weight: 1,
    tags: ['植民地解放', 'ナショナリズム', '宗教対立'],
    ideologies: ['民族自決', 'ナショナリズム'],
    causes: ['world-war-1'],
    influences: [],
  },
  {
    id: 'mexican-revolution',
    year: 1910, endYear: 1920,
    name: 'メキシコ革命',
    region: 3, type: 'revolution', era: '20th-century',
    theater: 'メキシコ全土',
    mapHighlight: 'north-america',
    markers: [
      { coordinates: [-99.1, 19.4], label: 'メキシコ・シティ（首都・政権争奪）', isMain: true },
      { coordinates: [-106.1, 28.6], label: 'チワワ（パンチョ・ビリャ拠点）', isMain: true },
      { coordinates: [-99.0, 18.7], label: 'モレロス州（サパタ・農民革命）' },
      { coordinates: [-77.0, 38.9], label: '米国（ウィルソン・ピアース介入）', enemy: true },
      { coordinates: [-106.5, 31.7], label: 'シウダー・フアレス（マデロ蜂起1910.11）' },
    ],
    weight: 1,
    tags: ['革命', '経済危機', 'ナショナリズム'],
    ideologies: ['農民革命', 'ナショナリズム'],
    causes: [],
    influences: [],
  },
  {
    id: 'world-war-1',
    year: 1914, endYear: 1918,
    name: '第一次世界大戦',
    region: 0, type: 'war', era: '20th-century',
    theater: '西部戦線・東部戦線・中東・海洋',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [18.4, 43.8], label: 'サラエボ（暗殺・1914）', isMain: true },
      { coordinates: [5.4, 49.2], label: 'ヴェルダン（1916消耗戦）', isMain: true },
      { coordinates: [-0.5, 50.0], label: 'ソンム川（1916・初日57470名死傷）' },
      { coordinates: [13.4, 52.5], label: 'ベルリン（独）', enemy: true },
      { coordinates: [2.3, 48.9], label: 'パリ（仏）', ally: true },
    ],
    cotenLinks: [
      { title: '第一次世界大戦編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E7%AC%AC%E4%B8%80%E6%AC%A1%E4%B8%96%E7%95%8C%E5%A4%A7%E6%88%A6' },
      { title: 'ケマル・アタテュルク編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E3%82%B1%E3%83%9E%E3%83%AB%E3%82%A2%E3%82%BF%E3%83%86%E3%83%A5%E3%83%AB%E3%82%AF' },
    ],
    weight: 3,
    tags: ['同盟暴走', 'ナショナリズム', '誤算・誤認知', '帝国衰退', '軍事革命'],
    ideologies: ['ナショナリズム', '汎ゲルマン主義', '汎スラブ主義', '帝国主義'],
    causes: ['balkan-wars', 'franco-prussian-war', 'russo-turkish-war-1877'],
    influences: ['russian-revolution', 'world-war-2-europe', 'irish-independence-war', 'mexican-revolution', 'greek-civil-war', 'russian-civil-war', 'first-arab-israeli-war'],
  },
  {
    id: 'russian-revolution',
    year: 1917, endYear: 1918,
    name: 'ロシア革命',
    region: 0, type: 'revolution', era: '20th-century',
    theater: 'ロシア全域',
    mapHighlight: 'eastern-europe',
    markers: [
      { coordinates: [30.3, 59.9], label: 'ペトログラード（二月・十月革命）', isMain: true },
      { coordinates: [37.6, 55.8], label: 'モスクワ（首都移転）' },
      { coordinates: [44.5, 48.7], label: 'ツァリーツィン（内戦激戦）' },
      { coordinates: [60.6, 56.8], label: 'エカテリンブルク（皇帝処刑）' },
    ],
    weight: 3,
    tags: ['革命', '経済危機', 'ナショナリズム'],
    ideologies: ['共産主義', 'マルクス・レーニン主義'],
    causes: ['world-war-1', 'russo-japanese-war'],
    influences: ['russian-civil-war', 'chinese-civil-war', 'spanish-civil-war'],
  },
  {
    id: 'second-italo-ethiopian-war',
    year: 1935, endYear: 1936,
    name: '第二次エチオピア戦争',
    region: 2, type: 'colonial', era: '20th-century',
    theater: 'エチオピア（アビシニア）',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [38.7, 9.0], label: 'アディスアベバ（占領1936.5）', isMain: true },
      { coordinates: [39.5, 12.8], label: 'マイチャウ（最終戦・毒ガス使用1936.3）', isMain: true },
      { coordinates: [38.9, 15.3], label: 'エリトリア（伊植民地・出撃基地）' },
      { coordinates: [12.5, 41.9], label: 'ローマ（ムッソリーニ）', enemy: true },
      { coordinates: [-0.1, 51.5], label: '英・仏（国際連盟制裁失敗）', ally: true },
    ],
    weight: 1,
    tags: ['植民地解放', 'ナショナリズム', '帝国衰退'],
    ideologies: ['ファシズム', '帝国主義'],
    causes: [],
    influences: ['world-war-2-europe', 'ethiopian-civil-war'],
  },
  {
    id: 'spanish-civil-war',
    year: 1936, endYear: 1939,
    name: 'スペイン内戦',
    region: 0, type: 'revolution', era: '20th-century',
    theater: 'スペイン全域',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [-3.7, 40.4], label: 'マドリード（首都・共和国側）', isMain: true },
      { coordinates: [-2.6, 43.3], label: 'ゲルニカ（独空軍爆撃1937）', isMain: true },
      { coordinates: [2.2, 41.4], label: 'バルセロナ（陥落1939）' },
      { coordinates: [13.4, 52.5], label: 'ベルリン（独・支援）', ally: false, enemy: true },
      { coordinates: [12.5, 41.9], label: 'ローマ（伊・支援）', enemy: true },
    ],
    weight: 2,
    tags: ['革命', '情報戦・プロパガンダ', '冷戦構造'],
    ideologies: ['ファシズム', '共産主義', 'アナキズム'],
    causes: ['russian-revolution'],
    influences: ['world-war-2-europe'],
  },
  {
    id: 'winter-war',
    year: 1939, endYear: 1940,
    name: '冬戦争（ソ連・フィンランド戦争）',
    region: 0, type: 'war', era: '20th-century',
    theater: 'カレリア地峡・フィンランド東部',
    mapHighlight: 'eastern-europe',
    markers: [
      { coordinates: [25.0, 60.2], label: 'ヘルシンキ（フィンランド）', isMain: true },
      { coordinates: [28.7, 60.4], label: 'マンネルヘイム線（防衛線）', isMain: true },
      { coordinates: [30.3, 59.9], label: 'レニングラード（ソ連目的地）', enemy: true },
      { coordinates: [29.0, 64.9], label: 'スオムッサルミ（包囲撃破）' },
      { coordinates: [37.6, 55.8], label: 'モスクワ（スターリン）', enemy: true },
    ],
    weight: 1,
    tags: ['ナショナリズム', '誤算・誤認知'],
    ideologies: ['共産主義', 'ナショナリズム'],
    causes: ['world-war-2-europe'],
    influences: [],
  },
  {
    id: 'world-war-2-europe',
    year: 1939, endYear: 1945,
    name: '第二次世界大戦（欧州）',
    region: 0, type: 'war', era: '20th-century',
    theater: 'ヨーロッパ全域・北アフリカ',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [13.4, 52.5], label: 'ベルリン（独・陥落1945）', isMain: true },
      { coordinates: [44.5, 48.7], label: 'スターリングラード（1942-43転換点）', isMain: true },
      { coordinates: [-0.6, 49.4], label: 'ノルマンディー（Dデイ1944）', isMain: true },
      { coordinates: [2.3, 48.9], label: 'パリ（解放1944）', ally: true },
      { coordinates: [19.2, 50.0], label: 'アウシュヴィッツ（ホロコースト）' },
    ],
    cotenLinks: [
      { title: 'ヒトラー編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E3%83%92%E3%83%88%E3%83%A9%E3%83%BC' },
    ],
    weight: 3,
    tags: ['ナショナリズム', '経済危機', '民族浄化', '指導者個人要因', '同盟暴走', '軍事革命'],
    ideologies: ['ナチズム', 'ファシズム', '共産主義', '反共主義'],
    causes: ['world-war-1', 'second-italo-ethiopian-war', 'spanish-civil-war'],
    influences: ['pacific-war', 'first-arab-israeli-war', 'greek-civil-war', 'first-indochina-war', 'korean-war'],
  },
  {
    id: 'pacific-war',
    year: 1941, endYear: 1945,
    name: '太平洋戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: '太平洋・東アジア・東南アジア',
    mapHighlight: 'east-asia',
    markers: [
      { coordinates: [139.7, 35.7], label: '東京（大本営）', enemy: true },
      { coordinates: [-157.8, 21.3], label: 'パールハーバー奇襲（1941）', isMain: true },
      { coordinates: [-177.4, 28.2], label: 'ミッドウェー海戦（1942転換）', isMain: true },
      { coordinates: [127.7, 26.3], label: '沖縄（1945・民間人12万死）' },
      { coordinates: [132.5, 34.4], label: '広島・長崎（原爆1945）', isMain: true },
    ],
    weight: 3,
    tags: ['ナショナリズム', '資源争奪', '核抑止', '指導者個人要因', '軍事革命', '海洋覇権'],
    ideologies: ['軍国主義', '大東亜共栄圏', 'ナショナリズム'],
    causes: ['second-sino-japanese-war', 'world-war-2-europe'],
    influences: ['chinese-civil-war', 'korean-war', 'first-indochina-war', 'malayan-emergency', 'burmese-independence-war'],
  },
  {
    id: 'korean-war',
    year: 1950, endYear: 1953,
    name: '朝鮮戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: '朝鮮半島全域',
    mapHighlight: 'east-asia',
    markers: [
      { coordinates: [125.7, 39.0], label: '平壌（北朝鮮首都）', enemy: true },
      { coordinates: [126.9, 37.6], label: 'ソウル（三度陥落と奪回）', isMain: true },
      { coordinates: [126.7, 37.5], label: '仁川（マッカーサー上陸1950）' },
      { coordinates: [116.4, 39.9], label: '中国（1950年秋介入）', enemy: true },
      { coordinates: [-77.0, 38.9], label: '米国（国連軍主力）', ally: true },
    ],
    weight: 3,
    tags: ['冷戦構造', 'ナショナリズム', '誤算・誤認知', '核抑止'],
    ideologies: ['共産主義', '反共主義'],
    causes: ['chinese-civil-war', 'pacific-war', 'world-war-2-europe'],
    influences: ['vietnam-war'],
  },
  {
    id: 'second-indo-pakistani-war',
    year: 1965, endYear: 1965,
    name: '第二次印パ戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: 'カシミール・パンジャブ国境',
    mapHighlight: 'south-asia',
    markers: [
      { coordinates: [74.8, 34.1], label: 'カシミール（潜入作戦・チョットラ作戦）', isMain: true },
      { coordinates: [74.3, 31.5], label: 'ラホール戦線（印軍越境）', isMain: true },
      { coordinates: [77.2, 28.6], label: 'デリー（印・シャストリ首相）', ally: true },
      { coordinates: [67.0, 24.9], label: 'カラチ（パ・アユーブ・カーン）', enemy: true },
      { coordinates: [69.3, 41.3], label: 'タシケント（停戦合意）' },
    ],
    weight: 1,
    tags: ['ナショナリズム', '宗教対立'],
    ideologies: ['ナショナリズム'],
    causes: ['first-indo-pakistani-war'],
    influences: ['bangladesh-liberation-war'],
  },
  {
    id: 'vietnam-war',
    year: 1955, endYear: 1975,
    name: 'ベトナム戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: 'ベトナム・ラオス・カンボジア',
    mapHighlight: 'southeast-asia',
    markers: [
      { coordinates: [105.8, 21.0], label: 'ハノイ（北ベトナム）', enemy: true },
      { coordinates: [106.7, 10.8], label: 'サイゴン（南ベトナム首都・陥落1975）', isMain: true },
      { coordinates: [107.1, 16.9], label: 'ケサン基地（激戦1968）' },
      { coordinates: [105.0, 15.0], label: 'ホーチミンルート（補給路）' },
      { coordinates: [-77.0, 38.9], label: '米国（50万人派兵）', ally: true },
    ],
    weight: 3,
    tags: ['冷戦構造', '植民地解放', 'ナショナリズム', '情報戦・プロパガンダ', '海洋覇権'],
    ideologies: ['共産主義', '反共主義', '民族自決'],
    causes: ['first-indochina-war', 'korean-war'],
    influences: ['sino-vietnamese-war', 'cambodian-genocide'],
  },
  {
    id: 'bangladesh-liberation-war',
    year: 1971, endYear: 1971,
    name: 'バングラデシュ独立戦争（第三次印パ戦争）',
    region: 1, type: 'revolution', era: '20th-century',
    theater: '東パキスタン（現バングラデシュ）',
    mapHighlight: 'south-asia',
    markers: [
      { coordinates: [90.4, 23.7], label: 'ダッカ（首都・占領→解放）', isMain: true },
      { coordinates: [77.2, 28.6], label: 'デリー（インド軍介入）', ally: true },
      { coordinates: [67.0, 24.9], label: 'カラチ（西パキスタン）', enemy: true },
      { coordinates: [91.8, 22.3], label: 'チッタゴン（虐殺現場）' },
      { coordinates: [37.6, 55.8], label: 'モスクワ（印支援）', ally: true },
    ],
    weight: 2,
    tags: ['ナショナリズム', '民族浄化', '植民地解放'],
    ideologies: ['民族自決', 'ベンガル民族主義'],
    causes: ['first-indo-pakistani-war', 'second-indo-pakistani-war'],
    influences: [],
  },
  {
    id: 'cambodian-genocide',
    year: 1975, endYear: 1979,
    name: 'カンボジア大虐殺（クメール・ルージュ統治）',
    region: 1, type: 'revolution', era: '20th-century',
    theater: 'カンボジア全土',
    mapHighlight: 'southeast-asia',
    markers: [
      { coordinates: [104.9, 11.6], label: 'プノンペン（強制疎開1975.4.17）', isMain: true },
      { coordinates: [104.9, 11.6], label: 'トゥール・スレン刑務所（S-21）', isMain: true },
      { coordinates: [104.9, 11.5], label: 'チュンエク（キリングフィールド）' },
      { coordinates: [105.8, 21.0], label: 'ベトナム（侵攻1978.12）', ally: true },
      { coordinates: [116.4, 39.9], label: '中国（クメール支援）', enemy: true },
    ],
    weight: 2,
    tags: ['革命', '民族浄化', '指導者個人要因'],
    ideologies: ['毛沢東主義', '共産主義', '原理主義'],
    causes: ['vietnam-war'],
    influences: [],
  },
  {
    id: 'falklands-war',
    year: 1982, endYear: 1982,
    name: 'フォークランド紛争',
    region: 3, type: 'war', era: '20th-century',
    theater: '南大西洋・フォークランド諸島',
    mapHighlight: 'south-america',
    markers: [
      { coordinates: [-57.9, -51.7], label: 'ポート・スタンリー（諸島首都）', isMain: true },
      { coordinates: [-58.4, -34.6], label: 'ブエノスアイレス（亜）', enemy: true },
      { coordinates: [-0.1, 51.5], label: 'ロンドン（英・サッチャー）', ally: true },
      { coordinates: [-59.0, -51.8], label: 'グースグリーン（陸上戦）' },
      { coordinates: [-59.5, -52.0], label: 'ベルグラノ号撃沈（1982.5）' },
    ],
    weight: 1,
    tags: ['ナショナリズム', '指導者個人要因', '資源争奪', '海洋覇権'],
    ideologies: ['ナショナリズム'],
    causes: [],
    influences: [],
  },
  {
    id: 'sino-indian-war',
    year: 1962, endYear: 1962,
    name: '中印戦争',
    region: 1, type: 'war', era: '20th-century',
    theater: 'ヒマラヤ国境（ラダック・アルナチャル・プラデシュ）',
    mapHighlight: 'south-asia',
    markers: [
      { coordinates: [79.5, 34.5], label: 'アクサイチン（西部戦線）', isMain: true },
      { coordinates: [91.9, 27.6], label: 'タワン・ボムディラ（東部戦線・1962.10-11）', isMain: true },
      { coordinates: [116.4, 39.9], label: '北京（毛沢東）', enemy: true },
      { coordinates: [77.2, 28.6], label: 'デリー（ネルー）', ally: true },
      { coordinates: [37.6, 55.8], label: 'ソ連（中立傾向、印に間接支援）' },
    ],
    weight: 1,
    tags: ['ナショナリズム', '資源争奪', '誤算・誤認知'],
    ideologies: ['共産主義', 'ナショナリズム'],
    causes: ['chinese-civil-war'],
    influences: [],
  },
  {
    id: 'biafra-war',
    year: 1967, endYear: 1970,
    name: 'ナイジェリア・ビアフラ戦争',
    region: 2, type: 'revolution', era: '20th-century',
    theater: 'ナイジェリア東部（ビアフラ）',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [7.5, 6.5], label: 'エヌグ→アバ（ビアフラ首都変遷）', isMain: true },
      { coordinates: [3.4, 6.5], label: 'ラゴス（ナイジェリア連邦首都）', enemy: true },
      { coordinates: [7.0, 4.8], label: 'ポートハーコート（陥落1968.5）' },
      { coordinates: [7.3, 5.5], label: 'ウムアヒア（最後の首都・飢饉中心）', isMain: true },
      { coordinates: [-0.1, 51.5], label: '英国（連邦支援）', enemy: true },
    ],
    weight: 1,
    tags: ['民族浄化', '植民地解放', '資源争奪'],
    ideologies: ['民族自決', 'ナショナリズム'],
    causes: [],
    influences: [],
  },
  {
    id: 'six-day-war',
    year: 1967, endYear: 1967,
    name: '第三次中東戦争（六日間戦争）',
    region: 2, type: 'war', era: '20th-century',
    theater: 'シナイ半島・ヨルダン川西岸・ゴラン高原',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [34.8, 32.1], label: 'テルアビブ（イスラエル）', isMain: true },
      { coordinates: [35.2, 31.8], label: 'エルサレム（東エルサレム占領）', isMain: true },
      { coordinates: [33.5, 29.5], label: 'シナイ半島（エジプト軍撃破）' },
      { coordinates: [35.7, 32.8], label: 'ゴラン高原（シリアから奪取）' },
      { coordinates: [35.5, 32.0], label: 'ヨルダン川西岸（占領）' },
    ],
    weight: 2,
    tags: ['ナショナリズム', '安全保障ジレンマ', '誤算・誤認知', '宗教対立'],
    ideologies: ['シオニズム', 'アラブ民族主義'],
    causes: ['first-arab-israeli-war', 'suez-crisis'],
    influences: ['yom-kippur-war', 'lebanese-civil-war', 'gaza-war'],
  },
  {
    id: 'yom-kippur-war',
    year: 1973, endYear: 1973,
    name: '第四次中東戦争（ヨム・キプール戦争）',
    region: 2, type: 'war', era: '20th-century',
    theater: 'シナイ半島・ゴラン高原',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [34.8, 32.1], label: 'テルアビブ（イスラエル）', isMain: true },
      { coordinates: [32.5, 30.0], label: 'スエズ運河（エジプト渡河）', isMain: true },
      { coordinates: [35.7, 32.8], label: 'ゴラン高原（シリア攻勢）' },
      { coordinates: [31.2, 30.1], label: 'カイロ（エジプト）', enemy: true },
      { coordinates: [36.3, 33.5], label: 'ダマスカス（シリア）', enemy: true },
    ],
    weight: 2,
    tags: ['ナショナリズム', '安全保障ジレンマ', '資源争奪', '宗教対立'],
    ideologies: ['シオニズム', 'アラブ民族主義'],
    causes: ['six-day-war'],
    influences: ['gaza-war'],
  },
  {
    id: 'iranian-revolution',
    year: 1978, endYear: 1979,
    name: 'イラン革命',
    region: 2, type: 'revolution', era: '20th-century',
    theater: 'イラン全土',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [51.4, 35.7], label: 'テヘラン（首都・革命中心）', isMain: true },
      { coordinates: [50.9, 34.6], label: 'コム（ホメイニ拠点）', isMain: true },
      { coordinates: [46.3, 38.1], label: 'タブリーズ（蜂起発端）' },
      { coordinates: [-77.0, 38.9], label: '米国（パーレビ亡命受入）', enemy: true },
      { coordinates: [2.3, 48.9], label: 'パリ（ホメイニ亡命地）' },
    ],
    weight: 3,
    tags: ['革命', '宗教対立', '指導者個人要因'],
    ideologies: ['イスラム主義', '原理主義', 'シーア派'],
    causes: [],
    influences: ['iran-iraq-war', 'syrian-civil-war', 'yemen-civil-war'],
  },
  {
    id: 'east-timor-occupation',
    year: 1975, endYear: 1999,
    name: '東ティモール独立闘争',
    region: 1, type: 'colonial', era: '20th-century',
    theater: '東ティモール',
    mapHighlight: 'southeast-asia',
    markers: [
      { coordinates: [125.6, -8.6], label: 'ディリ（首都・侵攻1975.12.7）', isMain: true },
      { coordinates: [125.1, -8.9], label: 'バリボ（豪州ジャーナリスト殺害）' },
      { coordinates: [125.6, -8.6], label: 'サンタクルス墓地（虐殺1991.11）', isMain: true },
      { coordinates: [106.8, -6.2], label: 'ジャカルタ（インドネシア政府）', enemy: true },
      { coordinates: [125.6, -8.6], label: '住民投票（1999.8.30）' },
    ],
    weight: 1,
    tags: ['植民地解放', '民族浄化', 'ナショナリズム'],
    ideologies: ['民族自決', '反共主義'],
    causes: [],
    influences: [],
  },
  {
    id: 'nicaraguan-revolution',
    year: 1978, endYear: 1979,
    name: 'ニカラグア・サンディニスタ革命',
    region: 3, type: 'revolution', era: '20th-century',
    theater: 'ニカラグア全土',
    mapHighlight: 'north-america',
    markers: [
      { coordinates: [-86.3, 12.1], label: 'マナグア（首都・1979.7.19入城）', isMain: true },
      { coordinates: [-85.9, 12.9], label: 'マタガルパ・エステリ（最終攻勢）', isMain: true },
      { coordinates: [-86.0, 11.9], label: 'グラナダ（ソモサ要塞）' },
      { coordinates: [-86.1, 12.0], label: 'サンディニスタ（FSLN）拠点' },
      { coordinates: [-77.0, 38.9], label: '米国（ソモサ→コントラ支援）', enemy: true },
    ],
    weight: 1,
    tags: ['革命', '冷戦構造'],
    ideologies: ['共産主義', '反帝国主義'],
    causes: ['cuban-revolution'],
    influences: ['salvadoran-civil-war'],
  },
  {
    id: 'colombian-conflict',
    year: 1964, endYear: 2016,
    name: 'コロンビア内戦（FARC戦争）',
    region: 3, type: 'revolution', era: '20th-century',
    theater: 'コロンビア全土',
    mapHighlight: 'south-america',
    markers: [
      { coordinates: [-74.1, 4.7], label: 'ボゴタ（首都・2016和平合意）', isMain: true },
      { coordinates: [-75.5, 3.5], label: 'マルケタリア（FARC発祥地1964）', isMain: true },
      { coordinates: [-74.5, 7.0], label: 'マグダレナ・メディオ（パラ拠点）' },
      { coordinates: [-75.6, 5.1], label: 'カリ・メデジン（麻薬カルテル拠点）' },
      { coordinates: [-77.0, 38.9], label: '米国（プラン・コロンビア2000〜）', ally: true },
    ],
    weight: 1,
    tags: ['革命', '冷戦構造', '資源争奪'],
    ideologies: ['共産主義', 'マルクス・レーニン主義'],
    causes: [],
    influences: [],
  },
  {
    id: 'soviet-afghan-war',
    year: 1979, endYear: 1989,
    name: 'ソ連・アフガニスタン戦争',
    region: 2, type: 'war', era: '20th-century',
    theater: 'アフガニスタン全域',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [69.2, 34.5], label: 'カブール（首都・ソ連占領）', isMain: true },
      { coordinates: [69.0, 35.5], label: 'サランパス（補給路）' },
      { coordinates: [65.7, 31.6], label: 'カンダハル（ムジャヒディーン拠点）' },
      { coordinates: [37.6, 55.8], label: 'モスクワ（ソ連）', enemy: true },
      { coordinates: [-77.0, 38.9], label: '米（CIA・武器支援）', ally: true },
    ],
    weight: 2,
    tags: ['冷戦構造', '宗教対立', '誤算・誤認知'],
    ideologies: ['共産主義', 'イスラム主義'],
    causes: [],
    influences: ['afghanistan-war', 'chechen-wars', 'iraq-war'],
  },
  {
    id: 'gulf-war',
    year: 1990, endYear: 1991,
    name: '湾岸戦争',
    region: 2, type: 'war', era: '20th-century',
    theater: 'クウェート・イラク南部',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [47.9, 29.4], label: 'クウェート（イラクが侵攻）', isMain: true },
      { coordinates: [44.4, 33.3], label: 'バグダード（空爆）', enemy: true },
      { coordinates: [47.8, 30.5], label: 'バスラ（地上戦）' },
      { coordinates: [-77.0, 38.9], label: '米国（多国籍軍主力）', ally: true },
      { coordinates: [46.7, 24.7], label: 'サウジアラビア（出撃基地）', ally: true },
    ],
    weight: 2,
    tags: ['資源争奪', 'ナショナリズム', '誤算・誤認知'],
    ideologies: ['バース主義', '新世界秩序'],
    causes: ['iran-iraq-war'],
    influences: ['iraq-war', 'afghanistan-war'],
  },
  {
    id: 'russian-civil-war',
    year: 1918, endYear: 1922,
    name: 'ロシア内戦',
    region: 0, type: 'war', era: '20th-century',
    theater: 'ロシア全土・シベリア・南ロシア・北極海沿岸',
    mapHighlight: 'eastern-europe',
    markers: [
      { coordinates: [37.6, 55.8], label: 'モスクワ（ボリシェヴィキ・赤軍本拠）', isMain: true },
      { coordinates: [44.5, 48.7], label: 'ツァリーツィン（1918-19赤軍防衛戦）', isMain: true },
      { coordinates: [73.4, 54.9], label: 'オムスク（コルチャーク白軍政府）', enemy: true },
      { coordinates: [39.7, 47.2], label: 'ロストフ（デニーキン・南ロシア軍）', enemy: true },
      { coordinates: [40.5, 64.5], label: 'アルハンゲリスク（連合国軍北部干渉）' },
      { coordinates: [132.7, 43.1], label: 'ウラジオストク（チェコ軍団・日本軍干渉）' },
    ],
    weight: 2,
    tags: ['革命', '冷戦構造', '権力真空'],
    ideologies: ['共産主義', 'マルクス・レーニン主義', '反共主義'],
    causes: ['russian-revolution', 'world-war-1'],
    influences: ['winter-war', 'world-war-2-europe'],
  },
  {
    id: 'philippine-american-war',
    year: 1899, endYear: 1902,
    name: '米比戦争',
    region: 1, type: 'colonial', era: '20th-century',
    theater: 'フィリピン群島（ルソン・サマール・ミンダナオ）',
    mapHighlight: 'southeast-asia',
    markers: [
      { coordinates: [120.98, 14.6], label: 'マニラ（1899.2.4開戦・米軍占領）', isMain: true },
      { coordinates: [120.59, 15.48], label: 'マロロス（アギナルド共和国首都）', isMain: true },
      { coordinates: [120.8, 16.6], label: 'パラナン（1901.3.23アギナルド捕縛）' },
      { coordinates: [125.38, 11.11], label: 'バランギガ（1901.9.28米兵殺害事件）' },
      { coordinates: [121.06, 13.95], label: 'バタンガス（マルバル降伏1902.4）' },
      { coordinates: [-77.0, 38.9], label: 'ワシントン（マッキンリー・T.ルーズベルト政権）', enemy: true },
    ],
    weight: 1,
    tags: ['植民地解放', 'ナショナリズム', '帝国衰退'],
    ideologies: ['帝国主義', '民族自決', 'ナショナリズム'],
    causes: ['spanish-american-war'],
    influences: [],
  },
  {
    id: 'burmese-independence-war',
    year: 1948, endYear: 2025,
    name: 'ミャンマー内戦',
    region: 1, type: 'colonial', era: '20th-century',
    theater: 'ミャンマー全土（ビルマ族中央・カレン州・シャン高原・カチン州）',
    mapHighlight: 'southeast-asia',
    markers: [
      { coordinates: [96.16, 16.8], label: 'ラングーン（首都・1948.1.4独立宣言）', isMain: true },
      { coordinates: [96.1, 16.9], label: 'インセイン（1949.1カレン軍包囲戦）', isMain: true },
      { coordinates: [97.04, 20.78], label: 'タウンジー（1949.8カレン軍占領）' },
      { coordinates: [96.49, 17.34], label: 'ペグー（1948.4ビルマ共産党武装蜂起）' },
      { coordinates: [99.0, 21.5], label: 'シャン州（国民党残党流入・少数民族反乱）' },
      { coordinates: [-0.1, 51.5], label: 'ロンドン（英・ヌー＝アトリー協定1947）', ally: true },
    ],
    weight: 1,
    tags: ['植民地解放', 'ナショナリズム', '民族浄化'],
    ideologies: ['民族自決', '共産主義', 'ナショナリズム'],
    causes: ['pacific-war'],
    influences: ['myanmar-civil-war'],
  },
  {
    id: 'kenyan-independence-war',
    year: 1952, endYear: 1960,
    name: 'ケニア独立戦争（マウマウ蜂起）',
    region: 2, type: 'colonial', era: '20th-century',
    theater: '中央ケニア・アバーデア山地・ケニア山麓',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [36.82, -1.29], label: 'ナイロビ（1952.10.20非常事態宣言）', isMain: true },
      { coordinates: [36.7, -0.4], label: 'アバーデア森林（マウマウ拠点）', isMain: true },
      { coordinates: [37.31, -0.42], label: 'ニエリ（キクユ族中心地・収容所）' },
      { coordinates: [38.5, 0.05], label: 'ホラ収容所（1959虐待事件）' },
      { coordinates: [36.95, -1.18], label: 'カピティ（1953.4ラリ虐殺）' },
      { coordinates: [-0.1, 51.5], label: 'ロンドン（英植民地省）', enemy: true },
    ],
    weight: 1,
    tags: ['植民地解放', 'ナショナリズム', '資源争奪'],
    ideologies: ['反植民地主義', '民族自決'],
    causes: [],
    influences: [],
  },
  {
    id: 'ethiopian-civil-war',
    year: 1974, endYear: 1991,
    name: 'エチオピア内戦',
    region: 2, type: 'war', era: '20th-century',
    theater: 'エチオピア全土・エリトリア・ティグレ・オガデン',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [38.74, 9.03], label: 'アディスアベバ（1974.9.12デルグ革命）', isMain: true },
      { coordinates: [38.94, 14.11], label: 'アスマラ（エリトリア人民解放戦線EPLF）', isMain: true },
      { coordinates: [38.32, 14.12], label: 'シレ（1989.2 TPLF決戦勝利）' },
      { coordinates: [39.47, 13.49], label: 'メケレ（ティグレ州都）' },
      { coordinates: [44.08, 9.56], label: 'オガデン（1977-78ソマリアと戦争）' },
      { coordinates: [37.62, 55.75], label: 'モスクワ（ソ連・キューバ軍事支援）', ally: true },
    ],
    weight: 1,
    tags: ['革命', '冷戦構造', '民族浄化'],
    ideologies: ['共産主義', '民族自決'],
    causes: ['second-italo-ethiopian-war'],
    influences: ['tigray-war', 'somali-civil-war'],
  },

  /* ─────────────────── 現代（2000-） ─────────────────── */

  {
    id: 'afghanistan-war',
    year: 2001, endYear: 2021,
    name: 'アフガニスタン戦争',
    region: 2, type: 'war', era: 'contemporary',
    theater: 'アフガニスタン全域',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [69.2, 34.5], label: 'カブール（首都・タリバン陥落→奪還）', isMain: true },
      { coordinates: [65.7, 31.6], label: 'カンダハル（タリバン本拠）', enemy: true },
      { coordinates: [70.4, 34.0], label: 'トラボラ（ビンラディン逃亡）' },
      { coordinates: [-77.0, 38.9], label: '米国・NATO（主力）', ally: true },
      { coordinates: [64.5, 31.4], label: 'ヘルマンド州（激戦区）' },
    ],
    weight: 2,
    tags: ['宗教対立', '誤算・誤認知', '権力真空', '情報戦・プロパガンダ'],
    ideologies: ['イスラム主義', '原理主義', '民主主義'],
    causes: ['soviet-afghan-war', 'gulf-war'],
    influences: ['iraq-war', 'syrian-civil-war'],
  },
  {
    id: 'iraq-war',
    year: 2003, endYear: 2011,
    name: 'イラク戦争',
    region: 2, type: 'war', era: 'contemporary',
    theater: 'イラク全域',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [44.4, 33.3], label: 'バグダード（陥落2003.4.9）', isMain: true },
      { coordinates: [43.7, 34.6], label: 'ティクリート（フセイン拘束）' },
      { coordinates: [43.8, 33.4], label: 'ファルージャ（市街戦2004）', isMain: true },
      { coordinates: [47.8, 30.5], label: 'バスラ（英軍担当）' },
      { coordinates: [-77.0, 38.9], label: '米・英（有志連合）', ally: true },
    ],
    weight: 2,
    tags: ['誤算・誤認知', '情報戦・プロパガンダ', '資源争奪', '権力真空'],
    ideologies: ['新保守主義', '民主主義', 'バース主義'],
    causes: ['gulf-war', 'afghanistan-war'],
    influences: ['syrian-civil-war', 'yemen-civil-war'],
  },
  {
    id: 'boko-haram-insurgency',
    year: 2009, endYear: 2025,
    name: 'ボコ・ハラム反乱',
    region: 2, type: 'revolution', era: 'contemporary',
    theater: 'ナイジェリア北東部・チャド湖周辺',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [13.2, 11.8], label: 'マイドゥグリ（ボコ・ハラム発祥地）', isMain: true },
      { coordinates: [13.1, 10.6], label: 'チボク（女子生徒276人誘拐2014.4）', isMain: true },
      { coordinates: [12.6, 11.1], label: 'サンビサ森林（ジハーディスト拠点）' },
      { coordinates: [14.0, 13.5], label: 'チャド湖周辺（ISWAP支配地）' },
      { coordinates: [7.5, 9.1], label: 'アブジャ（ナイジェリア連邦首都）', enemy: true },
    ],
    weight: 1,
    tags: ['宗教対立', '権力真空', '植民地解放'],
    ideologies: ['イスラム主義', '原理主義'],
    causes: [],
    influences: ['mali-conflict'],
  },
  {
    id: 'libyan-civil-war',
    year: 2011, endYear: 2011,
    name: 'リビア内戦（カダフィ崩壊）',
    region: 2, type: 'revolution', era: 'contemporary',
    theater: 'リビア全土',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [13.2, 32.9], label: 'トリポリ（首都・カダフィ拠点）', isMain: true },
      { coordinates: [20.1, 32.1], label: 'ベンガジ（蜂起地）', isMain: true },
      { coordinates: [16.5, 31.2], label: 'シルテ（カダフィ殺害2011.10.20）' },
      { coordinates: [15.1, 32.4], label: 'ミスラタ（包囲戦）' },
      { coordinates: [-77.0, 38.9], label: 'NATO（空爆）', ally: true },
    ],
    weight: 1,
    tags: ['革命', '権力真空', '情報戦・プロパガンダ'],
    ideologies: ['アラブ民族主義', '民主主義', 'イスラム主義'],
    causes: ['iraq-war', 'kosovo-war'],
    influences: ['mali-conflict', 'syrian-civil-war'],
  },
  {
    id: 'yemen-civil-war',
    year: 2014, endYear: 2025,
    name: 'イエメン内戦',
    region: 2, type: 'war', era: 'contemporary',
    theater: 'イエメン全土・紅海',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [44.2, 15.4], label: 'サナア（フーシ派制圧2014.9）', isMain: true },
      { coordinates: [45.0, 12.8], label: 'アデン（暫定政府）', enemy: true },
      { coordinates: [42.9, 14.8], label: 'ホデイダ（紅海港・激戦）', isMain: true },
      { coordinates: [46.7, 24.7], label: 'リヤド（サウジ主導連合）', enemy: true },
      { coordinates: [51.4, 35.7], label: 'イラン（フーシ支援）', ally: true },
    ],
    weight: 1,
    tags: ['宗教対立', '権力真空', '資源争奪', '情報戦・プロパガンダ'],
    ideologies: ['イスラム主義', 'シーア派', 'スンナ派'],
    causes: ['iranian-revolution', 'iraq-war'],
    influences: [],
  },
  {
    id: 'nagorno-karabakh-2020',
    year: 2020, endYear: 2020,
    name: '第二次ナゴルノ・カラバフ戦争',
    region: 0, type: 'war', era: 'contemporary',
    theater: 'ナゴルノ・カラバフ',
    mapHighlight: 'eastern-europe',
    markers: [
      { coordinates: [46.7, 39.8], label: 'ステパナケルト（首都・砲撃）', isMain: true },
      { coordinates: [46.7, 39.8], label: 'シューシャ（陥落11.8）', isMain: true },
      { coordinates: [44.5, 40.2], label: 'エレバン（アルメニア）', enemy: true },
      { coordinates: [49.9, 40.4], label: 'バクー（アゼルバイジャン）', ally: true },
      { coordinates: [32.9, 39.9], label: 'アンカラ（トルコ・ドローン提供）', ally: true },
    ],
    weight: 1,
    tags: ['ナショナリズム', '民族浄化', '誤算・誤認知', '軍事革命'],
    ideologies: ['ナショナリズム', '民族自決'],
    causes: ['first-nagorno-karabakh-war'],
    influences: [],
  },
  {
    id: 'south-sudan-civil-war',
    year: 2013, endYear: 2025,
    name: '南スーダン内戦',
    region: 2, type: 'war', era: 'contemporary',
    theater: '南スーダン',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [31.6, 4.9], label: 'ジュバ（首都・キール政権）', isMain: true },
      { coordinates: [31.6, 6.2], label: 'ボル・マラカル（マチャール拠点）', isMain: true },
      { coordinates: [29.8, 9.2], label: 'ベンティウ（油田地帯）' },
      { coordinates: [32.5, 15.6], label: '北部ハルツーム（旧スーダン政府）', enemy: true },
      { coordinates: [-77.0, 38.9], label: '米国（独立支援→失望）', ally: true },
    ],
    weight: 1,
    tags: ['権力真空', '資源争奪', '民族浄化'],
    ideologies: ['民族自決', '民族主義'],
    causes: [],
    influences: ['sudan-civil-war-2023'],
  },
  {
    id: 'mali-conflict',
    year: 2012, endYear: 2025,
    name: 'マリ内戦（サヘル危機）',
    region: 2, type: 'war', era: 'contemporary',
    theater: 'マリ北部・サヘル全域',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [-8.0, 12.6], label: 'バマコ（首都・連続クーデター）', isMain: true },
      { coordinates: [-3.0, 16.8], label: 'トンブクトゥ（占領→奪還2013.1）', isMain: true },
      { coordinates: [-0.0, 16.3], label: 'ガオ・キダル（トゥアレグ・ジハーディスト拠点）' },
      { coordinates: [2.3, 48.9], label: 'パリ（仏軍セルバル作戦2013-22）', ally: true },
      { coordinates: [37.6, 55.8], label: 'モスクワ（ワグネル進出2021〜）', enemy: true },
    ],
    weight: 1,
    tags: ['宗教対立', '権力真空', '植民地解放', '資源争奪'],
    ideologies: ['イスラム主義', '民族自決'],
    causes: ['libyan-civil-war', 'boko-haram-insurgency'],
    influences: [],
  },
  {
    id: 'central-african-civil-war',
    year: 2012, endYear: 2025,
    name: '中央アフリカ内戦',
    region: 2, type: 'war', era: 'contemporary',
    theater: '中央アフリカ共和国',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [18.6, 4.4], label: 'バンギ（首都）', isMain: true },
      { coordinates: [20.0, 6.0], label: '北部（セレカ・ムスリム連合拠点）', isMain: true },
      { coordinates: [17.0, 4.0], label: '南西部（アンチ・バラカ・キリスト教民兵）' },
      { coordinates: [37.6, 55.8], label: 'ロシア（ワグネル進出2018〜）', ally: true },
      { coordinates: [2.3, 48.9], label: 'パリ（仏軍サンガリス2013-16）', ally: true },
    ],
    weight: 1,
    tags: ['権力真空', '宗教対立', '資源争奪'],
    ideologies: ['イスラム主義', 'キリスト教民兵主義'],
    causes: [],
    influences: [],
  },
  {
    id: 'syrian-civil-war',
    year: 2011, endYear: 2024,
    name: 'シリア内戦',
    region: 2, type: 'revolution', era: 'contemporary',
    theater: 'シリア全域',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [36.3, 33.5], label: 'ダマスカス（首都・政府側）', isMain: true },
      { coordinates: [36.7, 34.7], label: 'ホムス（反政府勢力拠点）' },
      { coordinates: [37.2, 36.2], label: 'アレッポ（最大激戦・2016陥落）', isMain: true },
      { coordinates: [38.9, 35.9], label: 'ラッカ（IS首都→2017解放）' },
      { coordinates: [37.6, 55.8], label: 'ロシア（政府支援）', ally: true },
    ],
    weight: 2,
    tags: ['革命', '宗教対立', '情報戦・プロパガンダ', '権力真空'],
    ideologies: ['バース主義', 'イスラム主義', 'アラブ民族主義'],
    causes: ['iraq-war', 'libyan-civil-war', 'iranian-revolution'],
    influences: ['gaza-war', 'ukraine-war'],
  },
  {
    id: 'myanmar-civil-war',
    year: 2021, endYear: 2025,
    name: 'ミャンマー内戦（クーデター後）',
    region: 1, type: 'revolution', era: 'contemporary',
    theater: 'ミャンマー全土',
    mapHighlight: 'southeast-asia',
    markers: [
      { coordinates: [96.1, 19.7], label: 'ネピドー（軍政首都）', isMain: true },
      { coordinates: [96.2, 16.8], label: 'ヤンゴン（旧首都・抗議中心）' },
      { coordinates: [97.5, 25.5], label: 'カチン州・カレン州（少数民族抵抗）', isMain: true },
      { coordinates: [95.0, 18.0], label: 'PDF（人民防衛軍）拠点' },
      { coordinates: [116.4, 39.9], label: '中国（軍政支援）', enemy: true },
    ],
    weight: 1,
    tags: ['革命', '民族浄化', '情報戦・プロパガンダ'],
    ideologies: ['民族自決', '民主主義', '軍国主義'],
    causes: ['burmese-independence-war'],
    influences: [],
  },
  {
    id: 'tigray-war',
    year: 2020, endYear: 2022,
    name: 'ティグレ戦争',
    region: 2, type: 'war', era: 'contemporary',
    theater: 'エチオピア北部・ティグレ州',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [39.5, 13.5], label: 'メケレ（ティグレ州都）', isMain: true },
      { coordinates: [38.7, 9.0], label: 'アディスアベバ（連邦政府）', enemy: true },
      { coordinates: [38.7, 14.1], label: 'アクスム（古代王都・虐殺）', isMain: true },
      { coordinates: [38.9, 15.3], label: 'エリトリア（連邦軍と共同作戦）', ally: true },
      { coordinates: [37.6, 12.6], label: 'デバルク（連邦軍進撃ライン）' },
    ],
    weight: 1,
    tags: ['民族浄化', 'ナショナリズム', '指導者個人要因'],
    ideologies: ['民族自決', 'ナショナリズム'],
    causes: ['ethiopian-civil-war'],
    influences: [],
  },
  {
    id: 'sudan-civil-war-2023',
    year: 2023, endYear: 2025,
    name: 'スーダン内戦',
    region: 2, type: 'war', era: 'contemporary',
    theater: 'スーダン全土',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [32.5, 15.6], label: 'ハルツーム（首都・激戦）', isMain: true },
      { coordinates: [24.0, 13.0], label: 'ダルフール（虐殺再発）', isMain: true },
      { coordinates: [32.5, 15.7], label: 'オムドゥルマン（双子都市）' },
      { coordinates: [37.2, 19.6], label: 'ポートスーダン（暫定首都）' },
      { coordinates: [54.4, 24.5], label: 'UAE（RSF支援疑惑）', enemy: true },
    ],
    weight: 1,
    tags: ['権力真空', '資源争奪', '民族浄化'],
    ideologies: ['イスラム主義', '民族主義'],
    causes: ['south-sudan-civil-war'],
    influences: [],
  },
  {
    id: 'gaza-war',
    year: 2023, endYear: 2025,
    name: 'ガザ戦争',
    region: 2, type: 'war', era: 'contemporary',
    theater: 'ガザ地区・イスラエル南部',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [34.8, 32.1], label: 'テルアビブ（イスラエル）', isMain: true },
      { coordinates: [34.5, 31.5], label: 'ガザ市（北部・地上侵攻）', isMain: true },
      { coordinates: [34.3, 31.3], label: 'ハーンユーニス・ラファ（南部）' },
      { coordinates: [35.2, 31.8], label: 'エルサレム' },
      { coordinates: [51.4, 35.7], label: 'テヘラン（イラン・支援）', enemy: true },
    ],
    weight: 2,
    tags: ['宗教対立', 'ナショナリズム', '情報戦・プロパガンダ', '誤算・誤認知'],
    ideologies: ['シオニズム', 'イスラム主義', 'アラブ民族主義'],
    causes: ['first-arab-israeli-war', 'six-day-war', 'yom-kippur-war'],
    influences: [],
  },
  {
    id: 'ukraine-war',
    year: 2022, endYear: 2025,
    name: 'ロシア・ウクライナ戦争',
    region: 0, type: 'war', era: 'contemporary',
    theater: 'ウクライナ全域',
    mapHighlight: 'eastern-europe',
    markers: [
      { coordinates: [30.5, 50.5], label: 'キーウ（首都・初期攻防）', isMain: true },
      { coordinates: [37.5, 47.1], label: 'マリウポリ（包囲・陥落2022.5）', isMain: true },
      { coordinates: [38.0, 48.6], label: 'バフムート（最長激戦）' },
      { coordinates: [32.6, 46.6], label: 'ヘルソン（解放2022.11）' },
      { coordinates: [37.6, 55.8], label: 'モスクワ（ロシア）', enemy: true },
    ],
    weight: 3,
    tags: ['ナショナリズム', '安全保障ジレンマ', '核抑止', '帝国衰退', '情報戦・プロパガンダ', '軍事革命'],
    ideologies: ['ナショナリズム', '汎スラブ主義', 'ロシア帝国回復主義'],
    causes: ['chechen-wars', 'syrian-civil-war'],
    influences: [],
  },
];

// 先史〜近世初期は別ファイルから読み込んでマージ
export const WARS: War[] = [
  ...WARS_PREHISTORIC,
  ...WARS_ANCIENT,
  ...WARS_ANCIENT_EXTRA,
  ...WARS_MEDIEVAL,
  ...WARS_MEDIEVAL_EXTRA,
  ...WARS_RENAISSANCE,
  ..._WARS_INLINE,
];

export const REGIONS = ['欧州', 'アジア', '中東・アフリカ', '南北米'] as const;
