import { War } from './types';
/** 追加戦争（既存にない主要戦争を補完） */
export const WARS_EXTRA: War[] = [
  {
    id: 'war-of-the-pacific',
    year: 1879, endYear: 1884,
    name: '太平洋戦争（硝石戦争）',
    region: 3, type: 'war', era: 'early-modern',
    theater: 'アタカマ砂漠・太平洋沿岸（チリ／ペルー／ボリビア）',
    mapHighlight: 'americas',
    markers: [
      { coordinates: [-70.40, -23.65], label: 'アントファガスタ（1879年チリ占領）', isMain: true },
      { coordinates: [-77.03, -12.05], label: 'リマ（1881年チリ軍占領）', isMain: true },
      { coordinates: [-70.25, -18.48], label: 'アリカ（1880年要塞戦）', enemy: true },
      { coordinates: [-68.15, -16.50], label: 'ラパス（ボリビア・海岸喪失）', enemy: true },
      { coordinates: [-70.65, -33.45], label: 'サンティアゴ（チリ首都）' },
    ],
    weight: 2,
    tags: ['資源争奪', 'ナショナリズム', '帝国衰退'],
    ideologies: ['ナショナリズム', '近代化主義'],
    causes: ['latin-american-independence'],
    influences: ['mexican-revolution'],
  },
  {
    id: 'polish-soviet-war',
    year: 1919, endYear: 1921,
    name: 'ポーランド・ソビエト戦争',
    region: 0, type: 'war', era: '20th-century',
    theater: '東欧（ポーランド・ベラルーシ・ウクライナ）',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [21.01, 52.23], label: 'ワルシャワ（1920.8「ヴィスワの奇跡」）', isMain: true },
      { coordinates: [30.52, 50.45], label: 'キーウ（1920.5ポーランド軍占領）', isMain: true },
      { coordinates: [37.62, 55.75], label: 'モスクワ（ソビエト政権）', enemy: true },
      { coordinates: [27.57, 53.90], label: 'ミンスク' },
      { coordinates: [24.10, 56.95], label: 'リガ（1921.3.18講和条約）' },
    ],
    weight: 2,
    tags: ['ナショナリズム', '革命', '冷戦構造', '権力真空'],
    ideologies: ['ポーランド・ナショナリズム', 'ボリシェヴィズム', '共産主義'],
    causes: ['russian-revolution', 'russian-civil-war'],
    influences: ['winter-war'],
  },
  {
    id: 'greco-turkish-war-1919',
    year: 1919, endYear: 1922,
    name: '希土戦争',
    region: 2, type: 'war', era: '20th-century',
    theater: '西アナトリア・エーゲ海沿岸',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [27.14, 38.42], label: 'スミルナ（イズミル・1919上陸／1922大火）', isMain: true },
      { coordinates: [32.85, 39.92], label: 'アンカラ（ケマル政権の首都）', isMain: true },
      { coordinates: [32.14, 39.58], label: 'サカリヤ（1921.8決戦）', enemy: true },
      { coordinates: [28.98, 41.01], label: 'コンスタンティノープル（連合国占領下）' },
      { coordinates: [23.73, 37.98], label: 'アテネ（ギリシャ首都）' },
    ],
    weight: 2,
    tags: ['ナショナリズム', '帝国衰退', '民族浄化', '指導者個人要因'],
    ideologies: ['トルコ・ナショナリズム', 'メガリ・イデア', '世俗主義'],
    causes: ['balkan-wars'],
    influences: ['second-italo-ethiopian-war'],
  },
  {
    id: 'indonesian-national-revolution',
    year: 1945, endYear: 1949,
    name: 'インドネシア独立戦争',
    region: 1, type: 'colonial', era: '20th-century',
    theater: 'ジャワ・スマトラ・東インド諸島',
    mapHighlight: 'asia',
    markers: [
      { coordinates: [106.84, -6.21], label: 'ジャカルタ（1945.8.17独立宣言）', isMain: true },
      { coordinates: [112.75, -7.25], label: 'スラバヤ（1945.11市街戦）', isMain: true },
      { coordinates: [110.37, -7.80], label: 'ジョグジャカルタ（共和国臨時首都）' },
      { coordinates: [4.89, 52.37], label: 'アムステルダム（オランダ本国）', enemy: true },
      { coordinates: [-73.97, 40.78], label: '国連本部（外圧と国際承認）' },
    ],
    weight: 2,
    tags: ['植民地解放', 'ナショナリズム', '冷戦構造'],
    ideologies: ['インドネシア・ナショナリズム', 'パンチャシラ', '反植民地主義'],
    causes: ['pacific-war', 'second-sino-japanese-war'],
    influences: ['first-indochina-war', 'malayan-emergency'],
  },
  {
    id: 'mahdist-war',
    year: 1881, endYear: 1899,
    name: 'マフディー戦争',
    region: 2, type: 'colonial', era: 'early-modern',
    theater: 'スーダン・ナイル上流',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [32.53, 15.50], label: 'ハルツーム（1885.1陥落・ゴードン戦死）', isMain: true },
      { coordinates: [32.49, 15.65], label: 'オムドゥルマン（1898.9決戦）', isMain: true },
      { coordinates: [31.24, 30.04], label: 'カイロ（英・エジプト司令部）', enemy: true },
      { coordinates: [32.78, 19.62], label: 'ドンゴラ（1896キッチナー北部攻略）' },
      { coordinates: [35.36, 9.59], label: 'ファショダ（1898英仏対立）' },
    ],
    weight: 2,
    tags: ['宗教対立', '植民地解放', 'ナショナリズム', '帝国衰退'],
    ideologies: ['イスラム教（マフディー思想）', '帝国主義'],
    causes: ['second-opium-war'],
    influences: ['second-boer-war'],
  },
  {
    id: 'sino-french-war',
    year: 1884, endYear: 1885,
    name: '清仏戦争',
    region: 1, type: 'war', era: 'early-modern',
    theater: 'トンキン（北部ベトナム）・台湾海峡・福建',
    mapHighlight: 'asia',
    markers: [
      { coordinates: [105.85, 21.03], label: 'ハノイ（仏軍トンキン拠点）', isMain: true },
      { coordinates: [119.30, 26.08], label: '福州・馬尾（1884.8仏艦隊奇襲）', isMain: true },
      { coordinates: [106.62, 22.05], label: '鎮南関（1885.3清軍勝利）' },
      { coordinates: [121.52, 25.04], label: '基隆・淡水（1884仏軍上陸）', enemy: true },
      { coordinates: [116.40, 39.90], label: '北京（清・李鴻章）' },
    ],
    weight: 2,
    tags: ['帝国衰退', '植民地解放', '海洋覇権'],
    ideologies: ['帝国主義', '中華秩序'],
    causes: ['second-opium-war'],
    influences: ['first-sino-japanese-war'],
  },
  {
    id: 'russo-georgian-war',
    year: 2008, endYear: 2008,
    name: 'ロシア・グルジア戦争',
    region: 0, type: 'war', era: 'contemporary',
    theater: '南オセチア・アブハジア・グルジア本土',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [43.97, 42.22], label: 'ツヒンヴァリ（8.7戦闘開始）', isMain: true },
      { coordinates: [44.79, 41.71], label: 'トビリシ（グルジア首都・空爆対象）', isMain: true },
      { coordinates: [44.99, 42.98], label: '南オセチア境界' },
      { coordinates: [41.02, 43.00], label: 'スフミ（アブハジア）' },
      { coordinates: [37.62, 55.75], label: 'モスクワ（メドベージェフ・プーチン政権）', enemy: true },
    ],
    weight: 2,
    tags: ['冷戦構造', 'ナショナリズム', '安全保障ジレンマ', '指導者個人要因'],
    ideologies: ['ロシア・ナショナリズム', '主権概念（ロシア式）', '反NATO'],
    causes: ['chechen-wars', 'kosovo-war'],
    influences: ['ukraine-war'],
  },
  {
    id: 'first-italo-ethiopian-war',
    year: 1895, endYear: 1896,
    name: '第一次エチオピア戦争',
    region: 2, type: 'colonial', era: 'early-modern',
    theater: 'エチオピア北部・エリトリア',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [38.97, 14.13], label: 'アドワ（1896.3.1決戦）', isMain: true },
      { coordinates: [38.74, 9.03], label: 'アディスアベバ（メネリク2世の都）', isMain: true },
      { coordinates: [39.47, 15.34], label: 'アスマラ（伊領エリトリア拠点）', enemy: true },
      { coordinates: [39.47, 13.49], label: 'メケレ（1896.1包囲戦）' },
      { coordinates: [12.49, 41.90], label: 'ローマ（クリスピ首相辞任）', enemy: true },
    ],
    weight: 2,
    tags: ['植民地解放', 'ナショナリズム', '帝国衰退'],
    ideologies: ['帝国主義', 'エチオピア・ナショナリズム', '正教会'],
    causes: ['italian-unification'],
    influences: ['second-italo-ethiopian-war', 'mahdist-war'],
  },
];
