import { War } from './types';
/** 中世戦争（追加分） */
export const WARS_MEDIEVAL_EXTRA: War[] = [
  {
    id: 'battle-of-tours',
    year: 732, endYear: 732,
    name: 'トゥール・ポワティエ間の戦い',
    region: 0, type: 'war', era: 'medieval',
    theater: 'フランク王国南西部（アキテーヌ）',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [0.34, 46.58], label: 'ポワティエ（732.10.10決戦地周辺）', isMain: true },
      { coordinates: [0.69, 47.39], label: 'トゥール（聖マルティヌス修道院）', isMain: true },
      { coordinates: [-0.58, 44.84], label: 'ボルドー（ウマイヤ朝侵攻路）' },
      { coordinates: [-5.99, 37.39], label: 'コルドバ（後ウマイヤ朝拠点）', enemy: true },
      { coordinates: [3.88, 43.61], label: 'セプティマニア（ナルボンヌ・イスラム拠点）' },
    ],
    weight: 2,
    tags: ['宗教対立', '権力真空', '文明衝突'],
    ideologies: ['キリスト教', 'イスラム教'],
    causes: ['arab-conquests'],
    influences: ['frankish-conquests', 'reconquista-final'],
  },
  {
    id: 'battle-of-manzikert',
    year: 1071, endYear: 1071,
    name: 'マラズギルトの戦い',
    region: 2, type: 'war', era: 'medieval',
    theater: '東アナトリア（ヴァン湖北方）',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [42.54, 39.14], label: 'マラズギルト（1071.8.26決戦）', isMain: true },
      { coordinates: [28.98, 41.01], label: 'コンスタンティノープル（ビザンツ首都）', isMain: true },
      { coordinates: [51.42, 35.69], label: 'レイ（セルジューク朝拠点・アルプ・アルスラーン）', enemy: true },
      { coordinates: [43.38, 38.50], label: 'ヴァン湖' },
      { coordinates: [32.85, 39.92], label: 'ルーム・セルジューク朝（後にアナトリア中央部）' },
    ],
    weight: 3,
    tags: ['帝国衰退', '宗教対立', '指導者個人要因', '遊牧vs農耕'],
    ideologies: ['イスラム教', '正教会'],
    causes: ['arab-conquests'],
    influences: ['first-crusade', 'fall-constantinople'],
  },
  {
    id: 'albigensian-crusade',
    year: 1209, endYear: 1229,
    name: 'アルビジョア十字軍',
    region: 0, type: 'war', era: 'medieval',
    theater: '南フランス・ラングドック',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [2.21, 43.36], label: 'カルカソンヌ（1209陥落）', isMain: true },
      { coordinates: [3.22, 43.34], label: 'ベジエ（1209.7虐殺）', isMain: true },
      { coordinates: [2.15, 43.93], label: 'アルビ（カタリ派の中心）' },
      { coordinates: [12.49, 41.90], label: 'ローマ（教皇インノケンティウス3世）', enemy: true },
      { coordinates: [1.83, 42.88], label: 'モンセギュール（1244年カタリ派最後の砦）' },
    ],
    weight: 2,
    tags: ['宗教対立', '指導者個人要因'],
    ideologies: ['カトリック', 'カタリ派（二元論異端）'],
    causes: ['first-crusade'],
    influences: ['hundred-years-war'],
  },
  {
    id: 'wars-scottish-independence',
    year: 1296, endYear: 1357,
    name: 'スコットランド独立戦争',
    region: 0, type: 'war', era: 'medieval',
    theater: 'スコットランド・イングランド北部',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [-3.94, 56.13], label: 'スターリング・ブリッジ（1297.9・ウォレス勝利）', isMain: true },
      { coordinates: [-3.79, 56.00], label: 'バノックバーン（1314.6.24・ロバート・ブルース勝利）', isMain: true },
      { coordinates: [-3.79, 55.99], label: 'フォルカーク（1298・ウォレス敗北）' },
      { coordinates: [-3.19, 55.95], label: 'エディンバラ（1328年条約調印地）' },
      { coordinates: [-0.13, 51.51], label: 'ロンドン（イングランド王エドワード1世）', enemy: true },
    ],
    weight: 2,
    tags: ['ナショナリズム', '指導者個人要因', '権力真空'],
    ideologies: ['スコットランド・ナショナリズム', '封建制'],
    causes: ['norman-conquest-england'],
    influences: ['hundred-years-war'],
  },
  {
    id: 'hussite-wars',
    year: 1419, endYear: 1434,
    name: 'フス戦争',
    region: 0, type: 'revolution', era: 'medieval',
    theater: 'ボヘミア（現チェコ）・中欧',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [14.42, 50.09], label: 'プラハ（1419第一次窓外投擲事件）', isMain: true },
      { coordinates: [9.17, 47.66], label: 'コンスタンツ（1415フス火刑）', isMain: true },
      { coordinates: [14.69, 49.43], label: 'ターボル（急進派ターボル派の拠点）' },
      { coordinates: [14.78, 50.07], label: 'リパニ（1434.5.30・穏健派勝利）' },
      { coordinates: [16.61, 49.20], label: 'モラヴィア（戦線拡大）' },
    ],
    weight: 2,
    tags: ['宗教対立', '革命', 'ナショナリズム'],
    ideologies: ['フス派', 'カトリック', 'チェコ・ナショナリズム'],
    causes: ['black-death-jacquerie'],
    influences: ['wars-of-the-roses'],
  },
  {
    id: 'wars-of-the-roses',
    year: 1455, endYear: 1487,
    name: 'バラ戦争',
    region: 0, type: 'war', era: 'medieval',
    theater: 'イングランド全域',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [-0.34, 51.75], label: 'セント・オールバンズ（1455.5.22開戦）', isMain: true },
      { coordinates: [-1.27, 53.84], label: 'タウトン（1461.3.29・ヨーク家大勝）', isMain: true },
      { coordinates: [-1.41, 52.59], label: 'ボズワース・フィールド（1485.8.22・ヘンリー7世勝利）', isMain: true },
      { coordinates: [-0.86, 52.95], label: 'ストーク・フィールド（1487.6.16・最終戦）' },
      { coordinates: [-0.13, 51.51], label: 'ロンドン（テューダー朝成立）' },
    ],
    weight: 2,
    tags: ['指導者個人要因', '権力真空', 'ナショナリズム', '王朝継承'],
    ideologies: ['封建制', '王朝正統性'],
    causes: ['hundred-years-war'],
    influences: [],
  },
];
