import { War } from './types';

/** 近世初期戦争（1450-1700年）— 主要12戦争 */
export const WARS_RENAISSANCE: War[] = [
  {
    id: 'italian-wars',
    year: 1494, endYear: 1559,
    name: 'イタリア戦争',
    region: 0, type: 'war', era: 'renaissance',
    theater: 'イタリア半島・西欧',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [2.3, 48.9], label: 'パリ（フランス・シャルル8世以降のヴァロワ朝）', isMain: true },
      { coordinates: [-3.7, 40.4], label: 'マドリード（スペイン・ハプスブルク家）', enemy: true },
      { coordinates: [12.5, 41.9], label: 'ローマ（1527年「ローマ劫掠」）' },
      { coordinates: [9.16, 45.18], label: 'パヴィア（1525年フランソワ1世捕囚）', isMain: true },
      { coordinates: [3.66, 50.31], label: 'カトー＝カンブレジ（1559年講和条約）' },
    ],
    weight: 2,
    tags: ['帝国衰退', '同盟暴走', '指導者個人要因', '軍事革命'],
    ideologies: ['ルネサンス君主政', '勢力均衡'],
    causes: [],
    influences: ['french-wars-of-religion', 'dutch-revolt', 'thirty-years-war'],
  },
  {
    id: 'spanish-conquest-mexico',
    year: 1519, endYear: 1521,
    name: 'スペインによるアステカ征服',
    region: 3, type: 'war', era: 'renaissance',
    theater: 'メキシコ中央高原',
    mapHighlight: 'americas',
    markers: [
      { coordinates: [-99.13, 19.43], label: 'テノチティトラン（アステカ首都・1521年8月13日陥落）', isMain: true },
      { coordinates: [-96.13, 19.20], label: 'ベラクルス（1519年コルテス上陸地）' },
      { coordinates: [-98.30, 19.30], label: 'トラスカラ（コルテスの先住民同盟者）', ally: true },
      { coordinates: [-99.18, 19.46], label: '「悲しき夜」（1520年6月30日の敗走）' },
      { coordinates: [-3.7, 40.4], label: 'マドリード（カルロス1世＝カール5世）', isMain: true },
    ],
    weight: 3,
    tags: ['資源争奪', '権力真空', '宗教対立', '指導者個人要因', '文明衝突'],
    ideologies: ['カトリック布教', '重商主義', '征服国家'],
    causes: [],
    influences: ['spanish-conquest-peru', 'anglo-spanish-war'],
  },
  {
    id: 'spanish-conquest-peru',
    year: 1532, endYear: 1572,
    name: 'スペインによるインカ征服',
    region: 3, type: 'war', era: 'renaissance',
    theater: 'アンデス山脈・ペルー',
    mapHighlight: 'americas',
    markers: [
      { coordinates: [-78.51, -6.46], label: 'カハマルカ（1532年11月16日アタワルパ捕縛）', isMain: true },
      { coordinates: [-71.97, -13.52], label: 'クスコ（1533年陥落・インカ旧都）', isMain: true },
      { coordinates: [-77.04, -12.05], label: 'リマ（1535年スペイン副王領首都建設）' },
      { coordinates: [-72.55, -13.16], label: 'ビルカバンバ（最後の抵抗・1572年トゥパク・アマル処刑）' },
      { coordinates: [-3.7, 40.4], label: 'マドリード（スペイン王権）', isMain: true },
    ],
    weight: 3,
    tags: ['資源争奪', '権力真空', '宗教対立', '指導者個人要因', '文明衝突'],
    ideologies: ['カトリック布教', '重商主義', '征服国家'],
    causes: ['spanish-conquest-mexico'],
    influences: ['anglo-spanish-war', 'dutch-revolt'],
  },
  {
    id: 'sengoku-unification',
    year: 1467, endYear: 1615,
    name: '戦国時代統一戦争（信長・秀吉・家康）',
    region: 1, type: 'war', era: 'renaissance',
    theater: '日本列島',
    mapHighlight: 'asia',
    markers: [
      { coordinates: [135.77, 35.01], label: '京都（応仁の乱1467・室町幕府）', isMain: true },
      { coordinates: [136.96, 35.11], label: '桶狭間（1560年信長対今川）' },
      { coordinates: [136.59, 35.36], label: '関ヶ原（1600年家康勝利・東軍）', isMain: true },
      { coordinates: [135.50, 34.69], label: '大坂（1614-15年大坂の陣・豊臣家滅亡）', isMain: true },
      { coordinates: [139.69, 35.69], label: '江戸（1603年徳川幕府開府）' },
    ],
    cotenLinks: [
      { title: '織田信長編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E7%B9%94%E7%94%B0%E4%BF%A1%E9%95%B7' },
      { title: '秀吉・家康編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E7%A7%80%E5%90%89%E3%83%BB%E5%AE%B6%E5%BA%B7' },
    ],
    weight: 3,
    tags: ['権力真空', '帝国衰退', '指導者個人要因', '同盟暴走', '王朝継承'],
    ideologies: ['封建制', '中央集権', '兵農分離'],
    causes: [],
    influences: ['imjin-war'],
  },
  {
    id: 'french-wars-of-religion',
    year: 1562, endYear: 1598,
    name: 'ユグノー戦争',
    region: 0, type: 'war', era: 'renaissance',
    theater: 'フランス全土',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [2.3, 48.9], label: 'パリ（1572年8月24日サン・バルテルミの虐殺）', isMain: true },
      { coordinates: [4.95, 48.80], label: 'ヴァシー（1562年虐殺・開戦）' },
      { coordinates: [-1.15, 46.16], label: 'ラ・ロシェル（ユグノー拠点）', ally: true },
      { coordinates: [-0.58, 44.84], label: 'ナヴァール王アンリ（後のアンリ4世）の本拠' },
      { coordinates: [-1.48, 47.22], label: 'ナント（1598年ナントの勅令）', isMain: true },
    ],
    weight: 2,
    tags: ['宗教対立', '権力真空', '情報戦・プロパガンダ', '指導者個人要因'],
    ideologies: ['カトリック', 'カルヴァン主義', '王権神授説'],
    causes: ['italian-wars'],
    influences: ['thirty-years-war', 'dutch-revolt'],
  },
  {
    id: 'dutch-revolt',
    year: 1568, endYear: 1648,
    name: 'オランダ独立戦争（八十年戦争）',
    region: 0, type: 'revolution', era: 'renaissance',
    theater: 'ネーデルラント（低地諸国）',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [4.90, 52.37], label: 'アムステルダム（オランダ反乱拠点）', isMain: true },
      { coordinates: [-3.7, 40.4], label: 'マドリード（スペイン・フェリペ2世）', enemy: true },
      { coordinates: [4.30, 52.07], label: 'デルフト（オラニエ公ウィレム暗殺1584年）' },
      { coordinates: [4.48, 51.92], label: 'ロッテルダム（海乞食ホイセン拠点）' },
      { coordinates: [6.96, 50.97], label: 'ヴェストファーレン（1648年ミュンスター講和）', isMain: true },
    ],
    weight: 3,
    tags: ['宗教対立', 'ナショナリズム', '革命', '帝国衰退'],
    ideologies: ['カルヴァン主義', '共和主義', '商業ブルジョワジー'],
    causes: ['italian-wars', 'french-wars-of-religion'],
    influences: ['anglo-spanish-war', 'thirty-years-war', 'english-civil-war'],
  },
  {
    id: 'anglo-spanish-war',
    year: 1585, endYear: 1604,
    name: 'スペイン無敵艦隊',
    region: 0, type: 'war', era: 'renaissance',
    theater: '英仏海峡・大西洋',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [-0.13, 51.51], label: 'ロンドン（エリザベス1世）', isMain: true },
      { coordinates: [-3.7, 40.4], label: 'マドリード（フェリペ2世）', enemy: true },
      { coordinates: [-6.27, 36.53], label: 'カディス（1587年ドレイク奇襲・艦隊集結地）' },
      { coordinates: [1.85, 50.97], label: 'グラブリーヌ（1588年7月29日決戦・英艦勝利）', isMain: true },
      { coordinates: [-0.13, 51.51], label: 'ロンドン条約（1604年講和）' },
    ],
    cotenLinks: [
      { title: 'エリザベス一世編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E3%82%A8%E3%83%AA%E3%82%B6%E3%83%99%E3%82%B9%E4%B8%80%E4%B8%96' },
    ],
    weight: 2,
    tags: ['宗教対立', '帝国衰退', '情報戦・プロパガンダ', '誤算・誤認知', '海洋覇権'],
    ideologies: ['国教会', 'カトリック', '重商主義'],
    causes: ['dutch-revolt', 'spanish-conquest-mexico'],
    influences: ['thirty-years-war', 'english-civil-war'],
  },
  {
    id: 'imjin-war',
    year: 1592, endYear: 1598,
    name: '文禄・慶長の役（壬辰倭乱）',
    region: 1, type: 'war', era: 'renaissance',
    theater: '朝鮮半島・対馬海峡',
    mapHighlight: 'asia',
    markers: [
      { coordinates: [129.04, 35.10], label: '釜山（1592年4月日本軍上陸）', isMain: true },
      { coordinates: [126.98, 37.57], label: '漢城（ソウル・1592年5月陥落）' },
      { coordinates: [128.42, 34.84], label: '閑山島（1592年李舜臣の亀甲船勝利）', ally: true },
      { coordinates: [125.75, 39.04], label: '平壌（明軍参戦・1593年奪還）' },
      { coordinates: [127.76, 34.76], label: '露梁海戦（1598年11月・李舜臣戦死・終戦）', isMain: true },
    ],
    cotenLinks: [
      { title: '秀吉・家康編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E7%A7%80%E5%90%89%E3%83%BB%E5%AE%B6%E5%BA%B7' },
    ],
    weight: 2,
    tags: ['指導者個人要因', '同盟暴走', '誤算・誤認知', '帝国衰退', '文明衝突', '海洋覇権'],
    ideologies: ['朱子学', '中華秩序', '兵農分離'],
    causes: ['sengoku-unification'],
    influences: ['ming-qing-transition'],
  },
  {
    id: 'thirty-years-war',
    year: 1618, endYear: 1648,
    name: '三十年戦争',
    region: 0, type: 'war', era: 'renaissance',
    theater: '神聖ローマ帝国・中欧',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [14.42, 50.09], label: 'プラハ（1618年5月窓外投擲事件・開戦）', isMain: true },
      { coordinates: [12.10, 49.78], label: '白山の戦い（1620年・ボヘミア反乱鎮圧）' },
      { coordinates: [12.13, 51.12], label: 'リュッツェン（1632年グスタフ・アドルフ戦死）', isMain: true },
      { coordinates: [11.07, 49.45], label: 'ニュルンベルク（神聖ローマ帝国の戦災中心）' },
      { coordinates: [7.62, 51.96], label: 'ミュンスター・オスナブリュック（1648年ヴェストファーレン条約）', isMain: true },
    ],
    weight: 3,
    tags: ['宗教対立', '同盟暴走', '帝国衰退', '誤算・誤認知', '軍事革命'],
    ideologies: ['カトリック', 'プロテスタント', '主権国家', '勢力均衡'],
    causes: ['french-wars-of-religion', 'dutch-revolt', 'italian-wars'],
    influences: ['great-northern-war', 'great-turkish-war', 'war-of-spanish-succession'],
  },
  {
    id: 'english-civil-war',
    year: 1642, endYear: 1651,
    name: '清教徒革命（イングランド内戦）',
    region: 0, type: 'revolution', era: 'renaissance',
    theater: 'イングランド・スコットランド・アイルランド',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [-0.13, 51.51], label: 'ロンドン（議会派・1649年1月30日チャールズ1世処刑）', isMain: true },
      { coordinates: [-1.25, 51.75], label: 'オックスフォード（王党派本拠）', enemy: true },
      { coordinates: [-1.07, 53.97], label: 'マーストン・ムーア（1644年議会派決定的勝利）' },
      { coordinates: [-0.93, 52.34], label: 'ネイズビー（1645年クロムウェル新型軍勝利）', isMain: true },
      { coordinates: [-2.21, 52.19], label: 'ウースター（1651年最終決戦）' },
    ],
    weight: 3,
    tags: ['革命', '宗教対立', '権力真空', 'ナショナリズム', '王朝継承'],
    ideologies: ['ピューリタニズム', '議会主義', '王権神授説', '共和主義'],
    causes: ['dutch-revolt', 'anglo-spanish-war', 'thirty-years-war'],
    influences: [],
  },
  {
    id: 'ming-qing-transition',
    year: 1618, endYear: 1683,
    name: '明清交替（満州征服）',
    region: 1, type: 'war', era: 'renaissance',
    theater: '中国本土・満州',
    mapHighlight: 'asia',
    markers: [
      { coordinates: [123.43, 41.80], label: '瀋陽（後金・清の本拠地）', isMain: true },
      { coordinates: [116.40, 39.90], label: '北京（1644年4月李自成入城・5月清軍入城）', isMain: true },
      { coordinates: [119.55, 40.00], label: '山海関（1644年5月呉三桂が清軍を導入）' },
      { coordinates: [113.27, 23.13], label: '広州（1673-81年三藩の乱・呉三桂反乱）' },
      { coordinates: [120.30, 22.99], label: '台湾（1683年鄭氏政権降伏・最終統一）', isMain: true },
    ],
    weight: 3,
    tags: ['帝国衰退', '権力真空', '経済危機', 'ナショナリズム'],
    ideologies: ['朱子学', '満州人優越', '辮髪'],
    causes: ['imjin-war'],
    influences: [],
  },
  {
    id: 'great-turkish-war',
    year: 1683, endYear: 1699,
    name: '大トルコ戦争（第二次ウィーン包囲〜カルロヴィッツ）',
    region: 0, type: 'war', era: 'renaissance',
    theater: 'バルカン半島・中欧',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [16.37, 48.21], label: 'ウィーン（1683年9月12日包囲解放）', isMain: true },
      { coordinates: [28.98, 41.01], label: 'イスタンブル（オスマン帝国・メフメト4世）', enemy: true },
      { coordinates: [19.04, 47.50], label: 'ブダ（1686年ハプスブルク奪還）' },
      { coordinates: [21.32, 45.78], label: 'ゼンタ（1697年オイゲン公決定的勝利）', isMain: true },
      { coordinates: [21.18, 45.13], label: 'カルロヴィッツ（1699年講和条約）', isMain: true },
    ],
    cotenLinks: [
      { title: 'オスマン帝国編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E3%82%AA%E3%82%B9%E3%83%9E%E3%83%B3%E5%B8%9D%E5%9B%BD' },
    ],
    weight: 2,
    tags: ['帝国衰退', '宗教対立', '同盟暴走', '誤算・誤認知'],
    ideologies: ['イスラーム', 'カトリック', '勢力均衡'],
    causes: ['thirty-years-war'],
    influences: ['great-northern-war', 'war-of-spanish-succession'],
  },
];
