import { War } from './types';

/** 中世戦争（500-1450年）— 段階的に拡充中 */
export const WARS_MEDIEVAL: War[] = [
  {
    id: 'arab-conquests',
    year: 632, endYear: 750,
    name: 'アラブ大征服',
    region: 2, type: 'war', era: 'medieval',
    theater: 'アラビア半島・中東・北アフリカ・イベリア半島・中央アジア',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [39.8, 21.4], label: 'メッカ（ムハンマド・イスラム発祥）', isMain: true },
      { coordinates: [36.0, 32.7], label: 'ヤルムーク（636年・対ビザンツ決戦）', isMain: true },
      { coordinates: [44.4, 33.3], label: 'カーディシーヤ（637年・対サーサーン朝）' },
      { coordinates: [-5.4, 36.0], label: 'ジブラルタル（711年・イベリア侵攻）' },
      { coordinates: [72.2, 42.5], label: 'タラス河畔（751年・対唐）' },
    ],
    weight: 3,
    tags: ['宗教対立', '帝国衰退', 'ナショナリズム'],
    ideologies: ['イスラム教', 'カリフ制'],
    causes: [],
    influences: ['first-crusade', 'reconquista-final'],
  },
  {
    id: 'frankish-conquests',
    year: 768, endYear: 814,
    name: 'カール大帝の征服',
    region: 0, type: 'war', era: 'medieval',
    theater: '西欧・中欧・イタリア半島',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [6.1, 50.8], label: 'アーヘン（カール大帝の宮廷）', isMain: true },
      { coordinates: [9.2, 52.4], label: 'ザクセン戦争（772-804）' },
      { coordinates: [10.0, 45.5], label: 'ロンバルディア征服（774年）' },
      { coordinates: [12.5, 41.9], label: 'ローマ（800年戴冠）', isMain: true },
      { coordinates: [-1.3, 43.0], label: 'ロンスヴォー（778年・ローランの歌）' },
    ],
    weight: 2,
    tags: ['宗教対立', 'ナショナリズム', '指導者個人要因'],
    ideologies: ['キリスト教', 'ローマ帝国理念'],
    causes: [],
    influences: ['viking-invasions'],
  },
  {
    id: 'viking-invasions',
    year: 793, endYear: 1066,
    name: 'ヴァイキング侵攻',
    region: 0, type: 'war', era: 'medieval',
    theater: '北欧・北海・西欧・東欧・地中海',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [-1.6, 55.7], label: 'リンディスファーン（793年・襲撃開始）', isMain: true },
      { coordinates: [10.7, 59.9], label: 'オスロ（ノルウェー）' },
      { coordinates: [-21.9, 64.1], label: 'アイスランド入植（870年代）' },
      { coordinates: [30.5, 50.5], label: 'キエフ（ルーシ建国）' },
      { coordinates: [-2.0, 49.0], label: 'ノルマンディー（911年・ロロ定住）' },
    ],
    weight: 2,
    tags: ['資源争奪', '権力真空'],
    ideologies: ['北欧異教', 'キリスト教改宗'],
    causes: ['frankish-conquests'],
    influences: ['norman-conquest-england'],
  },
  {
    id: 'norman-conquest-england',
    year: 1066, endYear: 1066,
    name: 'ノルマン・コンクエスト',
    region: 0, type: 'war', era: 'medieval',
    theater: 'イングランド南部・イギリス海峡',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [0.5, 49.4], label: 'ノルマンディー（ウィリアム公）', isMain: true },
      { coordinates: [0.4, 50.9], label: 'ヘイスティングズ（1066.10.14決戦）', isMain: true },
      { coordinates: [-1.3, 51.0], label: 'スタンフォード・ブリッジ（9.25・対ノルウェー）' },
      { coordinates: [-0.1, 51.5], label: 'ロンドン（戴冠12.25）' },
      { coordinates: [10.7, 59.9], label: 'ノルウェー王ハーラル3世（敗北）', enemy: true },
    ],
    weight: 2,
    tags: ['指導者個人要因', '権力真空'],
    ideologies: ['封建制', 'キリスト教'],
    causes: ['viking-invasions'],
    influences: ['hundred-years-war'],
  },
  {
    id: 'first-crusade',
    year: 1095, endYear: 1099,
    name: '第一回十字軍',
    region: 2, type: 'war', era: 'medieval',
    theater: '西欧・東地中海・レヴァント',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [4.9, 45.0], label: 'クレルモン（1095教皇ウルバヌス2世演説）', isMain: true },
      { coordinates: [28.9, 41.0], label: 'コンスタンティノープル（集結地）' },
      { coordinates: [36.2, 36.2], label: 'アンティオキア（1098陥落）', isMain: true },
      { coordinates: [35.2, 31.8], label: 'エルサレム（1099.7.15陥落）', isMain: true },
      { coordinates: [35.0, 32.5], label: 'エルサレム王国（十字軍国家）' },
    ],
    cotenLinks: [
      { title: 'サラディンと十字軍編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E3%82%B5%E3%83%A9%E3%83%87%E3%82%A3%E3%83%B3%E3%81%A8%E5%8D%81%E5%AD%97%E8%BB%8D' },
    ],
    weight: 3,
    tags: ['宗教対立', '指導者個人要因', '情報戦・プロパガンダ'],
    ideologies: ['キリスト教', 'イスラム教'],
    causes: ['arab-conquests'],
    influences: ['third-crusade', 'fourth-crusade'],
  },
  {
    id: 'third-crusade',
    year: 1189, endYear: 1192,
    name: '第三回十字軍（サラディン対決）',
    region: 2, type: 'war', era: 'medieval',
    theater: '東地中海・パレスチナ',
    mapHighlight: 'middle-east',
    markers: [
      { coordinates: [35.2, 31.8], label: 'エルサレム（1187サラディン奪還）', isMain: true },
      { coordinates: [35.1, 32.9], label: 'アッコン包囲（1189-1191）', isMain: true },
      { coordinates: [34.9, 32.5], label: 'アルスフ（1191.9リチャード勝利）' },
      { coordinates: [34.7, 31.7], label: 'ヤッファ（1192休戦）' },
      { coordinates: [-1.5, 47.2], label: 'リチャード1世（イングランド）', ally: true },
    ],
    cotenLinks: [
      { title: 'サラディンと十字軍編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E3%82%B5%E3%83%A9%E3%83%87%E3%82%A3%E3%83%B3%E3%81%A8%E5%8D%81%E5%AD%97%E8%BB%8D' },
    ],
    weight: 2,
    tags: ['宗教対立', '指導者個人要因'],
    ideologies: ['キリスト教', 'イスラム教'],
    causes: ['first-crusade'],
    influences: ['fourth-crusade'],
  },
  {
    id: 'fourth-crusade',
    year: 1202, endYear: 1204,
    name: '第四回十字軍（コンスタンティノープル略奪）',
    region: 0, type: 'war', era: 'medieval',
    theater: 'アドリア海・東地中海・ビザンツ帝国',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [12.3, 45.4], label: 'ヴェネツィア（艦隊提供・ダンドロ）', isMain: true },
      { coordinates: [14.4, 44.9], label: 'ザラ陥落（1202年・キリスト教都市攻撃）' },
      { coordinates: [28.9, 41.0], label: 'コンスタンティノープル略奪（1204.4）', isMain: true },
      { coordinates: [22.9, 40.6], label: 'テッサロニキ王国（ラテン帝国分割）' },
      { coordinates: [27.4, 39.6], label: 'ニカイア帝国（亡命ビザンツ）' },
    ],
    weight: 2,
    tags: ['宗教対立', '資源争奪', '指導者個人要因'],
    ideologies: ['キリスト教', 'カトリック', '正教会'],
    causes: ['first-crusade', 'third-crusade'],
    influences: ['fall-constantinople'],
  },
  {
    id: 'mongol-invasions',
    year: 1206, endYear: 1294,
    name: 'モンゴル帝国の征服',
    region: 1, type: 'war', era: 'medieval',
    theater: 'ユーラシア大陸全域',
    mapHighlight: 'asia',
    markers: [
      { coordinates: [106.9, 47.9], label: 'カラコルム（モンゴル本拠）', isMain: true },
      { coordinates: [68.8, 32.5], label: 'インダス河畔（1221年）' },
      { coordinates: [44.4, 33.3], label: 'バグダード陥落（1258・アッバース朝滅亡）', isMain: true },
      { coordinates: [37.6, 55.8], label: 'モスクワ・ルーシ侵攻（1237-1240）' },
      { coordinates: [129.5, 33.6], label: '元寇（1274・1281日本侵攻）' },
    ],
    cotenLinks: [
      { title: 'チンギス・カン編', url: 'https://pody.jp/player/hh0fJGjBuDtPNVFIvZKq?view=series&series=%E3%83%81%E3%83%B3%E3%82%AE%E3%82%B9%E3%83%BB%E3%82%AB%E3%83%B3' },
    ],
    weight: 3,
    tags: ['指導者個人要因', '資源争奪', '帝国衰退'],
    ideologies: ['モンゴル普遍帝国理念', 'テングリ信仰'],
    causes: [],
    influences: ['black-death-jacquerie', 'timur-conquests'],
  },
  {
    id: 'genpei-war',
    year: 1180, endYear: 1185,
    name: '源平合戦',
    region: 1, type: 'war', era: 'medieval',
    theater: '日本列島',
    mapHighlight: 'asia',
    markers: [
      { coordinates: [135.7, 35.0], label: '京都（平氏政権）', enemy: true },
      { coordinates: [139.6, 35.3], label: '鎌倉（源頼朝挙兵）', isMain: true },
      { coordinates: [134.1, 34.4], label: '屋島の戦い（1185.2）' },
      { coordinates: [130.9, 33.9], label: '壇ノ浦（1185.3.24・平氏滅亡）', isMain: true },
      { coordinates: [136.2, 36.3], label: '倶利伽羅峠（1183年・木曾義仲）' },
    ],
    weight: 2,
    tags: ['権力真空', '指導者個人要因'],
    ideologies: ['武士道', '幕府制'],
    causes: [],
    influences: ['onin-war'],
  },
  {
    id: 'reconquista-final',
    year: 1212, endYear: 1492,
    name: 'レコンキスタ最終局面',
    region: 0, type: 'war', era: 'medieval',
    theater: 'イベリア半島',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [-3.5, 38.3], label: 'ラス・ナバス・デ・トロサ（1212決戦）', isMain: true },
      { coordinates: [-5.9, 37.4], label: 'セビリア奪還（1248）' },
      { coordinates: [-3.6, 37.2], label: 'グラナダ陥落（1492.1.2）', isMain: true },
      { coordinates: [-3.7, 40.4], label: 'カスティーリャ王国（イサベル）', ally: true },
      { coordinates: [-0.4, 39.5], label: 'アラゴン王国（フェルナンド）', ally: true },
    ],
    weight: 3,
    tags: ['宗教対立', 'ナショナリズム', '帝国衰退'],
    ideologies: ['キリスト教', 'カトリック'],
    causes: ['arab-conquests'],
    influences: ['fall-constantinople'],
  },
  {
    id: 'hundred-years-war',
    year: 1337, endYear: 1453,
    name: '百年戦争',
    region: 0, type: 'war', era: 'medieval',
    theater: 'フランス・イングランド・低地地方',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [2.3, 48.9], label: 'パリ（フランス王国）', ally: true },
      { coordinates: [-0.1, 51.5], label: 'ロンドン（イングランド王国）', enemy: true },
      { coordinates: [1.9, 50.3], label: 'クレシー（1346・長弓の威力）', isMain: true },
      { coordinates: [2.1, 50.5], label: 'アジャンクール（1415ヘンリー5世勝利）', isMain: true },
      { coordinates: [1.7, 47.9], label: 'オルレアン（1429ジャンヌ・ダルク解放）', isMain: true },
    ],
    weight: 3,
    tags: ['ナショナリズム', '指導者個人要因', '経済危機'],
    ideologies: ['封建制', '王権神授説'],
    causes: ['norman-conquest-england'],
    influences: ['black-death-jacquerie'],
  },
  {
    id: 'black-death-jacquerie',
    year: 1346, endYear: 1358,
    name: '黒死病とジャックリー一揆',
    region: 0, type: 'revolution', era: 'medieval',
    theater: '欧州全域・北フランス',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [33.5, 44.6], label: 'カッファ（1346・ペスト欧州伝来）', isMain: true },
      { coordinates: [12.5, 41.9], label: 'ローマ・イタリア（1347-48大流行）' },
      { coordinates: [2.6, 49.4], label: 'ボーヴェジ地方（1358ジャックリー一揆）', isMain: true },
      { coordinates: [-0.1, 51.5], label: 'ロンドン（1381ワット・タイラーの乱）' },
      { coordinates: [2.3, 48.9], label: 'パリ（エティエンヌ・マルセル蜂起）' },
    ],
    weight: 1,
    tags: ['経済危機', '革命', '権力真空'],
    ideologies: ['農民闘争', '中世キリスト教'],
    causes: ['mongol-invasions', 'hundred-years-war'],
    influences: [],
  },
  {
    id: 'onin-war',
    year: 1467, endYear: 1477,
    name: '応仁の乱',
    region: 1, type: 'war', era: 'medieval',
    theater: '京都・日本各地',
    mapHighlight: 'asia',
    markers: [
      { coordinates: [135.7, 35.0], label: '京都（戦場）', isMain: true },
      { coordinates: [135.7, 35.0], label: '東軍・細川勝元', ally: true },
      { coordinates: [135.7, 35.0], label: '西軍・山名宗全', enemy: true },
      { coordinates: [135.5, 34.7], label: '室町幕府（足利義政）' },
      { coordinates: [135.8, 35.0], label: '相国寺（戦火で焼失）' },
    ],
    weight: 2,
    tags: ['権力真空', '同盟暴走', '指導者個人要因'],
    ideologies: ['武家政治', '守護大名制'],
    causes: ['genpei-war'],
    influences: [],
  },
  {
    id: 'timur-conquests',
    year: 1370, endYear: 1405,
    name: 'ティムール帝国の征服',
    region: 1, type: 'war', era: 'medieval',
    theater: '中央アジア・西アジア・南アジア',
    mapHighlight: 'asia',
    markers: [
      { coordinates: [66.9, 39.7], label: 'サマルカンド（首都）', isMain: true },
      { coordinates: [77.2, 28.6], label: 'デリー略奪（1398）', isMain: true },
      { coordinates: [32.9, 39.9], label: 'アンカラの戦い（1402・対オスマン）', isMain: true },
      { coordinates: [44.4, 33.3], label: 'バグダード破壊（1401）' },
      { coordinates: [37.2, 36.2], label: 'アレッポ陥落（1400）' },
    ],
    weight: 3,
    tags: ['指導者個人要因', '資源争奪', '帝国衰退'],
    ideologies: ['イスラム教', 'モンゴル正統性'],
    causes: ['mongol-invasions'],
    influences: ['fall-constantinople'],
  },
  {
    id: 'fall-constantinople',
    year: 1453, endYear: 1453,
    name: 'コンスタンティノープル陥落',
    region: 0, type: 'war', era: 'medieval',
    theater: 'ボスポラス海峡・コンスタンティノープル',
    mapHighlight: 'europe',
    markers: [
      { coordinates: [28.9, 41.0], label: 'コンスタンティノープル（1453.5.29陥落）', isMain: true },
      { coordinates: [29.0, 41.0], label: 'テオドシウスの城壁（最後の防衛線）', isMain: true },
      { coordinates: [29.1, 41.0], label: '金角湾（オスマン艦隊陸送）' },
      { coordinates: [26.4, 40.2], label: 'ガリポリ（オスマン拠点）' },
      { coordinates: [32.5, 40.1], label: 'メフメト2世（征服王）', enemy: true },
    ],
    weight: 3,
    tags: ['宗教対立', '帝国衰退', '指導者個人要因'],
    ideologies: ['イスラム教', '正教会'],
    causes: ['fourth-crusade', 'timur-conquests'],
    influences: [],
  },
];
